### ISSUE TITLE
Allow cd mode for drives that don't read into the lead-in of audio discs

### ISSUE THREAD

**Issue by ssjkakaroto** [saramibreak/DiscImageCreator#1]
Hi sarami, right now, DIC aborts reading the disc if the drive reports an error reading the lead-in, like this:
```
Set read command: 0xbe, subcode reading mode: Raw
LBA[-00001, 0xffffffff], [F:ReadCDPartial][L:2235] OperationCode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, 04, ff, ff, ff, ff, 00, 00, 01, f8, 01, 00
dwBufSize: 2448
```
The only way to read such a disc is to use audio mode starting from LBA 1 instead of 0. But with audio mode we lose the cuesheet, track splitting and c2 correction that **cd** mode offers.

Is there any way to add an option to skip lead-in reading in DIC?

**Comment by saramibreak** [comment]
Please use the supported drive of lead-in.
