### ISSUE TITLE
Sega CD games Cue/bin issue

### ISSUE THREAD

**Issue by douglie007** [saramibreak/DiscImageCreator#10]
I am using the guide from redump.org I have ripped one of my games but the Cue/Bin  when loaded in an emulator only sees it as a music CD.  did I rip it incorrectly? the command I used was ( DiscImageCreator.exe cd d Eye_of_the_Beholder_dump1.bin 8 /c2 /nl ) do I need different commands for unprotected games?

**Comment by saramibreak** [comment]
Does your dumped image match the database of redump.org?

**Comment by douglie007** [comment]
there is not one, that is what I wanted to do.  but I found out that it might be my drive.  I have an LG not a plexor.  when I used Imgburn the game was playable on the emulator... but it doesnt give me any data.  I did see that the Hex was missing some code from the games I ripped with Disc Image Creator, compared to the working ISOs
