### ISSUE TITLE
Which and how many drives does one need?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#101]
Hi everyone,

it's more a generic question. How many drives should one keep to be able to read discs in a good way?

Right now I have (IDE if not said otherwise):
ASUS BW-16D1HT (SATA)
Plextor PX-760
Plextor PX-755
Plextor PX-W5224
Plextor PX-W4012
TS-H352C (kreon-firmwared to SH-D162C)

I also have a NEC ND-3530A which isn't supported from DIC, but I've read it should be great with some special AudioCDs with errors.

Now I wonder, if I would "need" them all and still make good dumps. Or if it's feasible to e.g. only keep the PX-760 (which I got for the multisession discs problems I had/have) and the PX-W4012. I'm not really feeling safe enough to make the swap thing for GD discs for the H352C

**Comment by dutchcow** [comment]
I don't know the charateristics of every model you mention but I would recommend to keep a few as drives often have differences and you probably also want a spare for the future as Plextor drives get older and may fail (although one model is more prone for failure than another). The Asus BW-16D1HT is great for many discs but a bit slower than a good Plextor, and a good Plextor can read audio+ and cd-i formats. I even have a cheap and small 15 euro aliexpress cd/dvddrive that is not compatible for raw mode but has a strong laser that can read old cd-r's that no other drive can and performs very well for data recovery. If you have room for it I would say: keep them all

**Comment by Feathered-Serpent** [comment]
Luckily the drives can be stacked neatly. So I will just keep them in the cupboard until I need a specific one. Thanks for your opinion!
