### ISSUE TITLE
[Bug] Additional false positive with ARccOS

### ISSUE THREAD

**Issue by SilasLaspada** [saramibreak/DiscImageCreator#102]
**Version**
20211101

**Describe the bug**
ARccOS is detected on a DVD-Video which does contain it. I know this because the disc contains no bad sectors, which is the key protection feature of ARccOS.

**Screenshots**
![DiscImageCreator_aK28YD1NVI](https://user-images.githubusercontent.com/24215969/144774199-be4d6432-7d17-4f17-857a-7e2b18269d48.png)
(Picture taken during dump, I confirmed there were no bad sectors after)

**Disc title**
Shrek the Third

**Disc ringcode**
I can grab this later if necessary. 

**URL**
[eBay](https://www.ebay.com/): https://www.ebay.com/itm/353774032454?epid=5046094874

**Log file**
[SHREK_THE_THIRD_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/7657382/SHREK_THE_THIRD_logs.zip)

**Comment by saramibreak** [comment]
can ISO be dumped correctly?

**Comment by SilasLaspada** [comment]
Yes
