### ISSUE TITLE
DIC crashes after Reading DirectoryRecord 91/ 91

### ISSUE THREAD

**Issue by dutchcow** [saramibreak/DiscImageCreator#103]
**Version**
x86, AnsiBuild, 20211101T131257 / 20211101 0d0b140 (latest release)
x86, AnsiBuild, 20211118T113901 (latest test version)

**Describe the bug**
With this cd-rom, DIC always crashes after showing Reading DirectoryRecord 91/ 91. The process just terminates without showing any error in console.
Tried dumping with BW-16D1HT v3.02 and Plextor PX-W5224TA v1.04 drives, both have the same crash. Other cd-roms dump well, without this crash. The cd-rom is in very good condition, nearly scratchfree.

SPIELEHITS_volDesc.txt latest text is:

> 	========== IMAGE_EXPORT_DIRECTORY ==========
		      Characteristics: 38383838
		        TimeDateStamp: 38383838 (1999-11-21T18:21:44)
		         MajorVersion: 3898
		         MinorVersion: 3838
		                 Name: 38383838 (

This seems to end abruptly so it's probably related

**Screenshots**
![crashscreen](https://user-images.githubusercontent.com/96270929/146470642-682f27b5-2f36-48d3-9b98-894ca7a237e1.png)

**Disc title**
Microsoft Windows Spiele Hits - 25 Vollversionen auf cd-rom (media Verlagsgesellschaft mbH)

**Disc ringcode**
IFPI L572 
media DATA Service
4573
A258378-01
IFPI 9703 (? a bit too small to read)

**URL**
https://www.amazon.de/media-Verlagsgesellschaft-25-Spiele-Hits/dp/B000N2YXQ2

**Log file**
[SPIELEHITS DIC crashlog.zip](https://github.com/saramibreak/DiscImageCreator/files/7731263/SPIELEHITS.DIC.crashlog.zip)

**Comment by saramibreak** [comment]
Test and upload logs, plz.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7735582/DiscImageCreator_test.zip)

**Comment by Feathered-Serpent** [comment]
Reminds me of some of my discs from https://github.com/saramibreak/DiscImageCreator/issues/80

**Comment by dutchcow** [comment]
> 

It now seems to work.

Not sure if related but just in case: the .bin file is almost the same as aaru exported output to bin/cue except for the last part of the .bin file. There seems to be 588 bytes of padding with 0's and the remainder of data is the same. Removing the 588 zero's and then adding them at the end of bin file gives the same hashes. The cdrom has audio tracks
[SPIELEHITS_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/7737581/SPIELEHITS_logs.zip)
