### ISSUE TITLE
[Bug] DIC not descrambling data found in pregap of track 1

### ISSUE THREAD

**Issue by SilasLaspada** [saramibreak/DiscImageCreator#104]
**Version**
20211101

**Describe the bug**
DIC is not descrambling data found in the pregap of track 1. There are data sectors (as seen in the mainInfo log), but DIC doesn't descramble them, only moves the SCM to IMG. Line 759 of https://github.com/saramibreak/DiscImageCreator/blob/master/DiscImageCreator/execScsiCmdforCD.cpp seems to indicate that CD's with data in their first track pregap should be descrambled in this case.

**Disc title**
Any disc with data in the track 1 pregap should exhibit this, but my specific disc is "Star Wars: Shadows of the Empire"

**Disc ringcode**
All the string that is written the inner of the disc (IFPI etc.)

**URL**
Tell me the link to get the disc.
[Amazon](https://www.amazon.com/): 
[eBay](https://www.ebay.com/): https://www.ebay.com/itm/203591334664
[discogs](https://www.discogs.com/): 

**Log file**
[Star Wars - Shadows of the Empire Soundtrack Logs.zip](https://github.com/saramibreak/DiscImageCreator/files/7797390/Star.Wars.-.Shadows.of.the.Empire.Soundtrack.Logs.zip)

**Comment by mnadareski** [comment]
I did a little digging into this as I was trying to understand the issue. I found the following:
- In https://github.com/saramibreak/DiscImageCreator/blob/7686bc1718ac6daa84362f2d6599f1ac08bd69f8/DiscImageCreator/set.cpp#L271 (Line 271), discs that aren't CD-i are processed.
- In that block, it does check for pregap data, as would be expected
- However, the `if` block following seems to make an assumption: if `trkType == TRACK_TYPE::dataExist` then `trkType = TRACK_TYPE::pregapDataIn1stTrack` and for everything else `trkType = TRACK_TYPE::pregapAudioIn1stTrack`
- The above assumption would work for the majority of discs. However, the disc above has Track 1 marked as "Audio", so it ends up setting `trkType = TRACK_TYPE::pregapAudioIn1stTrack` erroneously

All of this combined leads to the logic in https://github.com/saramibreak/DiscImageCreator/blob/6451ff92b402baf4cd674d4b891246c488567570/DiscImageCreator/execScsiCmdforCD.cpp#L759 to skip over descrambling the pregap entirely.

**Comment by saramibreak** [comment]
@SilasLaspada 
Is this not CD-i Ready? What is the platform of disc?

**Comment by SilasLaspada** [comment]
This disc is not CD-i Ready. This disc is an audio CD that has an ISO9660 partition in the pregap of track 1.

**Comment by saramibreak** [comment]
Test, plz.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7798603/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
No change in the dump, the image hash is the same as when dumping with the "normal" version of DIC.

**Comment by saramibreak** [comment]
Is there logs?

**Comment by SilasLaspada** [comment]
Here:
[Test build logs.zip](https://github.com/saramibreak/DiscImageCreator/files/7798647/Test.build.logs.zip)

**Comment by saramibreak** [comment]
Fixed
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7798678/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
Interesting results this time, it seems to descramble the sectors, but it says "[ERROR] Number of sector(s) where user data doesn't match the expected ECC/EDC: 57396". Logs:
[Test build logs 2.zip](https://github.com/saramibreak/DiscImageCreator/files/7798701/Test.build.logs.2.zip)

**Comment by saramibreak** [comment]
Uploaded
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7799762/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
The image dumped again has the same hashes, but this time I see that DIC attempted and failed to descramble the image. From the command window: 
```
Copying .scm to .img
LBA[-1947749405, 0x8be7b3e3]: Failed to read [F:DescrambleMainChannelAll][L:1794]
```
The command window also has the text:
```
LBA[066562, 0x10402]: [F:ReadVolumeDescriptor][L:538]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-64-00 = ILLEGAL_REQUEST - ILLEGAL MODE FOR THIS TRACK
lpCmd: a8, 00, 00, 01, 04, 02, 00, 00, 00, 01, 00, 00
dwBufSize: 2048
Reading Partition Map 2/2
```
It didn't have this text in previous dumps. Also, I recently discovered that this disc has both an ISO9660 and an HFS partition. Logs: [Test build logs 3.zip](https://github.com/saramibreak/DiscImageCreator/files/7799885/Test.build.logs.3.zip)

**Comment by saramibreak** [comment]
Some fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7799915/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
Newest build makes identical dump, this time seemingly with no attempt to descramble. This time, it says
```
Reading DirectoryRecord    3/   3
```

Instead of the partition map message. Logs: 
[Test build logs 4.zip](https://github.com/saramibreak/DiscImageCreator/files/7800011/Test.build.logs.4.zip)

**Comment by saramibreak** [comment]
Fixed again (incl partition map message)
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7800217/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
This dump seems better! The partition map message doesn't show up, but the dump does actual descramble, with no errors present! Logs:
[Test build logs 5.zip](https://github.com/saramibreak/DiscImageCreator/files/7800301/Test.build.logs.5.zip)

**Comment by saramibreak** [comment]
> The partition map message doesn't show up

Sorry and thanks all testing.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7800394/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
Alright, both the "Reading directories" and partition map messages show up, and the data seems to be descrambled! One last thing I'm wondering, is everything write offset wise accounted for since the data on the disc isn't immediately visible? Logs:
[Test build logs 6.zip](https://github.com/saramibreak/DiscImageCreator/files/7800428/Test.build.logs.6.zip)

**Comment by saramibreak** [comment]
> is everything write offset wise accounted for since the data on the disc isn't immediately visible?

What do you mean?

**Comment by SilasLaspada** [comment]
Well since a normal audio CD can't have its write offset known, but a CD with data on it can. I just wanted to be sure DIC takes into account the write offset using the data in the pregap.

**Comment by saramibreak** [comment]
> DIC takes into account the write offset using the data in the pregap.

Yes. Data sector has an address called by MSF. Your disc has it.
```
04F0 : C3 5A D1 FB 1C 43 49 F1  F6 C4 CD 43 B9 5F A5 24   .Z...CI....C._.$
0500 : 00 FF FF FF FF FF FF FF  FF FF FF 00 01 82 00 61   ...............a
0510 : 45 7A 02 1E 80 0B 1E 74  A8 02 FE 81 80 60 60 28   Ez.....t.....``(
```
01 82 00 is descrambled to 00 02 00. This indicates the 1st sector of the data. Combined offset is 0500h and it's 1280 bytes.
```
	 Combined Offset(Byte)   1280, (Samples)   320
	-   Drive Offset(Byte)    392, (Samples)    98
	----------------------------------------------
	       CD Offset(Byte)    888, (Samples)   222
```
As the result, your disc offset is 222.
