### ISSUE TITLE
Dumping BD_VIDEO fails with space error despite space being available

### ISSUE THREAD

**Issue by InternalLoss** [saramibreak/DiscImageCreator#105]
**Version**
Please use [the latest version](https://github.com/saramibreak/DiscImageCreator/releases) when report the bug.

**Describe the bug**
When trying to dump a BD-VIDEO disc, the application incorrectly reports not enough space available - the disc is 22467051520 bytes

**Screenshots**
```
AppVersion
        x86, AnsiBuild, 20211101T131257
CurrentDirectory
        C:\Users\Inter\Documents\Dumping Tools\MPF
WorkingPath
         Argument: ISO\Splatoon2-BD\Spla2n.iso
         FullPath: C:\Users\Inter\Documents\Dumping Tools\MPF\ISO\Splatoon2-BD\Spla2n.iso
            Drive: C:
        Directory: \Users\Inter\Documents\Dumping Tools\MPF\ISO\Splatoon2-BD\
         Filename: Spla2n
        Extension: .iso
StartTime: 2022-01-06T15:01:55+0000
CurrentDriveSize
        Total: 479321825280 bytes
         Used: 380581830656 bytes
        --------------------------
        Space:  98739994624 bytes
         => There is not enough the disk space for dumping
EndTime: 2022-01-06T15:01:55+0000
```

**Disc title**
Splatoon 2: Live in Makuhari 

**URL**
Tell me the link to get the disc.
[MusicBrainz]: https://musicbrainz.org/release/407494b2-af69-4f02-8ae2-0f68edb7b842

No logs created, except the command ran - `C:\Users\Inter\Documents\Dumping Tools\MPF\Programs\Creator\DiscImageCreator.exe bd E ISO\Splatoon2-BD\Spla2n.iso 16 `

This is likely due to BD requiring 130GB of space, not the actual space of the disc (this is a BD-25) as mentioned in https://github.com/saramibreak/DiscImageCreator/issues/83#issuecomment-893132802

**Comment by saramibreak** [comment]
> This is likely due to BD requiring 130GB of space

bd command supposes BDXL QL, it's 128GB.

**Comment by InternalLoss** [comment]
> > This is likely due to BD requiring 130GB of space
> 
> bd command supposes BDXL QL, it's 128GB.

Is it not possible to check if the disc is BD-25/etc? I don't have the space on my SSD to dump a 128GB disc right now, but I know I have more than enough for this (>90GB)

**Comment by malvarenga123** [comment]
@saramibreak shouldn't DIC check for the exact disc size first and then calculate the required free space? This would solve the free space issue once and for all.

**Comment by saramibreak** [comment]
> check for the exact disc size first and then calculate the required free space?

Plz tell me the remained space you can accept when blu-ray disc is dumped. If the free space is 25GB + 100MB, do you want to dump the BD-25 disc? Then, how about +500MB? +1GB? +2GB? I don't want the few remaining spaces on the disk.

**Comment by malvarenga123** [comment]
How much does DIC need **at most** for a particular disc? 110% of the actual size? 120% of the actual size? Whatever that is, that should be the required size and DIC should dump the disc if that space is available.
Using fixed sizes are not optimal at all. You can have a 11GB game on a BD-25. Why would you need 25GB (or 130GB) to dump it? The same logic applies to all other types of disks.
IMO, it's not DIC's job to manage how a user uses his disk space. If they want to have only 5KB of free space after a dump, what's the problem?

**Comment by saramibreak** [comment]
You consider only bin/iso size, but dic generates several log files. log files size is variable and not a limit theoretically.

**Comment by malvarenga123** [comment]
Do you think log files could be over 20% of the image size?

**Comment by saramibreak** [comment]
It's possible. 

>  it's not DIC's job to manage how a user uses his disk space. If they want to have only 5KB of free space after a dump, what's the problem?

Yes. but some users execute it by the disk including OS. If the remained space of the disk is a few sizes, it's a problem.

**Comment by malvarenga123** [comment]
>It's possible.

Sure it's possible, but in edge cases not even 130 GB would be enough.

>Yes. but some users execute it by the disk including OS. If the remained space of the disk is a few sizes, it's a problem.

Sure, but not DIC's problem.

**Comment by saramibreak** [comment]
```
	CONST INT nAllLogsFileSize = 1000000000;
	if ((IsCDBasedDisc(pExecType, pDisc) && ui64Avail.QuadPart > (ULONGLONG)(pDisc->SCSI.nAllLength * 3 + nAllLogsFileSize)) ||
		(IsDVDBasedDisc(pDisc) && ui64Avail.QuadPart > (ULONGLONG)(pDisc->SCSI.nAllLength + nAllLogsFileSize)) ||
		(IsBDBasedDisc(pDisc) && ui64Avail.QuadPart > (ULONGLONG)(pDisc->SCSI.nAllLength + nAllLogsFileSize))
		) {
		OutputString("\t => There is enough disk space for dumping\n");
		bRet = TRUE;
	}
```
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7923598/DiscImageCreator_test.zip)

**Comment by malvarenga123** [comment]
`
AppVersion
        32 bit, AnsiBuild, 20220124T163628
valid extension was omitted. -> set .bin
CurrentDirectory
        H:\DiscImageCreator\Release_ANSI
WorkingPath
         Argument: d:\bluray.bin
         FullPath: d:\bluray.bin
            Drive: d:
        Directory: \
         Filename: bluray
        Extension: .bin
StartTime: 2022-01-24T11:57:38-0300
DiskSize of [d:\]
        Total: 666798911488 bytes
         Used: 603180662784 bytes
        --------------------------
        Space:  63618248704 bytes
         => There is enough disk space for dumping
Creating iso(LBA) 12134528/12134528
Hashing: bluray.iso
EndTime: 2022-01-24T12:21:07-0300
`
Seems to be working.
