### ISSUE TITLE
DIC crashes with HP Data Protector Express Basic v5 sept 2010 C1529-10156 cd-rom

### ISSUE THREAD

**Issue by dutchcow** [saramibreak/DiscImageCreator#107]
**Version**
Latest (01 Nov 2021) and also the testversion that was posted in another closed issue: https://github.com/saramibreak/DiscImageCreator/issues/103

**Describe the bug**
When trying to make a disc image DIC completely closes. Tested with 2 different drives. Opening DPExps500_volDesc.txt it seems it ended abruptly:
```
========== IMAGE_EXPORT_DIRECTORY ==========
		      Characteristics: 00000000
		        TimeDateStamp: 44e39635 (2006-08-16T22:03:33)
		         MajorVersion: 0000
		         MinorVersion: 0000
		                 Name: 00413e44 (
```
It seems a bit similar to https://github.com/saramibreak/DiscImageCreator/issues/103

**Screenshots**
![1](https://user-images.githubusercontent.com/96270929/150697994-9fb345ac-0f46-48f0-a3a8-7ebdd728d210.png)

**Disc title**
HP Data Protector Express Basic v5.0

**Disc ringcode**
PRSSC C1529-10156

**URL**
-

**Log file**
[output.zip](https://github.com/saramibreak/DiscImageCreator/files/7921434/output.zip)

**Comment by saramibreak** [comment]
- added: check the range of array
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7923855/DiscImageCreator_test.zip)

**Comment by dutchcow** [comment]
Thanks, seems fixed
