### ISSUE TITLE
[Request] Hash image while dumping

### ISSUE THREAD

**Issue by malvarenga123** [saramibreak/DiscImageCreator#108]
**Is your feature request related to a problem? Please describe.**
For images where there is no descrambling (eg. DVD, BD), hashing may take a long time.

**Describe the solution you'd like**
Calculate the hash while dumping the disc.
http://forum.redump.org/post/94214/#p94214

**Describe alternatives you've considered**
The alternative is already being done by DIC, which is calculating the hash after the dump is complete.

**Additional context**
I know Imgburn already does this. As soon as the image is complete, its MD5 is shown and a .md5 is created.
This can't be done for CDs dumped in scrambled mode, but it can be done for most DVDs and BDs.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7939733/DiscImageCreator_test.zip)

**Comment by malvarenga123** [comment]
Seems to be working, thanks a lot Sarami!
Just need to be sure it's not enabled for CDs dumped in scrambled mode.

```
AppVersion
        32 bit, AnsiBuild, 20220126T163558
valid extension was omitted. -> set .bin
CurrentDirectory
        H:\DiscImageCreator\Release_ANSI
WorkingPath
         Argument: hashtest.bin
         FullPath: H:\DiscImageCreator\Release_ANSI\hashtest.bin
            Drive: H:
        Directory: \DiscImageCreator\Release_ANSI\
         Filename: hashtest
        Extension: .bin
StartTime: 2022-01-26T12:51:33-0300
[F:DVDGetRegion][L:406] GetLastError: 1, Incorrect function.

DiskSize of [H:\DiscImageCreator\Release_ANSI]
        Total: 666797862912 bytes
         Used: 366791307264 bytes
        --------------------------
        Space: 300006555648 bytes
         => There is enough disk space for dumping
Reading DirectoryRecord    5/   5
Creating iso(LBA)  2223961/ 2223961
EndTime: 2022-01-26T13:04:12-0300
```
