### ISSUE TITLE
Advantage of raw DVD dumping?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#109]
Hi everyone,

what is the advantage to use /raw on a DVD? Both on a data or a movie DVD? The extraction is really slow (feels like it will take 2 hours for a single layer DVD) so it would be nice to know, if it would be useful at all. Is it used mainly for data DVD copy protections?

Same goes for the /c which basically only just has three states to write down for any LBA:
- No protected sector
- CSS or CPPM doesn't exist in this sector, no copying is permitted
- This sector is scrambled by CSS, no copying is permitted

Using both parameters makes it twice as slow because at first it reads the /c information and then starts from the beginning and makes a /raw dump.

**Comment by Feathered-Serpent** [comment]
Just as reference: the same disc without /raw or /c took 50 minutes to dump on PX-760A.

I also noticed, /raw does not include using DVDauth, as when it came towards the CSS sectors, it rained errors. So I guess /raw isn't thought for movie DVDs.

Interestingly I have one game DVD (Simon the Sorcerer 5 (German)) where DIC also uses DVDauth. Upon using /c I found out that LBA 0 - 1208415 show "No protected sector" and LBA 1208416 - 1208671 show "CSS or CPPM doesn't exist in this sector, no copying is permitted"

**Comment by saramibreak** [comment]
ref: http://www.dvdforum.org/DVD_Cutting_Master/CMF-DVD-7.htm
```
VOID OutputDVDCopyrightManagementInformation(
	PDVD_COPYRIGHT_MANAGEMENT_DESCRIPTOR dvdCopyright,
	INT nLBA
) {
	if ((dvdCopyright->CPR_MAI & 0x80) == 0x80) {
		if ((dvdCopyright->CPR_MAI & 0x40) == 0x40) {
			switch (dvdCopyright->CPR_MAI & 0x0f) {
			case 0:
				OutputDiscWithLBALog("This sector is scrambled by CSS", nLBA);
				break;
			case 0x01:
				OutputDiscWithLBALog("This sector is encrypted by CPPM", nLBA);
				break;
			default:
				OutputDiscWithLBALog("reserved", nLBA);
			}
		}
		else {
			OutputDiscWithLBALog("CSS or CPPM doesn't exist in this sector", nLBA);
		}

		switch (dvdCopyright->CPR_MAI & 0x30) {
		case 0:
			OutputDiscLog(", copying is permitted without restriction\n");
			break;
		case 0x10:
			OutputDiscLog(", reserved\n");
			break;
		case 0x20:
			OutputDiscLog(", one generation of copies may be made\n");
			break;
		case 0x30:
			OutputDiscLog(", no copying is permitted\n");
			break;
		default:
			OutputDiscLog("\n");
		}
	}
	else {
		OutputDiscWithLBALog("No protected sector\n", nLBA);
	}
}
```
