### ISSUE TITLE
Using LibreDrive for dumping discs

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#118]
At https://forum.makemkv.com/forum/viewtopic.php?t=18856 one can read about the possibilities of LibreDrive, as in accessing any disc on a very basic level.

Couldn't DiscImageCreator, when using the LibDriveIo library, dump nearly everything without using special tricks? Or wouldn't it going to work with game CDs from video game consoles?

**Comment by saramibreak** [comment]
Did you see the src code? https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224

At least, it's not useful for my app, I think.

> dump nearly everything without using special tricks?

Special trick, I don't know what it is.

**Comment by Feathered-Serpent** [comment]
I meant like for GD discs for example. From how it read in the MakeMKV forum, it sounded like with LibreDrive one could also access such things with "unspecial" drives. Was just a thought :)
