### ISSUE TITLE
Dump CD-ROM Drive not compatible ?

### ISSUE THREAD

**Issue by GDX-X** [saramibreak/DiscImageCreator#119]
**Describe the bug**
I can dump DVDs, DVD9s but not PS1 CD-ROMs. I guess my player is not compatible for CD-ROM.
TSSTcorp CDDVDW SH-224DB

DiscImageCreator.exe cd d MyGameTitle.bin 8 /c2 /nl

**Log file**
[LOGDUMP.zip](https://github.com/saramibreak/DiscImageCreator/files/8327549/LOGDUMP.zip)

**Comment by saramibreak** [comment]
> I guess my player is not compatible for CD-ROM.

Yes, see README.md.
