### ISSUE TITLE
SecuROM detected and dumping stops

### ISSUE THREAD

**Issue by mnadareski** [saramibreak/DiscImageCreator#122]
**Version**
Using version 20220301 for testing

**Describe the bug**
While dumping http://redump.org/disc/20468/, DIC is correctly detecting SecuROM 4.76.00 during the scanning executables phase. Immediately after it detects SecuROM, the dump exits without warning. See the zip below for the complete set of files created at that point

**Commandline**
`DiscImageCreator.exe cd F "NWN_INSTALL1\NWN_INSTALL1.bin" 24 /c2 10000 /ns /sf `

**Disc title**
[Neverwinter Nights (USA) (Disc 1) (Installation Disc 1)](http://redump.org/disc/20468/)

**Log file**
[NWN_INSTALL1.zip](https://github.com/saramibreak/DiscImageCreator/files/8382281/NWN_INSTALL1.zip)

**Comment by saramibreak** [comment]
It seems 4.7x and 4.8x have the same SecuROM header.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8385601/DiscImageCreator_test.zip)

**Comment by Feathered-Serpent** [comment]
I was able to dump my NWN disc with the test build.

**Comment by saramibreak** [comment]
86cc79784305a9de4382a735b982325b92d3a252
