### ISSUE TITLE
SuperDisk media types

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#126]
**Version**
32 bit, AnsiBuild, 20220331T120308

**Describe the bug**
Now a difficult one. Upon dumping a normal 3.5" floppy disc, the _disc file shows this:
```
========== DISK_GEOMETRY ==========
SupportedMediaType
	        MediaType: 17 (3.5", 1.2Mb, 512 bytes/sector)
	        Cylinders: 80
	TracksPerCylinder: 2
	  SectorsPerTrack: 15
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 1228800 (Bytes)

	        MediaType: 18 (3.5", 1.23Mb, 1024 bytes/sector)
	        Cylinders: 77
	TracksPerCylinder: 2
	  SectorsPerTrack: 8
	   BytesPerSector: 1024 (Bytes)
	--------------------------
	         DiskSize: 1261568 (Bytes)

	        MediaType: 2 (3.5", 1.44MB, 512 bytes/sector)
	        Cylinders: 80
	TracksPerCylinder: 2
	  SectorsPerTrack: 18
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 1474560 (Bytes)

CurrentMediaType
	        MediaType: 2 (3.5", 1.44MB, 512 bytes/sector)
	        Cylinders: 80
	TracksPerCylinder: 2
	  SectorsPerTrack: 18
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 1474560 (Bytes)
```

Upon using a Imation LS120 SuperDisk drive with a 120 MB SuperDisk floppy, the _disc file shows the following:
```
CurrentMediaType
	        MediaType: 13 (3.5", 120M Floppy)
	        Cylinders: 963
	TracksPerCylinder: 8
	  SectorsPerTrack: 32
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 126222336 (Bytes)

CurrentMediaType
	        MediaType: 13 (3.5", 120M Floppy)
	        Cylinders: 963
	TracksPerCylinder: 8
	  SectorsPerTrack: 32
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 126222336 (Bytes)
```

So it lists CurrentMediaType twice with the same information and it's missing the "========== DISK_GEOMETRY ==========" at the beginning of the file plus the SupportedMediaType information.

**Comment by saramibreak** [comment]
Uploaded.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8458463/DiscImageCreator_test.zip)

**Comment by Feathered-Serpent** [comment]
I have to say, nothing changed.

Full logs:
[NO NAME.zip](https://github.com/saramibreak/DiscImageCreator/files/8458850/NO.NAME.zip)

**Comment by saramibreak** [comment]
> I have to say, nothing changed.

That is quite obvious. You're using the same version that you reported it 23 hours ago.

> Uploaded.
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8458463/DiscImageCreator_test.zip)

Use this, plz.

**Comment by Feathered-Serpent** [comment]
argh... my fault, sorry. I used a batch file which still was pointing to the old download.

Now everything looks better:
```
========== DISK_GEOMETRY ==========
SupportedMediaType
	        MediaType: 13 (3.5", 120M Floppy)
	        Cylinders: 963
	TracksPerCylinder: 8
	  SectorsPerTrack: 32
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 126222336 (Bytes)

CurrentMediaType
	        MediaType: 13 (3.5", 120M Floppy)
	        Cylinders: 963
	TracksPerCylinder: 8
	  SectorsPerTrack: 32
	   BytesPerSector: 512 (Bytes)
	--------------------------
	         DiskSize: 126222336 (Bytes)
```

I'm not sure if I should close cases when you made a fix or if you do that. This one can be closed for me, and so could the one about exFAT

**Comment by saramibreak** [comment]
It would help me if you could close these issue.
