### ISSUE TITLE
Dot in file name causes termination

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#131]
**Version**
32 bit, AnsiBuild, 20220501T222046

**Describe the bug**
(at minimum) a dot in the path or the filename causes the program to not work correctly. I'm using a batch file to automatically create a directory with the name of the disc itself. Now I got the first disc with a dot in the discs name and this causes DIC to stop. If I replace the . with a _ everything works fine.
I also tried dumping into a directory called Test.1 with an ISO filename of Test.iso, but it still wouldn't work, so the path seems also to be of importance there.

**Disc title**
HI5-0E-UT1.3_DES

**Log file**
```
AppVersion
        32 bit, AnsiBuild, 20220501T222046
/sf val was omitted. set [60]
CurrentDirectory
        G:\DVD\HI5-0E-UT1.3_DES
WorkingPath
         Argument: HI5-0E-UT1.3_DES.iso
         FullPath: G:\DVD\HI5-0E-UT1.3_DES\HI5-0E-UT1.3_DES.iso
            Drive: G:
        Directory: \DVD\HI5-0E-UT1.3_DES\
         Filename: HI5-0E-UT1.3_DES
        Extension: .iso
StartTime: 2022-05-23T09:20:15+0200
Set the drive speed: 0KB/sec
DiskSize of [G:\DVD\HI5-0E-UT1.3_DES]
        Total:  2000381014016 bytes
         Used:  1444091510784 bytes
        ---------------------------
        Space:   556289503232 bytes
         => There is enough disk space for dumping
[F:ReadDiscStructure][L:1227] GetLastError: 3, The system cannot find the path specified.

EndTime: 2022-05-23T09:20:16+0200
```

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8756888/DiscImageCreator_test.zip)
- changed: PFI.bin to (fname)_PFI.bin and DMI.bin to (fname)_DMI.bin
