### ISSUE TITLE
Better packaging of the Linux version.

### ISSUE THREAD

**Issue by maxz** [saramibreak/DiscImageCreator#134]
**Is your feature request related to a problem? Please describe.**
There are two minor changes to the packaging process which would make the experience of updating to a new DIC version more pleasant: Including a version number in the archive name like the Windows version already has it and marking executables in the tar archive as executable.

Also two more intrusive (non backward compatible) changes: Changing the structure of the archive so that it does extract everything into a `DiscImageCreator` directory instead of the current directory, as is proper archive etiquette and changing the names of the executables.

I already checked the files in the repository so that I could submit a pull request, but your deployment code does not seem to be included.

**Describe the solution you'd like**
After building the new version of the binaries and before tarring them, you should set their executable bit for all executables, e.g. with `chmod a+x *.out`. This will be preserved by the tar archive.

Add the current version number to the `.tar.gz` archive's name as you already do with the Windows version's `.zip`, so that the filename would look e.g. like `DiscImageCreator_20220606_linux.tar.gz`. This would make storing old versions easier since I would not have to modify the file names myself anymore.

Ensure that the files are not untared into the current directory but into a fitting structure. This is proper archive etiquette.
So say your build directory is `DiscImageCreator` and you are currently in it, you could use `tar -czf ../DiscImageCreator.tar.gz ../DiscImageCreator` to properly pack it. When someone then unpacks the archive, it will create (or use) the `DiscImageCreator` directory and place all the files in there.

An additional bonus to make the binaries a bit more idiomatic would be to drop the `.out` extension, so to just call them `DiscImageCreator_linux`, `EccEdc_linux`and `DVDAuth_linux` or even better: `DiscImageCreator`, `EccEdc`and `DVDAuth`.

It would be more idiomatic yet to have lower case names with components separated by hyphens, e.g. `disc-image-creator`, `ecc-edc`and `dvd-auth`, but that might go too far in this case and having a name like `DiscImageCreator` would already be an improvement over the current situation.

**Describe alternatives you've considered**
Alternatively I could obviously just keep doing these things myself.

**Comment by saramibreak** [comment]
> with chmod a+x *.out. This will be preserved by the tar archive.

> When someone then unpacks the archive, it will create (or use) the DiscImageCreator directory and place all the files in there.

I tried it on #139.

**Comment by maxz** [comment]
Great packaging changes so far. Thanks.
The release [20220707](https://github.com/saramibreak/DiscImageCreator/files/9064089/DiscImageCreator_20220707.tar.gz) covers everything but the renamed executables.

Are you intending to still change those or would you rather keep them as they currently are?
If you intend to change them but are stuck somewhere in the process, do you need any help?

**Comment by maxz** [comment]
I guess you want to keep the current names since you did not comment any further. Rather than keeping the issue open indefinitely, I'm closing it now.
