### ISSUE TITLE
No Securom Detection, wrong error count in Turok 2

### ISSUE THREAD

**Issue by HeroponRikiBestest** [saramibreak/DiscImageCreator#139]
**Version**
I tested twice on 20220501, twice on 20220301, and twice on the latest test version.

**Describe the bug**
When I dump http://redump.org/disc/30120/, all the hashes correctly match (except on the first dump on the test version). However, even with /sf /ns, DiC doesn't detect and handle Securom. Furthermore, the resulting error count is wrong. There should be one error; the first time i dumped on the test version, there were 2 errors. The second time I dumped on the test version (when i lowered the speed to 16x) and on my tests on all the other versions (done at fullspeed) resulted in 0 errors.

I am on Linux Mint 20.2. I am using an LG UH12NS240 flashed with Ribshark's JB8 firmware modification.

**Screenshots**
In the resulting EccEdc.txt, this seems to be where the error is supposed to occur:
`LBA[101883, 0x18dfb], MSF[22:40:33], mode 2 form 1, SubHeader[1](FileNum[00]), [2](ChannelNum[00]), [3](Submode[00])[NoEOF, Form 1], [4](CodingInfo[00])[]`

**Disc title**
Turok 2 - Seeds of Evil (USA)

**Disc ringcode**

DADC IFPI L555 A0100270050-0101  45  A5

**URL**
Tell me the link to get the disc.
[Amazon](https://www.amazon.com/): 
[eBay](https://www.ebay.com/): https://www.ebay.com/itm/175151581764
[discogs](https://www.discogs.com/): 

**Log file**
20220501:
[logs.zip](https://github.com/saramibreak/DiscImageCreator/files/8934825/logs.zip)
20220301:
[logs.zip](https://github.com/saramibreak/DiscImageCreator/files/8934833/logs.zip)
Latest test version:
[logs.zip](https://github.com/saramibreak/DiscImageCreator/files/8934850/logs.zip)

**Comment by saramibreak** [comment]
Sorry, linux version has not supported to extract .cab file yet.

**Comment by HeroponRikiBestest** [comment]
Wouldn't it still report the error, though?

**Comment by HeroponRikiBestest** [comment]
I went and dumped on Windows. In the resulting logs, `Detected intentional subchannel in LBA 40125 => SecuROM 1st version (a.k.a. OLD)` was displayed before any filesystem checks, which seems to indicate that the failure to detect SecuROM and the resulting wrong error count has nothing to do with extracting cab files @saramibreak 
Logs: [Turok2logs.zip](https://github.com/saramibreak/DiscImageCreator/files/8937456/Turok2logs.zip)

**Comment by saramibreak** [comment]
> independent of any filesystem checks, which seems to indicate that the failure to detect SecuROM on linux, and the resulting wrong error count has nothing to do with extracting cab files

Some disc need to extract cab, but probably this is a problem of linux 64 bit app.

[DiscImageCreator_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/8939742/DiscImageCreator_test.tar.gz)
- changed: DWORD of defineForLinux.h to UINT (NOT TEST)

**Comment by saramibreak** [comment]
@HeroponRikiBestest 
Would you test it, if possible?

**Comment by HeroponRikiBestest** [comment]
I can, but I can't test this until next Wednesday. I will let you know once I do.

**Comment by HeroponRikiBestest** [comment]
@saramibreak sorry it took me so long to get back to you. It seems it correctly identifies the Securom and captures the subchannel data field correctly, but still incorrectly says theres 0 errors when there should be 1.
[logs.zip](https://github.com/saramibreak/DiscImageCreator/files/9064226/logs.zip)
