### ISSUE TITLE
Dumping GC game with GDR8164B doesn't work

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#145]
**Version**
32 bit, AnsiBuild, 20220707T220452

**Describe the bug**
I thought I buy myself a GDR8164B for dumping my GC and Wii games.

Though my (so far) only GC game doesn't even have any voldesc file like I see in https://github.com/saramibreak/DiscImageCreator/issues/144 there should be. As soon as it starts dumping, it goes
```
LBA[000000, 0000000]: [F:ReadDiscStructure][L:1522]
	Opcode: 0xad
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB

LBA[000000, 0000000]: [F:ReadDVDRaw][L:864]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[000080, 0x00050]: [F:ReadDVDRaw][L:864]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[000160, 0x000a0]: [F:ReadDVDRaw][L:864]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[000240, 0x000f0]: [F:ReadDVDRaw][L:864]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[000320, 0x00140]: [F:ReadDVDRaw][L:864]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[000400, 0x00190]: [F:ReadDVDRaw][L:864]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR
```
and it goes so forever, in steps of 80 sectors. Is it something strange with the disc? Or is the drive strange? Is it because of the firmware (0L06)? I didn't find any firmware to download.
In the disc file, it says "StartingDataSector:  196608 (0x30000)" so is it normal that it has read errors I would assume. But why doesn't it start at 196608 then?

**Disc title**
Winnie the Pooh's Rumbly Tumbly Adventure

**Disc ringcode**
IFPI LQ11 105B0405 DOL-GWHP-0-00 JPN S0

**Log file**
[Winni.zip](https://github.com/saramibreak/DiscImageCreator/files/9477359/Winni.zip)

**Comment by saramibreak** [comment]
Uploaded test version in #144

**Comment by Feathered-Serpent** [comment]
No read errors now at the beginning, currently dumping the disc to the end.

Though the _mainInfo file and the _volDesc file are completely empty. I guess because of the
```
LBA[000000, 0000000]: [F:ReadDiscStructure][L:1529]
        Opcode: 0xad
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
Failed to read BCA. cdb: ad, 00, 00, 00, 00, 00, 00, 03, 00, c0, 00, 00
```
At the console output. Will supply logs once the dump is done.

**Comment by Feathered-Serpent** [comment]
```
AppVersion
        32 bit, AnsiBuild, 20220902T191340
CurrentDirectory
        C:\Users\Ezatoka\Desktop\Games\GWHP41
WorkingPath
         Argument: GWHP41.bin
         FullPath: C:\Users\Ezatoka\Desktop\Games\GWHP41\GWHP41.bin
            Drive: C:
        Directory: \Users\Ezatoka\Desktop\Games\GWHP41\
         Filename: GWHP41
        Extension: .bin
StartTime: 2022-09-02T21:37:03+0200
DiskSize of [C:\Users\Ezatoka\Desktop\Games\GWHP41]
        Total:  1023531806720 bytes
         Used:   566405644288 bytes
        ---------------------------
        Space:   457126162432 bytes
         => There is enough disk space for dumping
LBA[000000, 0000000]: [F:ReadDiscStructure][L:1529]
        Opcode: 0xad
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
Failed to read BCA. cdb: ad, 00, 00, 00, 00, 00, 00, 03, 00, c0, 00, 00
Rawdump command [0]:0xe7 [1]:0x48 [2]:0x49
Creating raw(LBA)  712880/ 712880
```
Finished successfully. If the remaining error there is normal, then I guess everything is alright, right?
[GWHP41.zip](https://github.com/saramibreak/DiscImageCreator/files/9481326/GWHP41.zip)

I also noticed, that only after finishing the image, the volDesc file was written.

**Comment by saramibreak** [comment]
committed https://github.com/saramibreak/DiscImageCreator/commit/0285795bb3811c74ca981debbd5a840921ccb206
