### ISSUE TITLE
dat file for GC and Wii games missing rom name, size and crc; also hashes are wrong maybe?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#148]
**Version**
32 bit, AnsiBuild, 20220902T191340

**Describe the bug**
the dat file created after finishing a dump doesn't contain the rom name, the size and the crc of the created ISO. it does have md5 and sha1 though:
```
  <game name="RSPP01">
    <category>Games</category>
    <description>RSPP01</description>
    <rom name="" size="0" crc="00000000" md5="d41d8cd98f00b204e9800998ecf8427e" sha1="da39a3ee5e6b4b0d3255bfef95601890afd80709" />
  </game>
```

**Disc title**
Wii Sports

**Log file**
The log file was too big for GitHub. I uploaded it onto my webspace: https://silentstrider.net/RSPP01_Logs.zip

another problem: these values do not reflect any file? where are they taken from?
```
 Datei: RSPP01_dec (Track 0).iso
CRC-32: 163dcfab
   MD4: 01009e1e3051250d95c0a0c0e1f16c40
   MD5: bbcb065b909640847e45f7b0d2dc873c
 SHA-1: 20a3f6338272fdcfdf325e68832354d1ad90f0a9

 Datei: RSPP01_dec (Track 1).iso
CRC-32: 8d04a20c
   MD4: de32748e4c462136eb385e39c632d7b1
   MD5: 91782646dd3aa465ced6104eb6ab897f
 SHA-1: 7d93abb0d086ad04b5fa1da1a277833292fd5fca

 Datei: RSPP01.raw
CRC-32: c5c7bbf0
   MD4: dd1fd79f78107a910f94076e7a90b9ec
   MD5: 626f107560c69cb933765fb5fa5755a0
 SHA-1: 1d92acf4bd94a38c92dff36a2287e96d372e927d

 Datei: RSPP01.iso
CRC-32: 7210d7b5
   MD4: 2cac6046e412de5f93cb2b2a4c5ec2af
   MD5: 197fa7bd7a4abc0c761057402ce194f1
 SHA-1: 3ef6ffe45ea5c05b8c02171282819a3c4fdde4b5
```

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/9554065/DiscImageCreator_test.zip)

**Comment by Feathered-Serpent** [comment]
just wanna leave the note, that it's working fine with that version. Hash of the iso is created and correct.

**Comment by Feathered-Serpent** [comment]
another addition: that size is totally wrong:
```
		<rom name="SX4P01.raw" size="18446744073697270784" crc="944c7f29" md5="26bdf071a3512b7bc03fe72eb53b4d67" sha1="f937aa337a57b3182de6169126b8a6576d4e987c"/>
```
the hash is alright. Also what are those _dec (Track X) files? They're not the size of the actual tracks in the descrambled ISO file. Like on this 8GB game the track 1 is not even 2GB in size.

**Comment by saramibreak** [comment]
Is it other disc? Are there logs?

**Comment by Feathered-Serpent** [comment]
Here you go. (too big for GitHub)
https://silentstrider.net/SX4P01_Logs.zip

**Comment by saramibreak** [comment]
Uploaded, but not test.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/9603365/DiscImageCreator_test.zip)

_SX4P01_ is a double layer disc. I'm not sure it's the problem...

**Comment by saramibreak** [comment]
> that size is totally wrong:

Is it still buggy size if you use the latest test version?

**Comment by Feathered-Serpent** [comment]
I can test this only in a few days because I'm reconfiguring my equipment for ripping game discs.

What I just noticed:
If you take the square root of 18446744073697270784 it is (rounded up) 4294967296 which is 2^32

**Comment by Feathered-Serpent** [comment]
> > that size is totally wrong:
> 
> Is it still buggy size if you use the latest test version?

much better:
```
		<rom name="Test.raw" size="8577653760" crc="944c7f29" md5="26bdf071a3512b7bc03fe72eb53b4d67" sha1="f937aa337a57b3182de6169126b8a6576d4e987c"/>
```
