### ISSUE TITLE
Proper usage of exit codes

### ISSUE THREAD

**Issue by Jakz** [saramibreak/DiscImageCreator#15]
I'm trying to fetch stdout from DiscImageCreator to DICUI to properly display it inside the UI itself.

It would be nice to be able to detect that something went wrong (non-existing drive, unsupported feature or whatever) by checking the error code of the process itself but it looks like that DiscImageCreator always exits with 0 (or at least in some trivial cases I checked, eg when you pass a drive letter that doesn't exist).

**Comment by saramibreak** [comment]
Fixed.
http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file
Only return 0(EXIT_SUCCESS) or 1(EXIT_FAILURE)
`	return nRet = nRet == TRUE ? EXIT_SUCCESS : EXIT_FAILURE;
`
