### ISSUE TITLE
Merge Disc dumping into DuckStation and PCSX2 Emulators?

### ISSUE THREAD

**Issue by SpaceAgeHero** [saramibreak/DiscImageCreator#152]
Hi there,

do you think you could add disc dumping features based on your tool to DuckStation and PCSX2 emulators?

I've described what I'd like to achieve here: https://github.com/PCSX2/pcsx2/issues/6910 but the idea was discarded.

Both emulators provide fullscreen / TV user interfaces and all I'd like to have is an option to install / dump inserted discs to the emulators game library.

**Comment by saramibreak** [comment]
I'm not interested in it.
