### ISSUE TITLE
Multi-session support for PX-W5224

### ISSUE THREAD

**Issue by tjanas** [saramibreak/DiscImageCreator#157]
Add support for multi-session discs with a Plextor PX-W5224 drive.

[Redumper](https://github.com/superg/redumper)  is able to dump multi-session discs with this drive that match DIC dumps produced with a Plextor PX-716 drive.

**Comment by saramibreak** [comment]
#41

**Comment by saramibreak** [comment]
Supported by https://github.com/saramibreak/DiscImageCreator/commit/e9b3dc3f3dd3d20d70d4ac2aec361c32abb5f8af
