### ISSUE TITLE
Protection Keys

### ISSUE THREAD

**Issue by mnadareski** [saramibreak/DiscImageCreator#16]
Would it be possible for external (or internal) keys for properly dumping DVD, HD-DVD, and BluRay discs? Unfortunately, some DVD's (especially) will crash immediately even with the `/cmi` flag.

**Comment by mnadareski** [comment]
I can confirm that DVDs with protection now dump properly, keeping the protection intact.

**Comment by mirh** [comment]
I mean.. Maybe instead of basing this over DeCss, libdvdcss was better?
