### ISSUE TITLE
[Q] change the default path of the driveOffset.txt file on linux. how?

### ISSUE THREAD

**Issue by sl1pkn07** [saramibreak/DiscImageCreator#160]
Hi

i want to change the default path of the file `driveOffset.txt`. in linux, wich is seems need to store in `/usr/local/share/DiscImageCreator` instead of `/usr/share/DiscImageCreator` where i have installed the data program

searching in the code, only i can found the path in here for the file `default.dat`:

https://github.com/saramibreak/DiscImageCreator/blob/bb05d981dbb3a39dd583d03a429a06e7a8c871c2/DiscImageCreator/xml.cpp#L604-L608

but i cant found for the file `driveOffset.txt` (this can be applicable to `ReadErrorProtect.txt` and `C2ErrorProtect.txt` files)

any help?

greetings

**Comment by saramibreak** [comment]
[DiscImageCreator_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/10073460/DiscImageCreator_test.tar.gz)

added this code.
```
#ifdef _WIN32
	fpDrive = OpenProgrammabledFile(_T("driveOffset.txt"), _T("r"));
#else
	if (PathFileExists("/usr/local/share/DiscImageCreator/driveOffset.txt")) {
		fpDrive = _tfopen(_T("/usr/local/share/DiscImageCreator/driveOffset.txt"), _T("r"));
	}
	else if (PathFileExists("/usr/share/DiscImageCreator/driveOffset.txt")) {
		fpDrive = _tfopen(_T("/usr/share/DiscImageCreator/driveOffset.txt"), _T("r"));
	}
	else {
		fpDrive = OpenProgrammabledFile(_T("driveOffset.txt"), _T("r"));
	}
#endif
```

**Comment by saramibreak** [comment]
@sl1pkn07
Is this working as you expected?

**Comment by sl1pkn07** [comment]
sorry the delay. yes, working. is possible add to upstream?

greetings

**Comment by saramibreak** [comment]
[DiscImageCreator_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/10142444/DiscImageCreator_test.tar.gz)
Also added `ReadErrorProtect.txt` and `C2ErrorProtect.txt`
