### ISSUE TITLE
How does DCI handle Dreamcast games with multiple tracks?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#161]
Hey there,

with DreamShell I dumped my few games. One of them is Ecco the Dolphin. After transfering the dump to my PC, I was surprised, that there were more than three tracks:
![grafik](https://user-images.githubusercontent.com/72162369/204136590-5fc1315e-1169-4011-8770-08dc5379d801.png)

Looking around some on Archive.org, I found an upload with DC Isos. There I looked into the contents of the Ecco.7z file which can be found here: https://ia902308.us.archive.org/view_archive.php?archive=/32/items/Dreamcast-GDI-Arquivista/Ecco%20the%20Dolphin%20-%20Defender%20of%20the%20Future%20%28EU%29.7z
(the link only opens a webpage showing the contents, it doesn't download the file).

I was kinda glad, that it was multiple files there as well. Now the question is: if using the correct drive, how would DIC handle this layout? Track 4 is an Audio track as well, though with some music, not like track 2 with the spoken warning.

Funnily, opening the GDI file with Isobuster reveals, that the files from track 3 do have LBA numbers within track 5. So that seems to be a strange mix.

**Comment by saramibreak** [comment]
Same layout http://redump.org/disc/19703/

**Comment by Feathered-Serpent** [comment]
So I guess it just works out of the box?

I just have seen the cue file from your link. There it's written
```
REM SINGLE-DENSITY AREA
FILE "Ecco the Dolphin - Defender of the Future (Europe) (En,Fr,De,Es) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Ecco the Dolphin - Defender of the Future (Europe) (En,Fr,De,Es) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
REM HIGH-DENSITY AREA
FILE "Ecco the Dolphin - Defender of the Future (Europe) (En,Fr,De,Es) (Track 3).bin" BINARY
  TRACK 03 MODE1/2352
    INDEX 01 00:00:00
FILE "Ecco the Dolphin - Defender of the Future (Europe) (En,Fr,De,Es) (Track 4).bin" BINARY
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Ecco the Dolphin - Defender of the Future (Europe) (En,Fr,De,Es) (Track 5).bin" BINARY
  TRACK 05 MODE1/2352
    INDEX 00 00:00:00
    INDEX 01 00:03:00

```

Now DreamShell created a GDI file showing this
```
5
1 0 4 2048 track01.iso 0
2 676 0 2352 track02.raw 0
3 45000 4 2048 track03.iso 0
4 91765 0 2352 track04.raw 0
5 95792 4 2048 track05.iso 0
```

So the data tracks are 2048, not 2352 (which I think is raw). Are the DreamShell dumps then "worse"?

**Comment by saramibreak** [comment]
It's up to you. If you want to preserve the disc image using _redump.org_ format, you can't use DreamShell.

**Comment by Feathered-Serpent** [comment]
thx for the clarification :)
