### ISSUE TITLE
Mixed-mode game CD - "This drive can't read the lead-out"

### ISSUE THREAD

**Issue by ajalberd** [saramibreak/DiscImageCreator#163]
**Version**
20220909T220450

**Describe the bug**
Cannot rip mixed-mode / enhanced audio CDs. 
"This drive can't read the lead-out"

**Screenshots**
```
.\DiscImageCreator.exe cd F taw.ccd 8
AppVersion
        32 bit, AnsiBuild, 20220909T220450
valid extension was omitted. -> set .bin
CurrentDirectory
        C:\Users\Carson\Downloads\MPFDump\Release_ANSI
WorkingPath
         Argument: taw.ccd.bin
         FullPath: C:\Users\Carson\Downloads\MPFDump\Release_ANSI\taw.ccd.bin
            Drive: C:
        Directory: \Users\Carson\Downloads\MPFDump\Release_ANSI\
         Filename: taw.ccd
        Extension: .bin
StartTime: 2022-11-29T20:35:13-0500
Set the drive speed: 12700KB/sec
DiskSize of [C:\Users\Carson\Downloads\MPFDump\Release_ANSI]
        Total:   870422933504 bytes
         Used:   540705849344 bytes
        ---------------------------
        Space:   329717084160 bytes
         => There is enough disk space for dumping
[WARNING] /c2 isn't set. The result of dumping may be incorrect if c2 error exists.
This drive doesn't define in driveOffset.txt
Please input drive offset(Samples): 6
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 0]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 1]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 2]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 4]
LBA[155871, 0x260df]: [F:ReadCDForCheckingReadInOut][L:1046]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, 04, 00, 02, 60, df, 00, 00, 01, f8, 00, 00
dwBufSize: 2352
This drive can't read the lead-out
```
**Disc title**
Total Air War (enhanced CD with 1 track audio, rest data)

**Disc ringcode**
All the string that is written the inner of the disc (IFPI etc.)

**URL**
Disc is only found used on Ebay

**Log file**
See above

**Comment by Feathered-Serpent** [comment]
Which drive do you use? Is it listed in https://github.com/saramibreak/DiscImageCreator/blob/master/Release_ANSI/Doc/TestedDrive.txt to be able to read the lead-out?

**Comment by Feathered-Serpent** [comment]
So is my ASUS BW16D1-HT with the 3.10DE firmware, but it also cannot read the lead out.

http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility#Non-Plextor_ODDs_.28Plextors_are_still_recommended.2C_as_more_testing_is_needed_for_these.29 lists your drive with firmwares being able to use Opcode 0xF1 which I think is some kind of replacement.

**Comment by ajalberd** [comment]
Interesting! I will try downgrading to official firmware and see if that works.

**Comment by ajalberd** [comment]
Now with 1.00 firmware I am getting:
'''
Please input drive offset(Samples): 6
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 0]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 1]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 2]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 4]
LBA[155871, 0x260df]: [F:ReadCDForCheckingReadInOut][L:1046]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, 04, 00, 02, 60, df, 00, 00, 01, f8, 00, 00
dwBufSize: 2352
This drive can't read the lead-out
/mr <val> is needed to read the lead-out. <val> is 50 by default
EndTime: 2022-11-30T19:57:44-0500
'''

**Comment by ajalberd** [comment]
Downgraded to 1.0, made some progress:

```
/mr <val> is needed to read the lead-out. <val> is 50 by default
```
Setting /mr to 10000 as a test
```
This drive can't read the lead-out
But 0xF1 opcode is supported
... ...
22 Cache LBA 155871, SubQ Trk aa, AMSF 34:40:21 [Lead-out]
23 Cache LBA 155872, SubQ Trk aa, AMSF 34:40:22 [Lead-out]
-----------------------------------------------------
Cache SIZE: 23 (This size is different every running)
-----------------------------------------------------
Checking SubQ adr (Track)  2/ 2
Checking SubRtoW (Track)  2/ 2
Reading DirectoryRecord   42/  42
Set OpCode: 0xbe, SubCode: 4(Pack)
Checking SubQ ctl (Track)  2/ 2
LBA[155871, 0x260df]: [F:FlushDriveCache][L:220]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
LBA[155871, 0x260df]: [F:FlushDriveCache][L:220]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Creating .scm (LBA) 155871/155871
[L:1346] Internal error. Failed to analyze the subchannel. Track[01]/[02]
EndTime: 2022-11-30T21:35:43-0500
```

**Comment by saramibreak** [comment]
@ajalberd
Upload the created files except .bin .img .scm .iso

**Comment by ajalberd** [comment]
[taw.ccd_subReadable.txt](https://github.com/saramibreak/DiscImageCreator/files/10133587/taw.ccd_subReadable.txt)
[taw.ccd_volDesc.txt](https://github.com/saramibreak/DiscImageCreator/files/10133588/taw.ccd_volDesc.txt)
[taw.ccd_20220909T220450.txt](https://github.com/saramibreak/DiscImageCreator/files/10133589/taw.ccd_20220909T220450.txt)
[taw.ccd_disc.txt](https://github.com/saramibreak/DiscImageCreator/files/10133590/taw.ccd_disc.txt)
[taw.ccd_drive.txt](https://github.com/saramibreak/DiscImageCreator/files/10133591/taw.ccd_drive.txt)
[taw.ccd_mainError.txt](https://github.com/saramibreak/DiscImageCreator/files/10133592/taw.ccd_mainError.txt)
[taw.ccd_mainInfo.txt](https://github.com/saramibreak/DiscImageCreator/files/10133593/taw.ccd_mainInfo.txt)
[taw.ccd_subError.txt](https://github.com/saramibreak/DiscImageCreator/files/10133594/taw.ccd_subError.txt)
[taw.ccd_subInfo.txt](https://github.com/saramibreak/DiscImageCreator/files/10133595/taw.ccd_subInfo.txt)

Thanks for looking into this!

**Comment by saramibreak** [comment]
https://github.com/saramibreak/DiscImageCreator/issues/163#issuecomment-1333924145 log is not same as https://github.com/saramibreak/DiscImageCreator/issues/163#issuecomment-1333076658

**Comment by ajalberd** [comment]
@saramibreak sorry about that, here is the most recent logs, using the command:
.\DiscImageCreator.exe cd F: taw.bin 72 /mr 6
subError.txt and subReadable.txt are 150mb and 26mb respectively, cannot upload. I can try again with a larger /mr and see if that helps. 
[taw_disc.txt](https://github.com/saramibreak/DiscImageCreator/files/10135555/taw_disc.txt)
[taw_mainInfo.txt](https://github.com/saramibreak/DiscImageCreator/files/10135556/taw_mainInfo.txt)
[taw_subInfo.txt](https://github.com/saramibreak/DiscImageCreator/files/10135557/taw_subInfo.txt)
[taw_volDesc.txt](https://github.com/saramibreak/DiscImageCreator/files/10135558/taw_volDesc.txt)

**Comment by saramibreak** [comment]
Thanks, but also upload __drive.txt_ and __mainError.txt_ , plz.

**Comment by ajalberd** [comment]
[taw_mainError.txt](https://github.com/saramibreak/DiscImageCreator/files/10141943/taw_mainError.txt)

[taw_drive.txt](https://github.com/saramibreak/DiscImageCreator/files/10141947/taw_drive.txt)

**Comment by ajalberd** [comment]
Also, what's the best output format for mixed/enhanced CDs?

**Comment by saramibreak** [comment]
/c2 is needed.
```
        /c2     Continue reading CD to recover C2 error existing sector
                        val1    value to reread (default: 4000)
                        val2    0: reread sector c2 error is reported (default)
                                1: reread all (or from first to last) sector
                        val3    first LBA to reread (default: 0)
                        val4    last LBA to reread (default: end-of-sector)
                                val3, 4 is used when val2 is 1
```

**Comment by ajalberd** [comment]
That worked, thank you! What in the logs pointed you to that being the error, for future reference?

**Comment by saramibreak** [comment]
> What in the logs pointed you to that being the error, for future reference?

If possible.

**Comment by ajalberd** [comment]
I think we can close this issue, then. But I'm just curious as to why it needed C2 flag and what lead you to conclude it was the issue?
