### ISSUE TITLE
Failed to analyze sub-channel when dumped multisession CD Audio

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#166]
**Version**
20220909

**Describe the bug**
When trying to dump a multisession audio CD with George Michael music, I get the error "Failed to Analyze Subchannel"

**Disc title**
Ladies & Gentlemen: The Best of George Michael CD2

**Disc ringcode**
S0100266472-0202 221 A00
IFPI 94K8

**URL**
https://www.discogs.com/master/98699-George-Michael-Ladies-Gentlemen-The-Best-Of-George-Michael

**Log file**
https://mega.nz/folder/IyAl3bTR#WV_WAkFlId1xoN_k1l131w

**Comment by saramibreak** [comment]
_subReadable.txt
```
LBA[342831, 0x53b2f]: P[ff], Q[41160000011800761306f44f]{ Data,      Copy NG,                  Track[16], Idx[00], RMSF[00:01:18], AMSF[76:13:06]}, RtoW[0, 0, 0, 0]
LBA[342832, 0x53b30]: P[ff], Q[410500000117007613078197]{ Data,      Copy NG,                  Track[05], Idx[00], RMSF[00:01:17], AMSF[76:13:07]}, RtoW[0, 0, 0, 0]
LBA[342833, 0x53b31]: P[ff], Q[41160000011600761308da29]{ Data,      Copy NG,                  Track[16], Idx[00], RMSF[00:01:16], AMSF[76:13:08]}, RtoW[0, 0, 0, 0]
```
Track No changes 16 to 05. It's incorrect but app can't detect as the error.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10147780/DiscImageCreator_test.zip)

Lead-in sectors of the 2nd session didn't check the subchannel error intentionally.
```
BOOL FixSubChannel(
	PEXEC_TYPE pExecType,
	PEXT_ARG pExtArg,
	PDEVICE pDevice,
	PDISC pDisc,
	PDISC_PER_SECTOR pDiscPerSector,
	INT nLBA,
	LPBOOL bReread
) {
	if (pExtArg->byMultiSession && pDisc->SCSI.n1stLBAofLeadout + 6750 <= nLBA &&
		nLBA < pDisc->SCSI.n1stLBAofLeadout + 11400) {
		return TRUE;
	}

```
I commented out this code.

**Comment by MrPepka** [comment]
The disk dumped correctly, but I'll ask again to be sure. 4498 errors seen after dump (no C2 errors) is this normal?
Logs - https://cdn.discordapp.com/attachments/934686273300475924/1048933853647081542/GEORGE_MICHAEL_logs.zip

**Comment by saramibreak** [comment]
Yes, it's lead-in sectors of the 2nd session error. No problem due to these area are trimmed.
