### ISSUE TITLE
Allow skipping of bad sectors/force RipGuard detection on Video DVD

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#169]
**Is your feature request related to a problem? Please describe.**
I do have a very few Video DVDs which don't have Ripguard (or at least it's not detected), but do still have thousands of defect sectors. Like this DVD:
![grafik](https://user-images.githubusercontent.com/72162369/209295663-ee9e59e4-a7c6-4da2-aa3e-f97728d71e38.png)
Every underscore is a defect or currently skipped sector from the program h2cdimage.

**Describe the solution you'd like**
It would be nice to have a switch for DVD ripping which allows DCI to try a number of retries on a defect sector, and if still not able to read, just continue with the next one. Or at least a parameter, which forces DCI to handle the disc like one with RipGuard, thus skipping a few sectors and read backwards (I wonder if the amount of skipped sectors should be configurable too?)

**Describe alternatives you've considered**
Try to find out, why DCI doesn't see any protection in the DVD

**Additional context**
One of the DVDs I have the problem with is Paddington (I only have the German version here): https://www.amazon.com/-/de/dp/B00QKCXER8/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=4006680072111&qid=1671782167&sr=8-1
The other movie is The Pink Panther from 2006 (also German version, from the Pink Panther Collection, but it's also to be found solo): https://www.amazon.com/-/de/dp/B000GYJUTC/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=B000GYJUTC&qid=1671782630&sr=8-1
I added the disc and CSS key file from an attempt on Paddington I made with DIC. It should write "Detected protection [MVSNRGFP]" if it would have found RipGuard in the disc file, but as you can see, it didn't. The file ends after "Outputted to _xxxKey.txt" because the dump didn't finish.

[_PADDINGTON__CSSKey.txt](https://github.com/saramibreak/DiscImageCreator/files/10293460/_PADDINGTON__CSSKey.txt)
[_PADDINGTON__disc.txt](https://github.com/saramibreak/DiscImageCreator/files/10293461/_PADDINGTON__disc.txt)

**Comment by Feathered-Serpent** [comment]
That's difficult to tell, because my movies are within a collection:
https://pictures.silentstrider.net/upload/2022/12/30/20221230085009-e341e09c.jpg

I do not have a single cover for the DVD to tell, which one it would be as the discs are piled up in jewel cases on the collection :-/
Can only show you how the disc itself does look and what's written onto it. Btw there is no visible ring or anything on the data side to be see.

**Comment by saramibreak** [comment]
Try https://github.com/mnadareski/BurnOutSharp

**Comment by Feathered-Serpent** [comment]
Found another disc which might be easier to be gotten. https://www.amazon.com/s?k=4030521449541&__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&ref=nb_sb_noss also gives me a hard time. Added _css and _disc file for that before DIC stopped because of retry count reached. MakeMKV was able to create a (decrypted) ISO out of it. Though as you might guess I'd like to have untampered ISOs (or at least as much untampered as possible).

[Spider-Man 3_disc.txt](https://github.com/saramibreak/DiscImageCreator/files/10327092/Spider-Man.3_disc.txt)
[Spider-Man 3_CSSKey.txt](https://github.com/saramibreak/DiscImageCreator/files/10327093/Spider-Man.3_CSSKey.txt)

BurnOutSharp on that disc doesn't find anything. Neither on the Pink Panther DVD. Running the DVDauth tool before BurnOutSharp only causes the latter one to take longer, but doesn't change the outcome.

Interestingly BurnOutSharp also doesn't detect anything on a DVD where DIC does (Detected protection [MVSNRGFP]).

**Comment by saramibreak** [comment]
https://en.wikipedia.org/wiki/List_of_Compact_Disc_and_DVD_copy_protection_schemes
Perhaps your dvds don't have RipGuard. I'm not sure but **[Sony ARccOS Protection](https://en.wikipedia.org/wiki/ARccOS_Protection)** uses unreadable/bad/corrupted sectors.

**Comment by Feathered-Serpent** [comment]
Judging from my ignorant programming knowledge, arccos should be detected by DIC I guess?

Is there anything I could see with sector view of certains LBAs that could help to find more information?

**Comment by saramibreak** [comment]
I have its protection dvd ([Stranger than fiction](https://www.engadget.com/2007-04-16-sony-copy-protection-taking-heat-again-now-dvds-wont-play.html)), but I can't find the identifier like "MVSNRGFP" of RipGuard.

**Comment by saramibreak** [comment]
May I upload all logs of _Paddington_, _The Pink Panther_, _Spider-Man 3_?

**Comment by Feathered-Serpent** [comment]
This is all I have from these discs made from DIC: 
[Logs.zip](https://github.com/saramibreak/DiscImageCreator/files/10366311/Logs.zip)

**Comment by saramibreak** [comment]
Test please.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10366422/DiscImageCreator_test.zip)

**Comment by Feathered-Serpent** [comment]
Tested on the first disc (Paddington), took a bit over 8 hours, but it finished:
[PADDINGTON.zip](https://github.com/saramibreak/DiscImageCreator/files/10374350/PADDINGTON.zip)

**Comment by Feathered-Serpent** [comment]
It seems that DIC always skips 100 sectors. Do you think it's useful to give an option to alter this amount via a parameter?

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10384953/DiscImageCreator_test.zip)
Added /sk

If you set _/sk 100_, it skips 100 sectors.

**Comment by Feathered-Serpent** [comment]
Works semi-fine. setting /sk uses the given amount, though not setting it defaults the value to 1
```
LBA[316000, 0x4d260]: [F:ReadDVD][L:335]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
Set 1st error LBA
LBA[316001, 0x4d261]: [F:ReadDVD][L:335]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
LBA[316002, 0x4d262]: [F:ReadDVD][L:335]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
LBA[316003, 0x4d263]: [F:ReadDVD][L:335]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
LBA[316004, 0x4d264]: [F:ReadDVD][L:335]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
```

**Comment by saramibreak** [comment]
> though not setting it defaults the value to 1

Yes, I changed default to 1.

**Comment by Feathered-Serpent** [comment]
Then it's working as intented :)
