### ISSUE TITLE
What is /74 used for?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#170]
Hey there,

question:
```
        /74     Read the lead-out about 74:00:00
                        For ring data (a.k.a Saturn Ring) of Sega Saturn
```
What does that do? I can't find any information on the internet if any tool (not even MPF) even uses this parameter. Should one use that on a Saturn disc? I acquired a physical copy of Panzer Dragoon Saga and want to dump the four discs only once to keep them save in the case afterwards.

**Comment by Feathered-Serpent** [comment]
```
AppVersion
        32 bit, AnsiBuild, 20220909T220450
/c2 val2 was omitted. set [0]
Unknown option: [/74]
If you see the usage, execute .exe without argument
```
Hmm seems like the option doesn't work anyway.

**Comment by saramibreak** [comment]
Before asking, see and search /74 using ctrl +F https://github.com/saramibreak/DiscImageCreator/wiki

**Comment by Feathered-Serpent** [comment]
Ohh my fault, haven't seen it's only for swap. Sorry for that.
