### ISSUE TITLE
DIC produces invalid CUE file for a certain disc.

### ISSUE THREAD

**Issue by nightson** [saramibreak/DiscImageCreator#173]
DIC Version: 20220909

Bug Description: 

DIC produced the follow CUE:
```
FILE "ZERODIVIDEX.bin" BINARY
  TRACK 01 MODE61/2352
    INDEX 01 00:00:00
```
Redumper, on the hand, produced an valid one:

```
FILE "dump_230106_102503_J.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
```
Is this a bug with DIC or I'm looking at a really wacky disc?

Logs: https://cdn.discordapp.com/attachments/705884111448834100/1060840873820180560/Zero_Divide_TW_Logs.7z

**Comment by saramibreak** [comment]
Test please.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10365599/DiscImageCreator_test.zip)

**Comment by saramibreak** [comment]
Uploaded.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10366463/DiscImageCreator_test.zip)

**Comment by nightson** [comment]
> Uploaded. [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10366463/DiscImageCreator_test.zip)

Thanks Sarami. This build works like a charm!
