### ISSUE TITLE
Q: Is this Audio CD dump correct?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#175]
Heya,

just got a new Audio CD and made a dump with DIC and a PLEXTOR PX-W4012A

Now I noticed these things in the DIC files:
_disc.txt:
```
========== Offset (Drive offset refers to http://www.accuraterip.com) ==========
	 Combined Offset(Byte)    392, (Samples)    98
	-   Drive Offset(Byte)    392, (Samples)    98
	----------------------------------------------
	       CD Offset(Byte)      0, (Samples)     0
	Overread sector: 1
	SubChannel Offset: 0
```
Overread sector? Is this a bad thing?

_subinfo.txt:
a message like this one is shown for each track (with different sector amounts):
```
P-channel pregap size (00:02:00) vs Q-channel pregap size (00:01:10) mismatch [65 sector(s)]
```

Just want to see, if anything could be wrong with the dump.

Logfiles:
[DIC Logs.zip](https://github.com/saramibreak/DiscImageCreator/files/10383529/DIC.Logs.zip)

**Comment by saramibreak** [comment]
> Overread sector? Is this a bad thing?

No. To read 392 bytes, 1 sector is overreaded. Btw, if you search the _CD Offset_ for audio cd, use _/vrfy 1_ (https://github.com/saramibreak/DiscImageCreator/wiki#dumping-guide-for-audio-cd)

> _subinfo.txt:

Some discs don't match p vs q pregap size. It's no problem.

**Comment by Feathered-Serpent** [comment]
Thanks for the info. Case closed.
