### ISSUE TITLE
Error on dumping 3.5 floppy disc

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#177]
**Version**
32 bit, AnsiBuild, 20230111T021641

**Describe the bug**
When trying to dump a regular 3.5 floppy drive (connected via standard floppy connector cable to floppy pins on motherboard) I get the message about an incorrect function.
I can format the drive at the command line with no problems, I also can list the contents (which are empty, because freshly formatted). Putting a file onto the floppy disk doesn't change the outcome.

**Log file**
listing of the empty floppy disk from command line
```
dir A:
 Volume in Laufwerk A: hat keine Bezeichnung.
 Volumeseriennummer: 9811-F131

 Verzeichnis von A:\

Datei nicht gefunden
```

DCI output (no log files are generated on disc containing more than that, not even _voldesc file when there's a file on the floppy disk):
```
DiscImageCreator fd a floppy.bin
AppVersion
        32 bit, AnsiBuild, 20230111T021641
CurrentDirectory
        C:\Users\Jack\Desktop\dumps
WorkingPath
         Argument: floppy.bin
         FullPath: C:\Users\Jack\Desktop\dumps\floppy.bin
            Drive: C:
        Directory: \Users\Jack\Desktop\dumps\
         Filename: floppy
        Extension: .bin
StartTime: 2023-01-25T08:15:57+0100
[F:TestUnitReady][L:45] GetLastError: 1, Unzulässige Funktion.

Please wait for 25000 milliseconds until the device is returned
EndTime: 2023-01-25T08:16:23+0100
```

**Comment by saramibreak** [comment]
> connected via standard floppy connector cable to floppy pins on motherboard

I only checked a floppy drive via usb, it's no problem.

**Comment by saramibreak** [comment]
> What is [F:TestUnitReady][L:45] refering to?

https://github.com/saramibreak/DiscImageCreator/blob/master/DiscImageCreator/execScsiCmd.cpp#L45
It failed to execute TestUnitReady function. Generally, It's a hardware problem.

**Comment by Feathered-Serpent** [comment]
As I can use the drive without any problems (formatting disk, copying files onto disk, saving BIOS image onto the disk) I only could imagine, that the old motherboard or the floppy connector doesn't return a specific information which a USB drive would do.

**Comment by Feathered-Serpent** [comment]
Considering modern motherboards never will have a floppy connector anymore, this problem probably can be neglected.
