### ISSUE TITLE
xxHash support

### ISSUE THREAD

**Issue by malvarenga123** [saramibreak/DiscImageCreator#179]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I saw that you added support for new hashes on commit f1b1ece.
Considering the size of some discs and the fact that xxHash is one of the fastest hashes for non-cryptographic use, it might be interesting to add support for it too.

**Describe the solution you'd like**
Also calculate XXH3 and XXH128 with the /d option

**Additional context**
https://cyan4973.github.io/xxHash/
https://github.com/Cyan4973/xxHash

**Comment by saramibreak** [comment]
Do you know any other applications that support xxHash?

**Comment by malvarenga123** [comment]
https://github.com/namazso/OpenHashTab
https://github.com/mcmilk/7-Zip-zstd

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/10731447/DiscImageCreator_test.zip)
[DiscImageCreator_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/10731449/DiscImageCreator_test.tar.gz)
- added: xxh3 (64bit) and xxh3 (128bit)

**Comment by malvarenga123** [comment]
Thanks a lot @saramibreak ! I tested with one disc and the hashes matched xxhsum.
