### ISSUE TITLE
Lack of commit message detail

### ISSUE THREAD

**Issue by bparker06** [saramibreak/DiscImageCreator#18]
I noticed the majority of git commit messages to this repo are just dates. Could we have more detailed messages in the future that explain what was changed or fixed and potentially why?

Even if it's in Japanese it is better than nothing.

Thanks!

**Comment by mirh** [comment]
Commits are certainly on the jumble side of the things.. And their titles/heads/messages are all dates indeed... But there isn't a single one without an extended description

**Comment by bparker06** [comment]
Ah! Silly me. I didn't notice you could expand that. Thanks
