### ISSUE TITLE
Unable to obtain ISRC

### ISSUE THREAD

**Issue by fuzz6001** [saramibreak/DiscImageCreator#184]
**Version**
20230309

**Describe the bug**
Unable to obtain ISRC for track 12.
This commit appears to be the cause.
84fd1864e168ec42d7a80e566997162ea246f1a5

**Screenshots**
```
DiscImageCreator cd G ISO\Audio CD\dump.bin 24 /c2 1000 /q
```

```
FILE "dump (Track 12).bin" BINARY
  TRACK 12 AUDIO
    TITLE "CREDIT"
    PERFORMER " "
    INDEX 00 00:00:00
    INDEX 01 00:03:00
```

**Disc title**
Shinji Hosoe Works Vol. 1: Dragon Spirit (Disc 2)
細江慎治 WORKS VOL.1 ドラゴンスピリット (Disc 2)

**URL**
https://www.amazon.co.jp/dp/B0097FIGK0

**Log file**
https://www.dropbox.com/s/os93gekr3brpqxz
https://www.dropbox.com/s/s28xs4eef5puy3p (20230201)

**Comment by fuzz6001** [comment]
@saramibreak 
added 20230201 logs

**Comment by saramibreak** [comment]
Is this issue related to https://github.com/saramibreak/DiscImageCreator/pull/183 ?

**Comment by fuzz6001** [comment]
PR #183 may make 84fd186 unnecessary. ("Nine Inch Nails - Broken" has many short tracks)
I am unable to grasp 84fd186.

**Comment by saramibreak** [comment]
comment out https://github.com/saramibreak/DiscImageCreator/commit/84fd1864e168ec42d7a80e566997162ea246f1a5
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11007605/DiscImageCreator_test.zip)

**Comment by fuzz6001** [comment]
It worked correctly 👍
However, "Nine Inch Nails - Broken" test is required.
```
FILE "dump (Track 12).bin" BINARY
  TRACK 12 AUDIO
    TITLE "CREDIT"
    PERFORMER " "
    ISRC JPG641206042
    INDEX 00 00:00:00
    INDEX 01 00:03:00
```
logs: [dump.zip](https://github.com/saramibreak/DiscImageCreator/files/11007695/dump.zip)

**Comment by Feathered-Serpent** [comment]
Because I was curious "back then" I bought me a used "Nine Inch Nails - Broken" disc for a few bucks back then. Just yesterday I threw it into my trash can here in my room... luckily I haven't put it away already heh. So just for being curious I tried it:
[dump.zip](https://github.com/saramibreak/DiscImageCreator/files/11011256/dump.zip)
