### ISSUE TITLE
Bootable version

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#185]
**Is your feature request related to a problem? Please describe.**
Some of the CD/DVDs I have are scratched and Windows (and even Linux) make it difficult to access certain disc sectors (even as no 3rd party drivers for SCSI support are installed) making them hard to dump, polishing such discs is not always successful effect

**Describe the solution you'd like**
It would be nice to make a bootable version of the DIC program, just like DMDE or MHDD programs do (these are just used to recover data from damaged hard drives, but CD/DVD drives rather also support it (DMDE certainly has such support)). This would help in dumping difficult discs (an example of a problem that could be solved with this - http://forum.redump.org/topic/32047/fm-towns-disc-c2-error/)

**Describe alternatives you've considered**
From alternative solutions, what comes to my mind is the implementation of an algorithm for fixing errors in sectors, such as in programs such as StrongRecovery or DMDE in versions for Windows and Linux (although both programs are paid, and their source codes are not available on the web)

**Additional context**
These are the programs in question
https://dmde.com/
https://www.strongrecovery.com/pl/
https://hddguru.com/software/2005.10.02-MHDD/

**Comment by malvarenga123** [comment]
The issue with that disc is related to a bug in Plextor's firmware, is it not?
How would it be fixed with a bootable version of DIC?

**Comment by MrPepka** [comment]
I'm talking about cases where reading and dumping a CD is made difficult by the system itself (it happened to me that DIC dumped a CD when I closed Windows Explorer). I don't know how common these cases are, but if the system can actually affect the quality of the dump (I'm talking about both Windows and Linux), it's worth reducing the number of factors affecting the quality of the dumps. In addition, data recovery programs in bootable versions are used, for example, to recover data from hard drives if the disk is heavily used and cannot be seen in the system, so analogously DIC in the bootable version can be used to read difficult discs that neither Windows nor Linux can see , and the drive can read something there

**Comment by saramibreak** [comment]
@MrPepka 
Do you hope that the damaged disc is recovered by the program like DMDE or MHDD?

> This would help in dumping difficult discs (an example of a problem that could be solved with this - http://forum.redump.org/topic/32047/fm-towns-disc-c2-error/)

As malvarenga123 says, this problem is a bug in Plextor's firmware, not damaged disc.

**Comment by MrPepka** [comment]
I once recovered one disc in the DMDE program (admittedly, some sectors were lost, but I recovered a large number of them that normally could not be read), so I think it's possible, although I used the Windows version. But from what I've seen, probably every data recovery program that has a bootable version also has the option to recover data from CD/DVD

**Comment by saramibreak** [comment]
Whatever the reason may be, I don't add the recovering program.
