### ISSUE TITLE
[Off topic] Pandora's box

### ISSUE THREAD

**Issue by u00101010** [saramibreak/DiscImageCreator#187]
Hello there!

Sorry for the heavily off-topic post, I just couldn't find an other way to contact you on this matter.
According to redump.org, you were the one dumping the Japanese version of the game パンドラの箱 (http://redump.org/disc/33700/) and I just have one question about it.

Does the game have an original Japanese voice actress as well, or are the subtitles and UI text the only thing that were localized into Japanese?

I cannot find absolutely any information about this game on Japanese sites so I'm hoping you might be able to answer this. Very sorry again for the off-topic, and thank you so much in advance.

**Comment by saramibreak** [comment]
> Does the game have an original Japanese voice actress as well

Yes.

> or are the subtitles and UI text the only thing that were localized into Japanese?

https://web.archive.org/web/20050307170430/http://www.microsoft.com/japan/games/pandora/screen.asp
