### ISSUE TITLE
Q: Automatic application of non-zero byte

### ISSUE THREAD

**Issue by fuzz6001** [saramibreak/DiscImageCreator#188]
Using latest version (20230401)

```
========== Check non-zero byte of the sector ==========
	There is not non-zero byte in the (Track AA)
	There is non-zero byte in the (Track 01)(-LBA): -46 byte => -12 sample
	Last non-zero byte before (Track AA): -49 byte => -12 sample
```

Is there an option to automatically apply the offset obtained here and dump it?
Or do I need to dump again using the /a option? (In this case `/a -12`)

**Comment by saramibreak** [comment]
> Or do I need to dump again using the /a option? (In this case /a -12)

Yes if you want to dump using "user specified offset".

**Comment by fuzz6001** [comment]
Okay, thanks for the reply.
