### ISSUE TITLE
Overread feature needed for mixed-mode CD.

### ISSUE THREAD

**Issue by Lutepatious** [saramibreak/DiscImageCreator#190]
I found some mixed-mode CD's audio reaches lead-out area.
They needs overread in audio mode.
I need combine "cd mode image" and "audio mode overread image".

**Comment by saramibreak** [comment]
- added: support mixed-mode disc in relation to reading the pregap of track 1 and the lead-out
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11167655/DiscImageCreator_test.zip)
