### ISSUE TITLE
Suggestion: don't use absolute paths in the logs

### ISSUE THREAD

**Issue by mariomadproductions** [saramibreak/DiscImageCreator#191]
Some people have expressed concern about hosting dumper's logs, because they may contain personal info (names) in the full absolute paths that exist in the log files. Could these be changed to relative paths, or could the windows user folder be censored automatically?

**Comment by fuzz6001** [comment]
@mariomadproductions 
As far as I know, DIC does not output absolute paths. (unless received by argument).
Perhaps the absolute path is what you received from MPF.

**Comment by fuzz6001** [comment]
That changed in MPF 2.5.

# MPF 2.4
![MPF2 4](https://user-images.githubusercontent.com/2080945/230749322-b86dfe4c-db54-4482-8ab1-6bcc6854702a.png)

# MPF 2.5
![MPF2 5](https://user-images.githubusercontent.com/2080945/230749326-6ebd57ec-0b2e-4028-babc-026c5eca3084.png)

**Comment by mariomadproductions** [comment]
I mean the file that has the command line in it, e.g. track_20230309T204228.txt [here](https://ia802600.us.archive.org/view_archive.php?archive=/21/items/ps2-the-suffering-ties-that-bind-europe-demo-dump-by-hiccup-on-2023-03-08-logs/track_logs.zip). I think sometimes it may be necessary to provide the full path to DIC, but I'm not sure the full paths should necessarily be in the output.

**Comment by fuzz6001** [comment]
In my opinion, it is self-responsibility.

For example, in my case:
```text
..\Release_ANSI\DiscImageCreator cd g .\dump 24 /c2 20 /q /ns /sf 
```




Also, logging "as is" is generally useful for debugging.

**Comment by mariomadproductions** [comment]
> In my opinion, it is self-responsibility.
> 
> For example, in my case:
> 
> ```
> ..\Release_ANSI\DiscImageCreator cd g .\dump 24 /c2 20 /q /ns /sf 
> ```
> 
> Also, logging "as is" is generally useful for debugging.

Some redump moderators are saying it may be a reason not to share logs publicly, and I don't think we can say to users not to use their normal login for dumping.

**Comment by fuzz6001** [comment]
I have no reason to oppose any more, so I will leave it to sarami's judgment.
