### ISSUE TITLE
Feature request: command line option to print the version & build info

### ISSUE THREAD

**Issue by tjanas** [saramibreak/DiscImageCreator#192]
Ability to execute DiscImageCreator with something like `--version` where it simply prints out the version, build information, and potentially the git commit identifier (and does not beep).

Also, if I execute DiscImageCreator.exe with just /q and no other arguments, it prints "Invalid argument" and it still beeps even though I provided the /q argument that is supposed to disable beep.

**Comment by tjanas** [comment]
That prints several pages of Usage info after printing the AppVersion & AnsiBuild, can there be a command line argument to only print the AppVersion & AnsiBuild?

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11233322/DiscImageCreator_test.zip)
- added: /v for printing only version
```
DiscImageCreator.exe /v
```
