### ISSUE TITLE
 in argument will error out

### ISSUE THREAD

**Issue by Ragowit** [saramibreak/DiscImageCreator#193]
**Describe the bug**
If the path contains , DIC will just error out.

 = SGCI

**Screenshots**
<img width="805" alt="image" src="https://user-images.githubusercontent.com/31790/231833011-7007dffb-1a7b-4add-aac6-1cf726897d70.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/31790/231833059-764d6abc-9c27-4dfd-aec7-cbaf5fd8c62a.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/31790/231838948-067802a4-a7ed-4148-87eb-535f4ea7e27e.png">

**Disc title**
UEFA EURO 2008

It's a PS3 disc.

**Other info**
Just remove the  if encountered in the argument would solve the problem.

**Comment by Feathered-Serpent** [comment]
if you start DIC from the command line yourself, you could try to make a **chcp 65001** before. That should make the command line window UTF 8 in codepage, eventually working better with whatever the icon is.

The other idea would be for DIC to remove such characters from the name.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11233721/DiscImageCreator_test.zip)
- added: print error message when prohibited characters are used

```
Please remove \, /, :, *, ?, “, <, >, | of the filename
```

DIC does not remove them automatically.
