### ISSUE TITLE
BH16NS40 SVC Code NS40 didn't supported

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#194]
**Version**
I'm using latest version
**Describe the bug**
The official list of supported drives mentions that the BH16NS40 is supported in DIC (http://wiki.redump.org/index.php?title=Optical_Disc_Drive_Compatibility), but it seems that only the SVC NS50 version works, while the older SVC NS40 version does not work in DIC (it says the drive does not support lead-out). The problem is that this is not true because the redumper works with this drive even with the opcode BE_CDDA. Will it be fixed?

**Screenshots**
<img width="610" alt="2023-04-13 (3)" src="https://user-images.githubusercontent.com/38865931/231881413-aba6f6a3-21b6-41dd-9e48-37b433430951.png">

**Comment by saramibreak** [comment]
https://github.com/saramibreak/DiscImageCreator/blob/master/DiscImageCreator/check.cpp#L159
1.00 and 1.02 are supported. Is your "VendorSpecific" different? Is VendorSpecific needed anyway?

**Comment by MrPepka** [comment]
I have a different firmware (version 1.03) so I think you need to add this code fragment to the check.cpp file
else if (!strncmp(pDevice->szProductRevisionLevel, "1.03", DRIVE_VERSION_ID_SIZE)) {
				if (!strncmp(pDevice->szVendorSpecific, "N0A03A0", 7)) {
					pDevice->by0xF1Drive = TRUE;

**Comment by saramibreak** [comment]
Added. 
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11239573/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
OK CD dumping works but DIC crashes when trying to fix C2 errors. Is the problem C2 offset or something else?

**Comment by saramibreak** [comment]
If it's true, it's another issue.
