### ISSUE TITLE
App crashes when fix C2 errors on BH16NS40

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#195]
**Version**
I have latest test version

**Describe the bug**
When the DIC detects a C2 error on a given disc and tries to fix this error after the dump is completed, the program crashes. The problem is only on the LG BH16NS40 drive, on the Plextor PX-712A the C2 error fix works. I changed the C2 offset in the MPF and it didn't do anything

**Comment by saramibreak** [comment]
Fixed it.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11241860/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Confirmed, fixed, thanks a lot
