### ISSUE TITLE
[Request] Include datfile snippet in machine parseable file for Xbox 360 variable files (SS, PFI, DMI)

### ISSUE THREAD

**Issue by mariomadproductions** [saramibreak/DiscImageCreator#197]
It'd be useful, so the size, md5 and sha1 can also be included in redump submissions, so that a datfile could potentially be made via scripts. Currently the data isn't very machine-readable, so that makes it difficult for MPF to use it, therefore difficult for redump to include that data.

See also: https://github.com/SabreTools/MPF/issues/482

**Comment by saramibreak** [comment]
Hashes of those files are outputted in _disc.txt. Does it mean that you hope that those are outputted in .dat?

**Comment by mariomadproductions** [comment]
> Hashes of those files are outputted in _disc.txt. Does it mean that you hope that those are outputted in .dat?
If they could be in a separate dat file (but not the main dat file), that'd be great.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11300271/DiscImageCreator_test.zip)
- added: _suppl.dat for .scm,  .img,  _SS.bin, _DMI.bin, _PFI.bin, _PIC.bin

**Comment by mariomadproductions** [comment]
Sorry, was waiting for feedback from DarkSabre, but I think this looks good, thanks.
