### ISSUE TITLE
HVN Discs

### ISSUE THREAD

**Issue by RedumpPT** [saramibreak/DiscImageCreator#199]
Hi
HVN discs were removed?
will support be added for this kind of discs?

**Comment by saramibreak** [comment]
> HVN discs

What is it?

**Comment by RedumpPT** [comment]
hasbro videonow 
http://redump.org/discs/system/hvn/
http://redump.org/discs/system/hvnc/
http://redump.org/discs/system/hvnjr/
http://redump.org/discs/system/hvnxp/

**Comment by RedumpPT** [comment]
yes... i'm a dumper. I can see them
I think you too

**Comment by saramibreak** [comment]
> I can see them

Then, this issue is deleted, ok?

**Comment by RedumpPT** [comment]
but the discovery of the offset is not automatic. or is it?

**Comment by saramibreak** [comment]
Do you want to report a bug? If yes, please use "Bug report" from [New Issue](https://github.com/saramibreak/DiscImageCreator/issues/new/choose). Do not "Open a blank issue".

By the way, my [VideoNow disc](http://redump.org/disc/58216/) works fine and can get the disc offset using /vnx.
```
Detected VideoNow XP
Search incomplete frame of track 01 (see _maininfo.txt)
1stHeader (81,e3,e3,c7,c7,81,81,e3...) Ofs: 776 (0x308)
2ndHeader (81,e3,e3,c7,c7,81,81,e3...) Ofs: 21608 (0x5468)
Empty bytes which are needed in this disc: 0 [20832 - (21608 - 776)]
========== Offset (Drive offset refers to http://www.accuraterip.com) ==========
	 Combined Offset(Byte)    440, (Samples)   110
	-   Drive Offset(Byte)    120, (Samples)    30
	----------------------------------------------
	       CD Offset(Byte)    320, (Samples)    80
	Overread sector: 1
	SubChannel Offset: 0
```

**Comment by saramibreak** [comment]
@RedumpPT 
Why not report a bug? I'll delete this issue whether you do it or not.

**Comment by RedumpPT** [comment]
sorry.. I was out... I will test it in a couple of hours

**Comment by RedumpPT** [comment]
ok i will open a new issue
