### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by jan-kleks** [saramibreak/DiscImageCreator#2]
It looks like there are no good ripping tools for Linux, at least when it comes to copying protected discs. Would it be possible to port this program to Linux?

**Comment by saramibreak** [comment]
I don't have Unix-like OS(Linux, BSD, OS-X etc). So I can't port now.

**Comment by jan-kleks** [comment]
I see. Maybe leave this issue ticket open then. Someone from the open-source community might get interested and help you with porting.

**Comment by mirh** [comment]
@saramibreak I think you misshaped with last PR

**Comment by saramibreak** [comment]
added: Linux build
http://www.mediafire.com/file/uw3e03kdkmsmvvq/DiscImageCreator_linux_test.tar

**Comment by Dimensional** [comment]
How long until we get an official build for Linux? It is rather easy to install a Linux OS, especially inside a VM like VirtualBox.

**Comment by SpiritQuaddicted** [comment]
@Dimensional Linux builds are in https://github.com/saramibreak/DiscImageCreator/releases

**Comment by gmipf** [comment]
How I can dump with the Linux version? The arguments still shows drive letters as examples. I have tried the device path [/dev/sr2] but it says "Invalid argument".

**Comment by SpiritQuaddicted** [comment]
`DiscImageCreator_linux.out cd /dev/sr0 "/tmp/rip.bin" 8 /c2` works fine for me. Your user might lack permissions, you can try running it as root if you cannot figure out groups and stuff.

This issue was about the Linux support itself. If you have specific problems with that please either use the forums or open a new issue.

**Comment by pseiler** [comment]
Added a rpm package for openSUSE https://software.opensuse.org/package/discimagecreator

**Comment by pseiler** [comment]
@saramibreak this can be closed, can't it?
