### ISSUE TITLE
Feature Request - DVD mode - Add /raw support for ASUS/LG drives for both DVDs and Blu Rays using the READ CACHE (F1 06) command

### ISSUE THREAD

**Issue by ehw** [saramibreak/DiscImageCreator#200]
**Describe the solution you'd like**
To go off my previous issue about raw dumping support, it turns out that ASUS/LG drives with RibShark's modified firmware can read the raw, scrambled 2384 byte sector data from a DVD by using the command to read from the cache. I don't believe this has been implemented in DIC? But this would be great to have. Unfortunately, these drives do not read Wii/GC discs with this method due to the invalid PFI data so drives have a hard time recognizing the discs. It also won't allow you to read security sectors either. But at least you can dump DVDISO no issue. Nothing seems to have this implemented so far.

As per RibShark's comment on an issue I opened with redumper:
https://github.com/superg/redumper/issues/40#issuecomment-1529148183

`
ASUS/LG drives support raw 2384 reads via the same F1 06 command as CDs (alternately 3C 03 02 XX XX XX YY YY YY 00, also works on CDs).
`

Blu Rays can also be read, but I'm having a hard time determining the size of an actual sector (with the ECC and header data).

**Comment by RibShark** [comment]
> it turns out that ASUS/LG drives with RibShark's modified firmware can read the raw, scrambled 2384 byte sector data from a DVD by using the command to read from the cache

No, my modified firmware is not necessary, it just needs to be below a specific version.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11366614/DiscImageCreator_test.zip)
- added: 2384 bytes/sector raw dump and unscramble

**Comment by ehw** [comment]
Doesn't seem to work?


H:\Tools\DiscImageCreator\test2>DiscImageCreator.exe dvd I conker 24 /raw
AppVersion
        32 bit, AnsiBuild, 20230502T011731
valid extension was omitted. -> set .raw
CurrentDirectory
        H:\Tools\DiscImageCreator\test2
WorkingPath
         Argument: conker.raw
         FullPath: H:\Tools\DiscImageCreator\test2\conker.raw
            Drive: H:
        Directory: \Tools\DiscImageCreator\test2\
         Filename: conker
        Extension: .raw
StartTime: 2023-05-01T18:31:13-0400
Set the drive speed: 0KB/sec
DiskSize of [H:\Tools\DiscImageCreator\test2]
        Total:  2000363188224 bytes
         Used:  1879711256576 bytes
        ---------------------------
        Space:   120651931648 bytes
         => There is enough disk space for dumping
Rawdump command [0]:0x3c [1]:0x02 [2]:0000
LBA[000000, 0000000]: [F:ReadDVDRaw][L:951]
        Opcode: 0x3c
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
EndTime: 2023-05-01T18:31:16-0400

Logs:
[test2.zip](https://github.com/saramibreak/DiscImageCreator/files/11368464/test2.zip)

**Comment by saramibreak** [comment]
```
	            VendorId: ASUS    
	           ProductId: BW-16D1HT       
	ProductRevisionLevel: 3.10
```
Downgrade is needed.

**Comment by ehw** [comment]
My bad, I thought it would work with Rib's patched firmware. I downgraded my firmware using this:
http://wiki.redump.org/index.php?title=Flashing_with_Asus_BW-16D1HT_3.02_firmware

Tested with my Xbox disc, dumped the DVD Video partition after downgrading. All seems to work. :)

H:\Tools\DiscImageCreator\test2>DiscImageCreator.exe dvd I conker 24 /raw
AppVersion
        32 bit, AnsiBuild, 20230502T011731
valid extension was omitted. -> set .raw
CurrentDirectory
        H:\Tools\DiscImageCreator\test2
WorkingPath
         Argument: conker.raw
         FullPath: H:\Tools\DiscImageCreator\test2\conker.raw
            Drive: H:
        Directory: \Tools\DiscImageCreator\test2\
         Filename: conker
        Extension: .raw
StartTime: 2023-05-01T21:02:30-0400
Set the drive speed: 0KB/sec
DiskSize of [H:\Tools\DiscImageCreator\test2]
        Total:  2000363188224 bytes
         Used:  1879718846464 bytes
        ---------------------------
        Space:   120644341760 bytes
         => There is enough disk space for dumping
Rawdump command [0]:0x3c [1]:0x02 [2]:0000
Creating raw(LBA)    6832/   6992
Layer is changed: 20 -> 01
Creating raw(LBA)    6992/   6992
GOD/WOD unscrambler 0.4.1 (xt5@ingenieria-inversa.cl)

This program is distributed under GPL license,
see the LICENSE file for more info.

caching seed 0080
caching seed 0005
caching seed 0100
caching seed 000a
caching seed 0200
caching seed 0014
caching seed 0400
caching seed 0028
caching seed 0801
caching seed 0050
caching seed 1002
caching seed 00a0
caching seed 2004
caching seed 0140
caching seed 4008
caching seed 0280
caching seed 0014
caching seed 0400
caching seed 0028
caching seed 0801
caching seed 0050
caching seed 1002
caching seed 00a0
caching seed 2004
caching seed 0140
caching seed 4008
image successfully unscrambled.
time elapsed: 3.00 seconds.
ret = 0
Hashing: conker.iso
EndTime: 2023-05-01T21:02:55-0400

Raw scrambled contents, should include ECC/EDC too.
![image](https://user-images.githubusercontent.com/885618/235557764-c450a8f5-31fe-47ed-94da-ccd0bd03cf5f.png)

 Feel free to merge unless you need more testing.
