### ISSUE TITLE
HVNC dumping problem

### ISSUE THREAD

**Issue by RedumpPT** [saramibreak/DiscImageCreator#201]
**Version**
DiscImageCreator_20230413

**Describe the bug**
i run this command to dump a vnc disc.
DiscImageCreator.exe cd d "C:\DiscImageCreator_20230413\Release_ANSI\iso\vnc\vnc.bin" 24 /vnc
disc is this one:
http://redump.org/disc/65043/

dumped data does not match

**Disc title**
Bob Esponja (Disc 3) ("Me muero por una tarta" y "Cangrejo de imitación")

**Log file**
[vnc.zip](https://github.com/saramibreak/DiscImageCreator/files/11372459/vnc.zip)

**Comment by saramibreak** [comment]
It seems that offset is correct.
```
	 Combined Offset(Byte)    488, (Samples)   122
	-   Drive Offset(Byte)    120, (Samples)    30
	----------------------------------------------
	       CD Offset(Byte)    368, (Samples)    92
```

Try this command.
`DiscImageCreator.exe cd d "C:\DiscImageCreator_20230413\Release_ANSI\iso\vnc\vnc.bin" 24 /a -4416`

**Comment by RedumpPT** [comment]
[vnc-good.zip](https://github.com/saramibreak/DiscImageCreator/files/11391806/vnc-good.zip)
yes, if we set the correct offset, the dump matches redump
