### ISSUE TITLE
Bug - DVD Mode - /raw can't resume properly with 2384 sized dumps (Lite-On and ASUS)

### ISSUE THREAD

**Issue by ehw** [saramibreak/DiscImageCreator#202]
**Version**
20230502T011731 (test version from issue #200 )

**Describe the bug**
DIC can't seem to resume properly (with /re) for what appears to be only raw, scrambled 2384 sized dumps. This bug occurs for both ASUS 3.02 drives (via READ CACHE method recently implemented) and the Lite-On LH-18A1P. This was tested on two separate DVD-Rs as well. For some reason when I tested my Conker disc, I didn't experience this issue and it was able to descramble just fine.

This issue does not occur for 2064 byte dumps, like dumping GC/Wii discs with the Plextor READ BUFFER method. I was able to resume both GC and Wii discs with my drive just fine.

To recreate:
1.) Use either a drive with down graded ASUS 3.02 firmware or a Lite-On LH-18A1P.
2.) Start dumping a disc with the /raw command.
3.) While the dump is progressing, press Ctrl+C to stop the dump.
4.) Resume the dump with the /re command.
5.) It appears that DIC calculates the position to jump to based on the .raw file, but when it starts to resume it begins at the very start of the disc instead (30000). DIC or the drive gets confused, and it starts reading data for a much earlier sector than the sector its expecting to pick up with from the .raw file.

**Screenshots**
From ASUS:
![image](https://user-images.githubusercontent.com/885618/235807981-f72210ae-388e-4653-ada6-36d5a63653be.png)

From Lite-On:
Rawdump command [0]:0x3c [1]:0x01 [2]:0x01
Start resuming -> Last sector num:  3c3a0
Checking sector num:  30000
Detected bad sector. Expected sector num:  30010, Got sector num: faa6a1

**Log file**
[bug 202 log.zip](https://github.com/saramibreak/DiscImageCreator/files/11378383/bug.202.log.zip)

**Comment by saramibreak** [comment]
Uploaded but not test.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11389721/DiscImageCreator_test.zip)

**Comment by ehw** [comment]
This bug seems fixed. Thanks sarami!

#204 still remains, however..
