### ISSUE TITLE
Bug - DVD Mode - ASUS drives stop reading one block (16 sectors) away from the end of the disc with /raw

### ISSUE THREAD

**Issue by ehw** [saramibreak/DiscImageCreator#204]
**Version**
20230502T011731 (test version from issue https://github.com/saramibreak/DiscImageCreator/issues/200 )

**Describe the bug**
While dumping a DVD-R with an ASUS drive's /raw reading capabilities, the program stops one block (16 sectors) away from the very end of the disc for some reason. When this occurs, the LED light on the drive is still flashing as if it were still doing something to the disc, DIC is not writing to the .raw file, and the program seems stuck. CTRL+C will end the dump, so the program itself hasn't hung.  I'm not sure if this problem affects only ASUS drives at the moment. My Conker disc did not have this issue, which is on a pressed DVD. Maybe this issue only affects recordable discs?

To replicate this issue:
1.) Use an ASUS drive with downgraded 3.02 firmware.
2.) Use the /raw command to dump a DVD-R
3.) As the drive gets 16 sectors away from the end of the disc, the dump should halt, the LED light on the drive should still be blinking indicating activity and the sound of the disc still spinning in the drive, and nothing should be writing to the .raw file. 

I left DIC alone for about 15 minutes and nothing changed from the screenshot below...

**Screenshots**
![image](https://user-images.githubusercontent.com/885618/235811278-fcbc4e2c-e0cb-4515-aebe-81bc9799862a.png)

**Log file**
The following log file is for when I used CTRL+C to end the program once it became stuck at 629008 / 629023.
[bug - 204.zip](https://github.com/saramibreak/DiscImageCreator/files/11378569/bug.-.204.zip)

**Comment by saramibreak** [comment]
Does other drive also stuck? Only Asus?

**Comment by ehw** [comment]
@saramibreak  I think I can see where the problem seems to be occurring.

When the sector count is an odd number, that's when the ASUS stalls on the last block. If it's even, it works.

This was another disc I had that also had the same thing happened:

> DiscImageCreator.exe dvd I "Dancing Stage Unleashed Xbox - First Playable (RAW)" 24 /raw
> AppVersion
>         32 bit, AnsiBuild, 20230504T152724
> valid extension was omitted. -> set .raw
> CurrentDirectory
>         H:\Tools\DiscImageCreator\test2
> WorkingPath
>          Argument: Dancing Stage Unleashed Xbox - First Playable (RAW).raw
>          FullPath: H:\Tools\DiscImageCreator\test2\Dancing Stage Unleashed Xbox - First Playable (RAW).raw
>             Drive: H:
>         Directory: \Tools\DiscImageCreator\test2\
>          Filename: Dancing Stage Unleashed Xbox - First Playable (RAW)
>         Extension: .raw
> StartTime: 2023-05-04T21:06:46-0400
> Set the drive speed: 0KB/sec
> DiskSize of [H:\Tools\DiscImageCreator\test2]
>         Total:  2000363188224 bytes
>          Used:  1925237694464 bytes
>         ---------------------------
>         Space:    75125493760 bytes
>          => There is enough disk space for dumping
> Rawdump command [0]:0x3c [1]:0x02 [2]:0000
> Creating raw(LBA) 1913760/1913775

However, this one was fine:

> H:\Tools\DiscImageCreator\test2>DiscImageCreator.exe dvd I "NANOBREAKER REVIEW (RAW)" 24 /raw
> AppVersion
>         32 bit, AnsiBuild, 20230504T152724
> valid extension was omitted. -> set .raw
> CurrentDirectory
>         H:\Tools\DiscImageCreator\test2
> WorkingPath
>          Argument: NANOBREAKER REVIEW (RAW).raw
>          FullPath: H:\Tools\DiscImageCreator\test2\NANOBREAKER REVIEW (RAW).raw
>             Drive: H:
>         Directory: \Tools\DiscImageCreator\test2\
>          Filename: NANOBREAKER REVIEW (RAW)
>         Extension: .raw
> StartTime: 2023-05-04T19:51:17-0400
> Set the drive speed: 0KB/sec
> DiskSize of [H:\Tools\DiscImageCreator\test2]
>         Total:  2000363188224 bytes
>          Used:  1912011862016 bytes
>         ---------------------------
>         Space:    88351326208 bytes
>          => There is enough disk space for dumping
> LBA[000000, 0000000]: [F:ReadDiscStructure][L:1447]
>         Opcode: 0xad
>         ScsiStatus: 0x02 = CHECK_CONDITION
>         SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
> FormatCode: 30 failed
> cdb: ad, 00, 00, 00, 00, 00, 00, 30, 00, 04, 00, 00
> Rawdump command [0]:0x3c [1]:0x02 [2]:0000
> Creating raw(LBA) 1853472/1853472
> GOD/WOD unscrambler 0.4.1 (xt5@ingenieria-inversa.cl)
> 
> This program is distributed under GPL license,
> see the LICENSE file for more info.
> 
> caching seed 0080
> caching seed 0005
> caching seed 0100
> caching seed 000a
> caching seed 0200
> caching seed 0014
> caching seed 0400
> caching seed 0028
> caching seed 0801
> caching seed 0050
> caching seed 1002
> caching seed 00a0
> caching seed 2004
> caching seed 0140
> caching seed 4008
> caching seed 0280
> image successfully unscrambled.
> time elapsed: 54.00 seconds.
> ret = 0
> Hashing: NANOBREAKER REVIEW (RAW).iso
> EndTime: 2023-05-04T21:00:03-0400

**Comment by saramibreak** [comment]
> When the sector count is an odd number, that's when the ASUS stalls on the last block. If it's even, it works.

[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11405863/DiscImageCreator_test.zip)

- fixed: transfer length when it's lower than 16. (NOT TEST)

**Comment by ehw** [comment]
> > When the sector count is an odd number, that's when the ASUS stalls on the last block. If it's even, it works.
> 
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11405863/DiscImageCreator_test.zip)
> 
> * fixed: transfer length when it's lower than 16. (NOT TEST)

Works! Thank you!

> H:\Tools\DiscImageCreator\test2>DiscImageCreator.exe dvd I "Dancing Stage Fusion - Preview (RAW)" 24 /raw
> AppVersion
>         32 bit, AnsiBuild, 20230505T204849
> valid extension was omitted. -> set .raw
> CurrentDirectory
>         H:\Tools\DiscImageCreator\test2
> WorkingPath
>          Argument: Dancing Stage Fusion - Preview (RAW).raw
>          FullPath: H:\Tools\DiscImageCreator\test2\Dancing Stage Fusion - Preview (RAW).raw
>             Drive: H:
>         Directory: \Tools\DiscImageCreator\test2\
>          Filename: Dancing Stage Fusion - Preview (RAW)
>         Extension: .raw
> StartTime: 2023-05-05T21:13:06-0400
> Set the drive speed: 0KB/sec
> DiskSize of [H:\Tools\DiscImageCreator\test2]
>         Total:  2000363188224 bytes
>          Used:  1949699543040 bytes
>         ---------------------------
>         Space:    50663645184 bytes
>          => There is enough disk space for dumping
> Rawdump command [0]:0x3c [1]:0x02 [2]:0000
> Creating raw(LBA)  629023/ 629023
> GOD/WOD unscrambler 0.4.1 (xt5@ingenieria-inversa.cl)
> 
> This program is distributed under GPL license,
> see the LICENSE file for more info.
> 
> caching seed 0080
> caching seed 0005
> caching seed 0100
> caching seed 000a
> caching seed 0200
> caching seed 0014
> caching seed 0400
> caching seed 0028
> caching seed 0801
> caching seed 0050
> caching seed 1002
> caching seed 00a0
> caching seed 2004
> caching seed 0140
> caching seed 4008
> caching seed 0280
> image successfully unscrambled.
> time elapsed: 20.00 seconds.
> ret = 0
> Hashing: Dancing Stage Fusion - Preview (RAW).iso
> EndTime: 2023-05-05T21:38:10-0400

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11411962/DiscImageCreator_test.zip)
- fixed: read size from the cache.

**Comment by ehw** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11411962/DiscImageCreator_test.zip)
> 
> * fixed: read size from the cache.

No change, the unscrambled raw dump is still 30720 bytes smaller than the read12 dump.

Logs:
[bug - 204 logs.zip](https://github.com/saramibreak/DiscImageCreator/files/11413188/bug.-.204.logs.zip)

**Comment by saramibreak** [comment]
> <rom name="Dancing Stage Fusion - Preview (RAW).raw" size="1499590832"

It seems raw file size is correct (1499590832 / 2384 = 629023 * 2048 = 1288239104)

Probably it's [unscrambler](https://github.com/saramibreak/unscrambler) problem.

**Comment by saramibreak** [comment]
> Probably it's [unscrambler](https://github.com/saramibreak/unscrambler) problem. If last block isn't 16 sectors, it's needed to change the read size.

Fixed it.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11415146/DiscImageCreator_test.zip)

**Comment by ehw** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/885618/236684786-e0d57da2-63c8-4e27-87fd-0b58f5854053.png)

Feel free to merge. :)
