### ISSUE TITLE
Bug - DVD Mode - No error messages at all when /raw is used

### ISSUE THREAD

**Issue by ehw** [saramibreak/DiscImageCreator#205]
**Version**
20230504T032226 (Test version for #202 )

**Describe the bug**
DiscImageCreator does not report any error messages that are reported by the drive when /raw is used. 

This was in part probably caused by the change in order to silence the error spam when dumping Wii/GC with Plextors, which generated SCSI errors with every block read. However, doing so silenced legitimate errors too, which is making diagnostics pretty difficult with the /raw mode...

This affects any disc and drive reading method strictly when /raw mode is used.

The only solution I can think of is to reenable errors to propagate even though they might spam the console and log file a lot. Unless there's something specifically setup when Plextors are used with /raw for GameCube and Wii discs and where only certain messages returned with each initial read on a sector, maybe we have no choice but to allow all error messages to be printed...

I'm not sure what would be an ideal solution here...

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11394220/DiscImageCreator_test.zip)
When only Plextor and Nintendo disc dumps, message is not shown.

**Comment by ehw** [comment]
This works, thank you!

I'll back to #204 in a moment. I needed the error messages to return to diagnose the issue further as I wasn't sure if maybe the drive was returning something without me knowing.
