### ISSUE TITLE
ILLEGAL MODE FOR THIS TRACK on multisession disc in Plextor PX-712A drive

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#209]
**Version**
Used latest test version
**Describe the bug**
One of my multisession discs is throwing an ILLEGAL MODE FOR THIS TRACK message even though I am using a PX-712A drive to dump such discs. The problem is only with this disc

**Screenshots**
Paste command-line text.

**Disc title**
Max Kids 3/2006

**Disc ringcode**
VEGCD 4311  MAX KIDS 3-2006 PL <tab> Vegart <tab> www.vegart.pl

**URL**
Isn't available on auctions, sorry

**Log file**
[Max Kids.zip](https://github.com/saramibreak/DiscImageCreator/files/11480738/Max.Kids.zip)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11486312/DiscImageCreator_test.zip)
- added: repeat 5 times at max when the lead-in & out can't be read correctly

**Comment by MrPepka** [comment]
It works thx
