### ISSUE TITLE
Failed to get (Track 01)(-LBA) error.

### ISSUE THREAD

**Issue by Lutepatious** [saramibreak/DiscImageCreator#215]
AppVersion
        32 bit, AnsiBuild, 20230413T211754

**Describe the bug**
Failed to get (Track 01)(-LBA)

**Screenshots**
AppVersion
        32 bit, AnsiBuild, 20230413T211754
/c2 val1 was omitted. set [4000]
/c2 val2 was omitted. set [0]
/c2 val3 was omitted. set [0]
valid extension was omitted. -> set .bin
CurrentDirectory
        D:\audio\ALICE-001
WorkingPath
         Argument: ALICE-001.bin
         FullPath: D:\audio\ALICE-001\ALICE-001.bin
            Drive: D:
        Directory: \audio\ALICE-001\
         Filename: ALICE-001
        Extension: .bin
StartTime: 2023-05-30T14:11:07+0900
Set the drive speed: 62266KB/sec
DiskSize of [D:\audio\ALICE-001]
        Total:  4000650883072 bytes
         Used:  1794546221056 bytes
        ---------------------------
        Space:  2206104662016 bytes
         => There is enough disk space for dumping
This drive (DVDR   PX-760A  ) supports [OpCode: 0xd8, SubCode: 1]
This drive (DVDR   PX-760A  ) supports [OpCode: 0xd8, SubCode: 2]
This drive (DVDR   PX-760A  ) supports [OpCode: 0xd8, SubCode: 8]
Checking reading lead-out -> OK
Checking SubQ adr (Track) 13/13
Checking SubRtoW (Track) 13/13
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -3298/   -5000
Failed to get (Track 01)(-LBA)
EndTime: 2023-05-30T14:11:51+0900

**Disc title**
Legend of Rance Kichiku Densetu (Soundtrack CD of Alicesoft Rance III Option set)

**Disc ringcode**
ALICE-001 SP-PUA

**Log file**
[ALICE-001_20230413T211754.txt](https://github.com/saramibreak/DiscImageCreator/files/11596163/ALICE-001_20230413T211754.txt)
[ALICE-001_disc.txt](https://github.com/saramibreak/DiscImageCreator/files/11596164/ALICE-001_disc.txt)
[ALICE-001_drive.txt](https://github.com/saramibreak/DiscImageCreator/files/11596165/ALICE-001_drive.txt)
[ALICE-001_mainInfo.txt](https://github.com/saramibreak/DiscImageCreator/files/11596166/ALICE-001_mainInfo.txt)

Other text files are empty.

I ripped -5000 to -1149 by audio mode.
[ALICE-001_subReadable.txt](https://github.com/saramibreak/DiscImageCreator/files/11596176/ALICE-001_subReadable.txt)

LBA[-02328, 0xfffff6e8]: P[00], Q[010010021073002349004cff]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[00], Point[10], AMSF[02:10:73], StartTimeOfTrack[23:49:00]}, RtoW[Unknown[63], Unknown[63], Unknown[63], Unknown[63]]
LBA[-02327, 0xfffff6e9]: P[00], Q[020000000000000000002175]{Audio, 2ch, Copy NG, Pre-emphasis No, MediaCatalogNumber [             ], AMSF[     :00]}, RtoW[Unknown[63], Unknown[63], Unknown[63], Unknown[63]] *<=== Absolute 0 sector with MCN!?*
LBA[-02326, 0xfffff6ea]: P[ff], Q[01010000017400000001ba98]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[01], Idx[00], RMSF[00:01:74], AMSF[00:00:01]}, RtoW[Unknown[63], Unknown[63], Unknown[63], Unknown[63]]

**Comment by saramibreak** [comment]
> Absolute 0 sector with MCN!?

Yes.
Uploaded. [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11596630/DiscImageCreator_test.zip)

**Comment by Lutepatious** [comment]
D:\audio\ALICE-001>D:\DiscImageCreator_test\Release_ANSI\DiscImageCreator cd E ALICE-001 48 /c2 /s 2
AppVersion
        32 bit, AnsiBuild, 20230530T152632
/c2 val1 was omitted. set [4000]
/c2 val2 was omitted. set [0]
/c2 val3 was omitted. set [0]
valid extension was omitted. -> set .bin
CurrentDirectory
        D:\audio\ALICE-001
WorkingPath
         Argument: ALICE-001.bin
         FullPath: D:\audio\ALICE-001\ALICE-001.bin
            Drive: D:
        Directory: \audio\ALICE-001\
         Filename: ALICE-001
        Extension: .bin
StartTime: 2023-05-30T15:48:27+0900
Set the drive speed: 8467KB/sec
DiskSize of [D:\audio\ALICE-001]
        Total:  4000650883072 bytes
         Used:  1791130914816 bytes
        ---------------------------
        Space:  2209519968256 bytes
         => There is enough disk space for dumping
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 1]
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 2]
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 8]
Checking SubQ adr (Track) 13/13
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8187/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8564/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8400/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8293/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8338/  -10000
Failed to get (Track 01)(-LBA)
Checking SubRtoW (Track) 13/13
Set OpCode: 0xd8, SubCode: 8(Raw)
Checking SubQ ctl (Track) 13/13
Creating .scm (LBA) 164400/164400
No C2 errors
Moving .scm to .img
Creating cue and ccd (Track) 13/13
Creating bin (Track) 13/13
Creating (Track all).img
[F:ConcatenateFromPregapToLeadout][L:2989] GetLastError: 2, 指定されたファイルが見つかりません。

Hashing: ALICE-001.img
Hashing: ALICE-001 (Track 01).bin
Hashing: ALICE-001 (Track 02).bin
Hashing: ALICE-001 (Track 03).bin
Hashing: ALICE-001 (Track 04).bin
Hashing: ALICE-001 (Track 05).bin
Hashing: ALICE-001 (Track 06).bin
Hashing: ALICE-001 (Track 07).bin
Hashing: ALICE-001 (Track 08).bin
Hashing: ALICE-001 (Track 09).bin
Hashing: ALICE-001 (Track 10).bin
Hashing: ALICE-001 (Track 11).bin
Hashing: ALICE-001 (Track 12).bin
Hashing: ALICE-001 (Track 13).bin
EndTime: 2023-05-30T15:56:23+0900

[ALICE-001.zip](https://github.com/saramibreak/DiscImageCreator/files/11596936/ALICE-001.zip)

**Comment by saramibreak** [comment]
Check also the next subchannel.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11597829/DiscImageCreator_test.zip)

**Comment by Lutepatious** [comment]
It seems fail between Track 00 reading and Track 01 (-LBA) reading.

**Comment by saramibreak** [comment]
More fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11599812/DiscImageCreator_test.zip)

**Comment by Lutepatious** [comment]
Still not solved last 2 test versions.
ALICE-001 (Track 00).bin is generated, but ALICE-001 (Track 01)(-LBA).bin is not generated.

D:\audio\ALICE-001>D:\DiscImageCreator_test\Release_ANSI\DiscImageCreator cd E ALICE-001 48 /c2 /s 2
AppVersion
        32 bit, AnsiBuild, 20230530T211530
/c2 val1 was omitted. set [4000]
/c2 val2 was omitted. set [0]
/c2 val3 was omitted. set [0]
valid extension was omitted. -> set .bin
CurrentDirectory
        D:\audio\ALICE-001
WorkingPath
         Argument: ALICE-001.bin
         FullPath: D:\audio\ALICE-001\ALICE-001.bin
            Drive: D:
        Directory: \audio\ALICE-001\
         Filename: ALICE-001
        Extension: .bin
StartTime: 2023-05-30T21:34:31+0900
Set the drive speed: 0KB/sec
DiskSize of [D:\audio\ALICE-001]
        Total:  4000650883072 bytes
         Used:  1792563036160 bytes
        ---------------------------
        Space:  2208087846912 bytes
         => There is enough disk space for dumping
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 1]
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 2]
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 8]
Checking SubQ adr (Track) 13/13
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8277/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8035/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8532/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -8098/  -10000
Failed to get (Track 01)(-LBA)
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -7777/  -10000
Failed to get (Track 01)(-LBA)
Checking SubRtoW (Track) 13/13
Set OpCode: 0xd8, SubCode: 8(Raw)
Checking SubQ ctl (Track) 13/13
Creating .scm (LBA) 164400/164400
No C2 errors
Moving .scm to .img
Creating cue and ccd (Track) 13/13
Creating bin (Track) 13/13
Creating (Track all).img
[F:ConcatenateFromPregapToLeadout][L:2989] GetLastError: 2, 指定されたファイルが見つかりません。

Hashing: ALICE-001.img
Hashing: ALICE-001 (Track 01).bin
Hashing: ALICE-001 (Track 02).bin
Hashing: ALICE-001 (Track 03).bin
Hashing: ALICE-001 (Track 04).bin
Hashing: ALICE-001 (Track 05).bin
Hashing: ALICE-001 (Track 06).bin
Hashing: ALICE-001 (Track 07).bin
Hashing: ALICE-001 (Track 08).bin
Hashing: ALICE-001 (Track 09).bin
Hashing: ALICE-001 (Track 10).bin
Hashing: ALICE-001 (Track 11).bin
Hashing: ALICE-001 (Track 12).bin
Hashing: ALICE-001 (Track 13).bin
EndTime: 2023-05-30T21:42:22+0900

[ALICE-001.zip](https://github.com/saramibreak/DiscImageCreator/files/11600036/ALICE-001.zip)

**Comment by Lutepatious** [comment]
Solved.

D:\audio\ALICE-001>D:\DiscImageCreator_test\Release_ANSI\DiscImageCreator cd E ALICE-001 48 /c2 /s 2
AppVersion
        32 bit, AnsiBuild, 20230530T225943
/c2 val1 was omitted. set [4000]
/c2 val2 was omitted. set [0]
/c2 val3 was omitted. set [0]
valid extension was omitted. -> set .bin
CurrentDirectory
        D:\audio\ALICE-001
WorkingPath
         Argument: ALICE-001.bin
         FullPath: D:\audio\ALICE-001\ALICE-001.bin
            Drive: D:
        Directory: \audio\ALICE-001\
         Filename: ALICE-001
        Extension: .bin
StartTime: 2023-05-31T06:55:29+0900
Set the drive speed: 0KB/sec
DiskSize of [D:\audio\ALICE-001]
        Total:  4000650883072 bytes
         Used:  1803572170752 bytes
        ---------------------------
        Space:  2197078712320 bytes
         => There is enough disk space for dumping
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 1]
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 2]
This drive (DVDR   PX-760A   1.07 08/18/07  15:10     ) supports [OpCode: 0xd8, SubCode: 8]
Checking SubQ adr (Track) 13/13
Creating (Track AA).bin & .sub (LBA)   164499/  164499
Searching last non-zero byte (size)      0/235080
        There is not non-zero byte in the (Track AA)
Creating (Track 00).bin & .sub, (Track 01)(-LBA).bin & .sub (LBA)    -7830/  -10000
        There is non-zero byte in the (Track 01)(-LBA): -2088 byte => -522 sample
        Last non-zero byte before (Track AA): -178489 byte => -44622 sample
Checking SubRtoW (Track) 13/13
Set OpCode: 0xd8, SubCode: 8(Raw)
Checking SubQ ctl (Track) 13/13
Creating .scm (LBA) 164400/164400
No C2 errors
Moving .scm to .img
Creating cue and ccd (Track) 13/13
Creating bin (Track) 13/13
Creating (Track all).img
Hashing: ALICE-001.img
Hashing: ALICE-001 (Track 01).bin
Hashing: ALICE-001 (Track 02).bin
Hashing: ALICE-001 (Track 03).bin
Hashing: ALICE-001 (Track 04).bin
Hashing: ALICE-001 (Track 05).bin
Hashing: ALICE-001 (Track 06).bin
Hashing: ALICE-001 (Track 07).bin
Hashing: ALICE-001 (Track 08).bin
Hashing: ALICE-001 (Track 09).bin
Hashing: ALICE-001 (Track 10).bin
Hashing: ALICE-001 (Track 11).bin
Hashing: ALICE-001 (Track 12).bin
Hashing: ALICE-001 (Track 13).bin
EndTime: 2023-05-31T07:01:55+0900

[ALICE-001.zip](https://github.com/saramibreak/DiscImageCreator/files/11606453/ALICE-001.zip)
