### ISSUE TITLE
Failed to read [F:ConvertScmToBin] when dumping software CD

### ISSUE THREAD

**Issue by OldMadMan** [saramibreak/DiscImageCreator#216]
When dumping a Microsoft MSDN Subscription CD, DIC reports an error, Failed to read [F:ConvertScmToBin][L:2444].

I used DIC version 20230606T110637, and the command I used to dump disc is: 

cd G EXPTB3EN.bin 24 /d8 /c2 1000 /q /ns /s 2

**Comment by saramibreak** [comment]
Please report the issue using "Bug report" from "New Issue".
