### ISSUE TITLE
(repost)"Failed to read [F:ConvertScmToBin]" when dumping CD

### ISSUE THREAD

**Issue by OldMadMan** [saramibreak/DiscImageCreator#217]
**Version**
32 bit, AnsiBuild, 20230606T110637

**Describe the bug**
When dumping Microsoft software CD, DIC says "Failed to read [F:ConvertScmToBin][L:xxxx]", xxxx could be different number each time I dump.

However, the entire dump process can be completed. I'm not sure if this error message has any real impact.

My ODD is Plextor PX-755SA.

**Screenshots**
cd G ERMSXVOL_EN.bin 72 /d8 /c2 1000 /q /ns /s 2

![111](https://github.com/saramibreak/DiscImageCreator/assets/87818252/4667e60b-355c-47f4-af20-f348f8c5b377)

**Disc title**
Windows Server 2003 Standard Edition

**Disc ringcode**
N/A

**URL**
N/A

**Log file**
[Download Here](https://mega.nz/file/jUkUUa7Q#i9lih0t6ZZ7GIgaS5QkQwG5f66Jc9Z3M6QMy6LcUc5c)

Thank you.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11684220/DiscImageCreator_test.zip)
 - changed: (Track AA).scm filesize

**Comment by OldMadMan** [comment]
Thank you very much, I've dumped some CDs, the problem seems has been solved.

**Comment by OldMadMan** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11684220/DiscImageCreator_test.zip)
> 
> * changed: (Track AA).scm filesize


Sorry to bother you again, I recently meet the same problem again, which shows "Failed to read [F:ConvertScmToBin][L:2444]" when dumping Windows NT Disc.

I noticed that this problem seems to be related to the file size of (Track AA).scm, I've dumped some discs with the newer version of DIC you gave, no problems until just now I had the same problem again. I wonder if this means that the file size of TrackAA.scm needs to be further increased? Thank you so much.

**Comment by saramibreak** [comment]
Would you upload all logs and (Track AA).scm?

**Comment by OldMadMan** [comment]
> Would you upload all logs and (Track AA).scm?

Here are the logs, [Download](https://mega.nz/file/uYcUgCCD#JkHkhVMmWDBh5dkKtZ_p_jt1xUJ1nh2Pu6sb9U90PIo)

Sorry but TrackAA.scm seems did not be created by DIC during dump.

Thank you.

**Comment by OldMadMan** [comment]
[NTWKS351 (Track AA).zip](https://github.com/saramibreak/DiscImageCreator/files/12209373/NTWKS351.Track.AA.zip)
Here is TrackAA.scm .

**Comment by saramibreak** [comment]
Some changed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12209738/DiscImageCreator_test.zip)

**Comment by OldMadMan** [comment]
> Some changed. [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12209738/DiscImageCreator_test.zip)

I dumped again and still got the same problem, here are the logs:

[Download](https://mega.nz/file/uR9lwSpJ#zV644geq6ctc_w8kDjDxo-4NCFIgyimyG5XAxQ6pHRE)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12211644/DiscImageCreator_test.zip)
added log. (not fixed yet) Please upload all logs.

**Comment by OldMadMan** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12211644/DiscImageCreator_test.zip) added log. (not fixed yet) Please upload all logs.

This newest build stops my ODD from responding during the reading process:

Checking SubQ adr (Track)  1/ 1
[F:ReadCDOutOfRange][L:2761] GetLastError: 1117, This request cannot be performed due to an I/O device error.
Please wait for 25000 milliseconds until the device is returned
lpCmd: d8, 00, 00, 03, d8, aa, 00, 00, 00, 02, 02, 00
dwBufSize: 2448
can't read

So only a few files been generated, here are them

[nt.zip](https://github.com/saramibreak/DiscImageCreator/files/12214662/nt.zip)

**Comment by saramibreak** [comment]
> This newest build stops my ODD from responding during the reading process:

Sorry. Reuploaded.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12215857/DiscImageCreator_test.zip)

**Comment by OldMadMan** [comment]
> > This newest build stops my ODD from responding during the reading process:
> 
> Sorry. Reuploaded. [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12215857/DiscImageCreator_test.zip)

The problem seems to be solved temporarily. When I use this latest DIC to dump, the problem of reading failure no longer occurs. I still put the log below, maybe it can help you. Also, I'm going to try dump some other discs and see if the problem still occurs.

[logs](https://mega.nz/file/zJch3JJQ#aSyfrr6qwO4NXt46ir9S_6eu5LS0DiSCH3DUASmJX-A)

**Comment by saramibreak** [comment]
Thanks test, but subchannel is still buggy.
fixed: subchannel correction
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12229318/DiscImageCreator_test.zip)

**Comment by OldMadMan** [comment]
Thank you, I will test to dump some discs. I had previously dumped over a thousand CDs with older versions of DIC, but with the newer version, it looks like maybe I'll have to do the work again. Maybe I should wait until DIC releases a more stable version before starting ：）

**Comment by saramibreak** [comment]
> it looks like maybe I'll have to do the work again. Maybe I should wait until DIC releases a more stable version before starting

This problem is related to the lead-in/out file (e,g (Track 0).bin or (Track AA).bin)
If you only hope to dump the playable image (e.g. (Track 1).bin etc), no need to redump your a thousand CDs.

**Comment by OldMadMan** [comment]
When dumping a Hybrid CD (Data and Music on one CD) of Microsoft, I noticed DIC report like this:

Checking SubQ adr (Track) 30/30
Creating (Track AA).bin & .sub (LBA)   291494/  291494

        There is not non-zero byte in the (Track AA)
Creating (Track 00).scm & .sub, (Track 01)(-LBA).scm & .sub (LBA)    -7684/  -10000


Does the  "There is not non-zero byte in the (Track AA)" message mean that any errors occurred?

**Comment by saramibreak** [comment]
> Does the "There is not non-zero byte in the (Track AA)" message mean that any errors occurred?

No. Generally, lead-out sectors are zeroes, but sometimes non-zero byte exists. If you can use a binary editor, you can check it yourself.

**Comment by OldMadMan** [comment]
@saramibreak  Again, today when I dump a Windows NT DDK disc, DIC shows info like 
[F:ConvertScmToBin][L:2432] GetLastError: 2, system cannot find file specified.
DIC tried five times but all failed to get (Track 01)(-LBA).

Also, there is no C2 errors after dump, but DIC still shows [ERROR] Number of sector(s) where sync(0x00 - 0x0c) is invalid: 2. would this affect bin files it dumped?

Here are the logs and files, wish these would help, thank you :)

[logs.zip](https://github.com/saramibreak/DiscImageCreator/files/12706533/logs.zip)

**Comment by saramibreak** [comment]
> DIC tried five times but all failed to get (Track 01)(-LBA).

Reading of the minus lba area depends on the drive cache. Therefore, it may not read well. Currently, there is no way to completely solve the problem, and it can only be repeated until it succeeds.

> there is no C2 errors after dump, but DIC still shows [ERROR] Number of sector(s) where sync(0x00 - 0x0c) is invalid: 2. would this affect bin files it dumped?

It seems there is a sync in LBA 134823 and 134824.
```
LBA[134822, 0x20ea6], MSF[29:59:47], mode 1
LBA[656308, 0xa03b4], MSF[df:4c:58], invalid sync
LBA[656308, 0xa03b4], MSF[df:4c:58], invalid sync
LBA[134825, 0x20ea9], MSF[00:00:00], zero sync (pregap)
```

But these are audio sector.
```
LBA[134822, 0x20ea6]: P[00], Q[410102295747002959479925]{ Data,      Copy NG,                  Track[01], Idx[02], RMSF[29:57:47], AMSF[29:59:47]}, RtoW[0, 0, 0, 0]
LBA[134823, 0x20ea7]: P[00], Q[01020000017400295948e241]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[02], Idx[00], RMSF[00:01:74], AMSF[29:59:48]}, RtoW[0, 0, 0, 0]
LBA[134824, 0x20ea8]: P[ff], Q[0102000001730029594995b4]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[02], Idx[00], RMSF[00:01:73], AMSF[29:59:49]}, RtoW[0, 0, 0, 0]
LBA[134825, 0x20ea9]: P[ff], Q[01020000017200295950bcfd]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[02], Idx[00], RMSF[00:01:72], AMSF[29:59:50]}, RtoW[0, 0, 0, 0]
```
There is no problem.
