### ISSUE TITLE
Generated Track0.bin data is inconsistent when dump the same CD twice

### ISSUE THREAD

**Issue by OldMadMan** [saramibreak/DiscImageCreator#218]
**Version**
32 bit, AnsiBuild, 20230608T140750

**Describe the bug**
I used the same command to dump the same CD twice, and the two Track0.bin files I got were not exactly the same, their sizes were inconsistent. Several other files (such as Track AA.bin) generated twice have the same content. Is this result normal?

**Screenshots**
cd G JA_C0251.bin 72 /d8 /c2 1000 /q /ns /s 2

**Disc title**
Microsoft TechNet Subscription Disc 0251

**Disc ringcode**
X11-11122

**URL**
N/A

**Log file**

[First time dump](https://mega.nz/file/uRtyQZrQ#Rg4ppfPsua2bSWLSOcDthM1Wqs6ubLUBhgX9ewU_oTI)
[Second time dump](https://mega.nz/file/Kcs2nTRT#h_2_TRY-gt9thpbV2eXoXT10TQP6CD2lZxgIzzxHxuo)

**Comment by saramibreak** [comment]
> Is this result normal?

Yes. Track 0.bin is dumped using a kind of cache command, so a range of the dumping is different every time.

**Comment by OldMadMan** [comment]
> Owner

Thank you very much, please allow me to ask one more small question, then I will close this issue myself. 

I have dumped over 1,000 Microsoft software CDs with various versions of DIC so far. Among the dump results, all CDs have some error written inside SubError.txt . Does this mean that all the CD are bad? Or has no real impact? Is there a disc in the world without suberror?

Thanks.

**Comment by saramibreak** [comment]
> no real impact?

Yes. Subchannel often reads error. This app fixes these errors.

> Is there a disc in the world without suberror?

No. Subchannel errors are to be expected for CD.
