### ISSUE TITLE
No new commits are seen in a log

### ISSUE THREAD

**Issue by sskras** [saramibreak/DiscImageCreator#22]
Hello,

several minutes ago I received an email notification about the [release 20181020](https://github.com/saramibreak/DiscImageCreator/releases/tag/20181020).  I am very interested in incremental changes of the source code, but sadly the [last commit](https://github.com/saramibreak/DiscImageCreator/commits/master) here is 595c083305f0e335cc0d9732561e777061c99dc7 circa 2018-08-28.

Is there a possibility that all related commits will arrive yet? : )

**Comment by saramibreak** [comment]
master branch is also updated now.

**Comment by sskras** [comment]
Thanks. 

Ah, all changes squashed into the single commit, OK.  Is there a possibility that you would push changes in smaller commits?
