### ISSUE TITLE
Weird C2 errors that corrupt the dump when repaired

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#220]
**Version**
I have latest version

**Describe the bug**
I reported this problem on the redump forum, then I thought that the problem concerns only one disc, today it turned out that there are more discs with this error. Namely, DIC reports strange, non-existent C2 errors on selected disc fragments, and when it fixes them, the dump is finally corrupted (ECCEDC reports errors). I noticed the problem on Settlers: Dziedzictwo Królów (Disc 1) and Max Game 5/2003. After checking the scm file, I noticed that the DIC for some reason replaces some sectors with 0x55 instead of trying to fix them. The problem occurs only in the LG BH16NS40 drive, in the PX-712A it is not. I did not notice this problem in the redumper application, only DIC behaves like this. Can I count on this bug to be fixed?
**Screenshots**
Paste command-line text.

**Disc title**
The Settlers: Dziedzictwo Królów (Disc 1) Original edition
Max Game 5/2003

**Disc ringcode**
All the string that is written the inner of the disc (IFPI etc.)

**URL**
Tell me the link to get the disc.
[Amazon](https://www.amazon.com/): 
[eBay](https://www.ebay.com/): 
[discogs](https://www.discogs.com/): 

**Log file**
https://mega.nz/file/omQxACwC#gh09rAsihSK9xP7yvZSLEG6qoWBRQHrO5Hf1BlbkJD0
https://mega.nz/file/5iAX0S6B#92GInFyo7IvXTQtuO0AuaA23bl9wamN7N_r1nKl7e8k
[MAX GAME 5_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/11910898/MAX.GAME.5_logs.zip)
[MAX GAME 5_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/11910892/MAX.GAME.5_logs.zip)

**Comment by saramibreak** [comment]
_The Settlers: Dziedzictwo Królów (Disc 1)_
Logs is not the latest (20230509 version)

_MAX_GAME_5/2003_
SCSI error occurs. App can't fix it. Try to change the disc and/or the drive.

```
LBA[131102, 0x2001e]: [F:ProcessReadCD][L:335]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT

LBA[131101, 0x2001d]: [F:ProcessReadCD][L:282]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
LBA[131101, 0x2001d]: Read error. padding [2352 bytes]
========== LBA[131101, 0x2001d]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 36 3C 3B CD 03 EC BA 5F  41 FE 80 12 0F 69 32 C7   6<;...._A....i2.

LBA[131102, 0x2001e]: [F:ProcessReadCD][L:282]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
LBA[131102, 0x2001e]: Read error. padding [2352 bytes]
========== LBA[131102, 0x2001e]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 36 3C 3B CD 03 EC BA 5F  41 FE 80 12 0F 69 32 C7   6<;...._A....i2.

LBA[131103, 0x2001f]: [F:ProcessReadCD][L:282]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
LBA[131103, 0x2001f]: Read error. padding [2352 bytes]
========== LBA[131103, 0x2001f]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 36 3C 3B CD 03 EC BA 5F  41 FE 80 12 0F 69 32 C7   6<;...._A....i2.

LBA[131104, 0x20020]: [F:ProcessReadCD][L:282]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
LBA[131104, 0x20020]: Read error. padding [2352 bytes]
========== LBA[131104, 0x20020]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 36 3C 3B CD 03 EC BA 5F  41 FE 80 12 0F 69 32 C7   6<;...._A....i2.
```

**Comment by MrPepka** [comment]
The Settlers: Dziedzictwo Królów (Disc 1)
Logs from latest version
[SHOK_PL_CD1_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/11915907/SHOK_PL_CD1_logs.zip)
Max Game 5/2003
I know there are SCSI errors, but the problem also applies to sectors where there are no SCSI errors

**Comment by saramibreak** [comment]
> The Settlers: Dziedzictwo Królów (Disc 1)

According to the _mainError.ext, the sync position often changes.
```
LBA[014155, 0x0374b]: Track[01]: Invalid sync. Skip descrambling
========== LBA[014155, 0x0374b]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
 :
04A0 : 6E 7B D4 E1 A4 35 7D 9A  A2 97 1B 66 60 31 F9 A4   n{...5}....f`1..
04B0 : 00 FF FF FF FF FF FF FF  FF FF FF 00 02 90 66 61   ..............fa
04C0 : 3B EC 6B FD 7A 0F F2 D6  64 A7 19 10 6C 33 E6 06   ;.k.z...d...l3..
```

```
LBA[014165, 0x03755]: Track[01]: Invalid sync. Skip descrambling
========== LBA[014165, 0x03755]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
 :
0480 : D7 3B 3B 22 A3 26 EF B5  01 C8 93 A3 1A FB F3 FA   .;;".&..........
0490 : 46 24 0E 28 58 5B F5 48  00 FF FF FF FF FF FF FF   F$.(X[.H........
04A0 : FF FF FF 00 02 91 01 61  DF E7 E7 E2 2A 4E 81 5C   .......a....*N.\
```

```
LBA[014354, 0x03812]: Track[01]: Invalid sync. Skip descrambling
========== LBA[014354, 0x03812]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0900 : 0D B7 56 A2 FE B8 01 B5  E8 60 19 46 DD DF 6F 19   ..V......`.F..o.
0910 : D8 3A 5E A0 8A 4D D0 C7  00 FF FF FF FF FF FF FF   .:^..M..........
0920 : FF FF FF 00 02 93 51 61  F6 D4 29 F1 BD 78 48 0F   ......Qa..)..xH.
```

This is another problem. I can't fix it now. If this problem occurs only LG BH16NS40, I recommend that change the drive for this disc.
