### ISSUE TITLE
DiscImageCreator can't dump RVT-R/NR with Plextors due to not knowing the end PSN from the PFI data

### ISSUE THREAD

**Issue by ehw** [saramibreak/DiscImageCreator#221]
**Version**
[20230606](https://github.com/saramibreak/DiscImageCreator/releases/tag/20230606)

**Describe the bug**
DiscImageCreator can dump commercial Wii/GC discs by using the READ BUFF command in DVD Plextor drives. This method also works for RVT-R and NR discs but there's a caveat.

Due to unknown reasons at the moment, the PFI data returned by the drive is incomplete. All drives have a hard time with the PFI data in any software. The possible reason for this is that the sector data that has the DMI/PFI data stored is scrambled with a unique algorithm that's not DVD standard, so it can't properly descramble all the parts of the PFI. 

The PFI contains the starting PSN (00030000) but not the ending PSN value. So DiscImageCreator doesn't know how big the NR/RVT-R discs are, which results in a "INVALID FIELD IN CDB" error. If you tell DiscImageCreator the size of the disc, bypassing the need of checking the PFI data, DIC will dump the discs just fine. So there needs to be an alternate solution to determine the size of NR/RVT-R discs.

A.) The first logical solution, which should be the standard solution for making raw dumps, is to descramble the raw DMI/PFI data returned from the cache itself.

When you execute the 0xAD 00 opcode (READ DVD STRUCTURE), the PFI data gets returned to the root of the drive's cache in DRAM. This data is scrambled with some algorithm, but just like other sectors, it has EDC that can be validated against. So since drives don't have a natural ability to descramble the PFI data of a RVT/NR disc, you can descramble the PFI data at the user level instead to determine the actual end sector size. To do this, you do the following:

 1.) User inserts the RVT-R/NR disc
 2.) DiscImageCreator runs the READ DVD STRUCTURE opcode
 3.) At the root of the cache, the first 0x810 or 0x950 bytes written is the PFI's raw scrambled data. Unscramble/bruteforce this data to get the right seed so that you can read the entire PFI data.
 4.) At 0x8 in the unscrambled PFI data is the end PSN value. 0x4 contains the start PSN value
 5.) Pass this off to DIC's read commands, and you should be able to return data.

The only problem with this solution is that DIC currently does the bruteforcing/unscrambling in a separate process. In this scenario, it assumes DIC can do some of the unscrambling itself. But this is the safest most reliable way to get the end PSN every time.

B.) Look at the unique string stored in the DMI. GC, Wii, RVT-R, and NR discs all have unique vendor strings stored in the DMI area at 0x10.

"Nintendo NNGC Emu. Disk"  <- RVT
"Nintendo Game Disk" <- Retail GameCube
"Nintendo NNGC Disk" <- Retail Wii
"Nintendo Emulation Disk" <- NR 

If the DMI matches one of the strings above, you can assume the start and end PSN. According to a valid dump of the PFI data, here are the starting and ending PSN numbers for Gamecube and Wii discs (both Retail and Dev):
Wii/RVT: Start PSN: 00030000, End PSN: 0026127F
GC/NR: Start PSN: 00030000, End PSN: 00DE0AF

There is an issue with this. Dual layer RVT-Rs can't be be dumped this way as the single layer and dual layer RVT-Rs use the same string in the DMI. So this isn't very reliable...

**Log file**
Here are the log files along with the DMI/PFI data as returned by a DVD Plextor for a NR and RVT disc.
[rvtr.zip](https://github.com/saramibreak/DiscImageCreator/files/11991357/rvtr.zip)
[nr.zip](https://github.com/saramibreak/DiscImageCreator/files/11991358/nr.zip)

**Comment by saramibreak** [comment]
> the DMI/PFI data as returned by a DVD Plextor for a NR and RVT disc.

How about non plextor drive? If possible, please upload all logs of the non plextor drive.

> Wii/RVT: Start PSN: 00030000, End PSN: 0026127F

Is it typo? My wii disc (single) have 0x26047f.
```
	StartingDataSector:  196608 (0x30000)
	     EndDataSector: 2491519 (0x26047f)
```

**Comment by ehw** [comment]
> > the DMI/PFI data as returned by a DVD Plextor for a NR and RVT disc.
> 
> How about non plextor drive? If possible, please upload all logs of the non plextor drive.

All the drives I've tested returned the PFI/DMI data this way. Plextors are the only drives that can read these discs without disc swapping, which I would assume would mess with the PFI/DMI data being returned. The only other drive that can read RVT-Rs and NR discs are RVT-R Writers, which are Matshita SW-9585-C drives flashed with special firmware that can descramble the RVT-Rs that use a nonstandard algorithm. This drive can return the PFI/DMI of the disc in full without anything missing. Check below for logs. The Matshita drives can read RVT-R and NR discs with Read12, but Plextors need to use READ BUFF. I haven't tested if the Matshita can do raw reads.

The only way for other drives to retrieve the PFI in full is to read the raw data that's returned onto the cache and bruteforce a seed to descramble it. I don't think drives can descramble it entirely by themselves.

> 
> > Wii/RVT: Start PSN: 00030000, End PSN: 0026127F
> 
> Is it typo? My wii disc (single) have 0x26047f.
> 
> ```
> 	StartingDataSector:  196608 (0x30000)
> 	     EndDataSector: 2491519 (0x26047f)
> ```

Not a typo, but something I actually overlooked. The EndDataSector is different for RVT-Rs in comparison to commercial discs. I didn't realize this. A single layer RVT-R returns 0x26127F as the end PSN. Commercial games return 0x26047F.

Here are some logs:
Sonic and the Secret Rings (Retail single layer Wii disc, completely dumped with a PX-760A with READ BUFF)
[Sonic and the Secret Rings (retail wii disc - raw dump with plextor).zip](https://github.com/saramibreak/DiscImageCreator/files/11994183/Sonic.and.the.Secret.Rings.retail.wii.disc.-.raw.dump.with.plextor.zip)

RVT-R disc dumped with a RVT-R Writer. This was dumped with normal DVD operations due to the firmware being made to handle these discs' scrambling algorithm.
[Muscle March Game Disc (rvt wii dev disc - normal dump with rvt writer).zip](https://github.com/saramibreak/DiscImageCreator/files/11994186/Muscle.March.Game.Disc.rvt.wii.dev.disc.-.normal.dump.with.rvt.writer.zip)

**Comment by ehw** [comment]
Here's a cache dump of what raw DMI/PFI data looks like from an RVT-R. The READ DVD STRUCTURE command was executed which put the DMI/PFI onto the cache. The cache was dumped using READ BUFF, and descrambled using unscrambler. The result, in the .iso, is what the data looks like. It consists of both the PFI and DMI in its entirety, which includes the end PSN too. The same drive didn't return all the data for the PFI when using the READ DVD STRUCTURE. It was only when descrambling the raw data from the cache that you could get everything:
[cache.zip](https://github.com/saramibreak/DiscImageCreator/files/11994199/cache.zip)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11994404/DiscImageCreator_test.zip)
- added: generate _PFI.raw

Please check the end PSN of your RVT-R. If it's 0, I use a fixed size (0x26127F) as a magic number.

**Comment by ehw** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11994404/DiscImageCreator_test.zip)
> 
> * added: generate _PFI.raw
> 
> Please check the end PSN of your RVT-R. If it's 0, I use a fixed size (0x26127F) as a magic number.

Doesn't seem like it worked, it read the first block (16 sectors) from the cache that was on the disc and not the PFI/DMI.
[issue 221 - raw pfi test 1.zip](https://github.com/saramibreak/DiscImageCreator/files/11994438/issue.221.-.raw.pfi.test.1.zip)

**Comment by saramibreak** [comment]
Retail disc can get it correctly.
[test.zip](https://github.com/saramibreak/DiscImageCreator/files/11994467/test.zip)

If RVT-R can't get it, I use a fixed size (0x26127F) as a magic number.

**Comment by ehw** [comment]
I think I found the issue. You need to put something on the cache first before you put the PFI/DMI on there with READ DVD STRUCTURE or else the data gets immediately replaced. You need to read from cache to get the PFI at a different point.

Try doing this:
1.) Read LBA 0, this gets LBA 0 onto the root of DRAM/Cache. 
a8 00 00 00 00 00 00 00 00 01 00 00

2.) Next, read format code 04 (return DMI. this will return PFI also because PFI and DMI are part of the same 'block'. drives return things onto the cache by block)
ad 00 00 00 00 00 00 04 00 04 00 00

3.) Part of the lead in area is now in cache, now you can read it with 3C 02 00:
3c 02 00 00 00 00 00 08 10 00

Received 2064 bytes of data:
 00     04 02 f2 00 86 72 00 00  00 00 00 00 24 af 35 46    .....r......$.5F
 10     86 5e c7 03 6e 4d 03 cb  15 ea 96 87 fd f0 45 e8    .^..nM........E.
 20     36 d6 b7 7b 81 87 33 e8  1a d3 6f cb 26 f0 6d a7    6..{..3...o.&.m.
 30     51 86 6c 3b 54 5c 23 3c  21 fc 7c 77 76 00 2c 05    Q.l;T\#<!.|wv.,.
 40     d8 b0 a7 75 a0 5f 4b 57  fc 50 72 ae b0 8b 70 78    ...u._KW.Pr...px
 50     ef ec 22 5c 0f 39 f9 4c  db 02 d6 5f 67 52 24 e0    .."\.9.L..._gR$.
 60     d5 db 10 d4 3b 2f 13 bc  50 f2 bf b2 89 34 34 ee    ....;/..P....44.
 70     f4 03 68 6b dd ac 0e d9  c6 8b 5c 7d 37 5c 85 29    ..hk......\}7\.)

Unscrambler needs 16 sectors worth of data to unscramble. 

Here's the output data:
The raw data looks like raw_pfi_dmi.bin when stored onto the cache. The data looks like raw_pfi_dmi.iso when successfully unscrambled (it used seed 00d0 for us).

[raw_pfi_dmi.zip](https://github.com/saramibreak/DiscImageCreator/files/11994472/raw_pfi_dmi.zip)

**Comment by saramibreak** [comment]
> Try doing this

I implemented below in test version.
1) read format code 00
2) read cache (3C 02 00)
3) got 16 blocks with PFI and DMI

> This for some reason is not part of the PFI data returned directly with 0xAD.

Please try sg_raw using 0xAD to check the end PSN.

**Comment by ehw** [comment]
> > Try doing this
> 
> I implemented below in test version.
> 
> 1. read format code 00
> 2. read cache (3C 02 00)
> 3. got 16 blocks with PFI and DMI

Ah I see, using format code 00 doesn't pull the data from the disc, it pulls it straight from various parts of RAM it seems. It's immediately returned when you run it. Using format code 04 for some reason makes the Plextor read from the disc, storing the data that's read onto the cache.

Can you make a new test version with format code 04 instead? That might do it.

The one thing to note, RVT-Rs and NR discs are not like commercial Wii/GC discs at all. For some reason, there are drives that can read commercial discs fine but almost all drives have a problem with the PFI of RVT-R and NR. So even though retail discs work for you with format code 00, having a RVT-R or NR in the drive might make the drive do different things.

> > This for some reason is not part of the PFI data returned directly with 0xAD.
> 
> Please try sg_raw using 0xAD to check the end PSN.

Using "ad 00 00 00 00 00 00 00 00 0F 00 00":
08 02 00 00 25 00 02 00  00 03 00 00 00 00 00 00    ....%...........

Start PSN is defined, but not End PSN. This is seen in the PFI.bin as well.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11994614/DiscImageCreator_test.zip)

According to your _rvtr.zip_, "FormatCode: 04 failed" occurs. I implemented to generate _PFI.raw after this message.

**Comment by ehw** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11994614/DiscImageCreator_test.zip)
> 
> According to your _rvtr.zip_, "FormatCode: 04 failed" occurs. I implemented to generate _PFI.raw after this message.

Yep, that did it:
[test5.zip](https://github.com/saramibreak/DiscImageCreator/files/11994645/test5.zip)

I didn't unscramble it but it's definitely a perfect match from our manual dump.

So you just have to unscsramble this and use the last psn value and DIC should be able to read RVT-Rs and NRs.

BTW, just as a reference:
![image](https://github.com/saramibreak/DiscImageCreator/assets/885618/abc04063-2d3c-4648-b519-d8a73f1ed5a2)

The left file is the RVT-R's raw PFI/DMI data that's still scrambled. The right is the raw PFI/DMI data from a blank DVD-R. There is almost no similarity between them despite carrying a lot of the same data when unscrambled. This proves that the scrambling algorithm for RVT-Rs and NRs is different and isn't the DVD standard.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11994924/DiscImageCreator_test.zip)

changed: _PFI.raw to _CDZ.raw (CDZ is ControlDataZone)

I don't NR and RVT-R, so test please.

**Comment by ehw** [comment]
Good work! We're almost there...

[test6.zip](https://github.com/saramibreak/DiscImageCreator/files/11995548/test6.zip)

So the drive read the raw CDZ and unscrambled it successfully, and it seems like it did apply the correct end LBA to start dumping (if you got this far?). But when it tried to read the disc it returned a L-EC error and quit. This might be because DIC didn't detect the disc as Gamecube/Wii and so instead of ignoring the L-EC errors, it quit on the first one?

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11995758/DiscImageCreator_test.zip)

added: RVT_SL_SIZE
```
BOOL IsNintendoDisc(
	PDISC pDisc
) {
	if (pDisc->SCSI.nAllLength == GAMECUBE_SIZE ||
		pDisc->SCSI.nAllLength == WII_SL_SIZE ||
		pDisc->SCSI.nAllLength == RVT_SL_SIZE ||
		pDisc->SCSI.nAllLength == WII_DL_SIZE) {
		return TRUE;
	}
	return FALSE;
}
```

> can you output a log file when unscrambler is run like inputfilename_unscramble.txt? I noticed the unscrambler verbose isn't recorded anywhere.

added: output .txt using redirect

**Comment by ehw** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11995758/DiscImageCreator_test.zip)
> 
> added: RVT_SL_SIZE
> 
> ```
> BOOL IsNintendoDisc(
> 	PDISC pDisc
> ) {
> 	if (pDisc->SCSI.nAllLength == GAMECUBE_SIZE ||
> 		pDisc->SCSI.nAllLength == WII_SL_SIZE ||
> 		pDisc->SCSI.nAllLength == RVT_SL_SIZE ||
> 		pDisc->SCSI.nAllLength == WII_DL_SIZE) {
> 		return TRUE;
> 	}
> 	return FALSE;
> }
> ```
> 
> > can you output a log file when unscrambler is run like inputfilename_unscramble.txt? I noticed the unscrambler verbose isn't recorded anywhere.
> 
> added: output .txt using redirect

Almost there!

RVT-Rs are working now. :)
[test8 - rvtr working.zip](https://github.com/saramibreak/DiscImageCreator/files/11995899/test8.-.rvtr.working.zip)

NR discs aren't. It looks like a similar issue from before.
[test9 - nr fail.zip](https://github.com/saramibreak/DiscImageCreator/files/11995897/test9.-.nr.fail.zip)
The end PSN for NR discs is 000DEEAF.

I'll recheck retail in a bit.

**Comment by ehw** [comment]
Side note. I don't have a RVT-DL on hand but I know someone that does. 

The end PSN for a RVT-DL should be 0042A7BF.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11997569/DiscImageCreator_test.zip)
added: NR_SIZE, RVT_DL_SIZE

**Comment by ehw** [comment]
> [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11997569/DiscImageCreator_test.zip) added: NR_SIZE, RVT_DL_SIZE

RVT-R and NR are dumping now. :)
[nr and rvt good.zip](https://github.com/saramibreak/DiscImageCreator/files/12001863/nr.and.rvt.good.zip)


Feel free to merge and close.

BTW, have you looked into how you might be able to speed things up with dumping Wii/GC with Plextor? We were thinking messing with the READ error page 01h with the MODE SELECT command might help make it work.

**Comment by ehw** [comment]
> > BTW, have you looked into how you might be able to speed things up with dumping Wii/GC with Plextor?
> 
> No.
> 
> > We were thinking messing with the READ error page 01h with the MODE SELECT command might help make it work.
> 
> You can see mmc3r10g.pdf p.291 for more information.

Looked at it a little bit, doesn't seem to help. I believe we were able to turn off ECC correction and enable streaming mode but no change in behavior at all. It's possible that one of the drive's processing functions are slowing it down and not anything mechanic per se. Might need more of a firmware patch at this point unless you have some theories...

Anyway, thanks for fixing the bug. :)
