### ISSUE TITLE
Varying Errors Imaging old Macintosh disc

### ISSUE THREAD

**Issue by genekellyjr** [saramibreak/DiscImageCreator#226]
**Version**
AppVersion - 32 bit, AnsiBuild, 20230606T110637

**Describe the bug**
I am trying to image an old Macintosh disc (Operation: Weather Disaster). I get two different types of errors depending on the two drives I have.

I am using this call:
`C:\Utilities\DiscImageCreator\DiscImageCreator.exe cd F "E:\Game Installers\Operation Weather Disaster\Operation Weather Disaster.iso" 16`

The errors are as follows:

**PIONEER BD-RW BDR-209D 1.34-ID61 (F:) (SATA) Platform RS8600**

This drive (BD-RW   BDR-209D 1.34  16/04/25  PIONEER  ) can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 1]
Failed to get write-offset
This drive (BD-RW   BDR-209D 1.34  16/04/25  PIONEER  ) can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 2]
LBA[000000, 0000000]: [F:ExecSearchingOffset][L:196]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
lpCmd: be, 04, 00, 00, 00, 00, 00, 00, 01, f8, 04, 00
dwBufSize: 2448
This drive (BD-RW   BDR-209D 1.34  16/04/25  PIONEER  ) can't read data sectors at scrambled state [OpCode: 0xbe, C2flag: 0, SubCode: 4]

**HL-DT-ST BD-RE WH16NS60 1.02 (D:) (SATA) Platform MT1959 - Patched**

LBA[302310, 0x49ce6]: [F:ReadCDForCheckingReadInOut][L:859]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, 04, 00, 04, 9c, e6, 00, 00, 01, f8, 00, 00
dwBufSize: 2352
This drive can't read the lead-out

**ImgBurn info**

TOC Information:
Session 1... (LBA: 0 / 00:02:00)
-> Track 01  (Mode 1, LBA: 0 / 00:02:00)
-> LeadOut  (LBA: 302310 / 67:12:60)

Track Information:
Session 1...
-> Track 01 (LTSA: 0, LTS: 302310, LRA: 0)

ImgBurn can almost read it but errors on two sectors (302159 and 302160 of 302310 total sectors) on both drives. The resulting .ISO is not mountable via Windows but 7zip can open it and it gives an error "MacOS.hfs - Cannot open the file as [HFS] archive" then I guess manages to open it and shows a MacOS.hfs file and a PartitionMap.Apple_partition_map file. I have a feeling that the disc is OK - it looks good, but maybe the format being just a HFS file system dump is tripping it up?

**Disc title**
Operation: Weather Disaster Macintosh CD-ROM published 1996

**Disc ringcode**
H311113-1

JVC 466-011

**Log file**
https://files.catbox.moe/xys1mt.7z <- 7zip file with outputs from both drives

**Comment by saramibreak** [comment]
> BD-RW BDR-209D 1.34 16/04/25 PIONEER

This drive can't support when CD is dumped.

> HL-DT-ST BD-RE WH16NS60 1.02

[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12463028/DiscImageCreator_test.zip)
Added it as 0xF1 drive. Try to dump plz.

**Comment by saramibreak** [comment]
According to this site (http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility#Recommended_Non-Plextor_ODDs), WH16NS60 1.00 is supported. But Unfortunately, it seems 1.02 is not supported.

**Comment by saramibreak** [comment]
> the drive is actually a WH16NS40 that was flashed to be a WH16NS60

If you re-flash to a WH16NS40, the drive may be able to read the lead-out.

> Is there a work-around to tell the program where the "lead-out" is (sorry, I do not know what the "lead-out" actually is on a disc)?

Not all drives can read the lead-out.

If you are interested in the specification of the CD-ROM, you can see ecma-130.
https://www.ecma-international.org/publications-and-standards/standards/ecma-130/

**Comment by saramibreak** [comment]
> I'll let you know if it finishes, it will take an extremely long time

It's weird. If you have other disc, try to dump it.

> how can other programs get by the drive not actually being able to read the lead-out?

ImgBurn doesn't read the lead-out, but your disc is a single data track. In most cases, a single data track disc generates the same binary without reading the lead-out. For more information, you can see _Drives and Features_ of this document. (https://dbpoweramp.com/spoons-audio-guide-cd-ripping.htm) Keywords are "offset" and "Over-reading".

**Comment by saramibreak** [comment]
> It got close, but it did not finish successfully.

Would you upload all logs?

**Comment by saramibreak** [comment]
Try to use /c2 like
```
DiscImageCreator.exe cd D "E:\dump\Operation Weather Disaster.iso" 16 /mr 50 /c2
```
