### ISSUE TITLE
Discs with 6-second index 02

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#229]
**Version**
20230606

**Describe the bug**
I have a case of a CD that displays C2 errors on sectors 300-307 and 320-327. This disc has a index 02 of as long as 6 seconds, and the sectors with C2 errors do not have any files (this is what CDMage claims), which leads us to assume that these errors are in the index 01. Could these be mastering errors or unidentified protection?

**Screenshots**
Paste command-line text.

**Disc title**
Liga Polska Manager 2000

**Disc ringcode**
All the string that is written the inner of the disc (IFPI etc.)

**URL**
Tell me the link to get the disc.
[Amazon](https://www.amazon.com/): 
[eBay](https://www.ebay.com/): 
[discogs](https://www.discogs.com/): 

**Log file**

[Liga_Polska_Manager_2000_Poland_logs-c2.zip](https://github.com/saramibreak/DiscImageCreator/files/12588022/Liga_Polska_Manager_2000_Poland_logs-c2.zip)
[Liga_Polska_Manager_2000_Poland_logs-no-c2.zip](https://github.com/saramibreak/DiscImageCreator/files/12588024/Liga_Polska_Manager_2000_Poland_logs-no-c2.zip)

**Comment by MrPepka** [comment]
Just in case, I am also posting logs from the latest version 20230909
[LPM2000_logs-no-c2.zip](https://github.com/saramibreak/DiscImageCreator/files/12588845/LPM2000_logs-no-c2.zip)
[LPM2000_logs-c2.zip](https://github.com/saramibreak/DiscImageCreator/files/12588846/LPM2000_logs-c2.zip)

**Comment by saramibreak** [comment]
> This disc has a index 02 of as long as 6 seconds

LBA 450 to 525. It seems it's intentional.

> the sectors with C2 errors do not have any files (this is what CDMage claims), which leads us to assume that these errors are in the index 01

LBA 299 to 1498 are mode 2 but no EDC (Other sectors are mode 2 form 1). It seems it's also intentional.

> Could these be mastering errors or unidentified protection?

I'm not sure but it may be a protection.
Protection list is here -> https://www.cdmediaworld.com/hardware/cdrom/cd_protections.shtml

Or  "A-Ray Scanner", which is copy protect detection tool, may be useful.

**Comment by MrPepka** [comment]
Hmm, it looks like neither A-Ray, ProtectionID nor BOS detects protection on this CD. Mastering errors?

**Comment by saramibreak** [comment]
> Liga Polska Manager 2000

Same publisher game list: https://www.mobygames.com/company/4673/marksoft/games/
Same developer game list: https://www.mobygames.com/company/20701/mgroup/games/

Maybe there is a title with the same protection( or error).

**Comment by CookiePLMonster** [comment]
No information on Liga Polska Manager '98:
<http://redump.org/disc/89785/>

**Comment by MrPepka** [comment]
I have a question. Does the /sk option allow skipping more than 2 sectors? If not, would you add such an option?

**Comment by saramibreak** [comment]
```
 LBA[000300, 0x0012c] Detected C2 error "00 F0 F0 F0 00 00 00 0F 0F 0F 00"
This error can't be fixed by plextor drive. Needs to dump it by non-plextor drive and replace it
```
Do you have ASUS/LG drive that can read the lead-out sector?

**Comment by MrPepka** [comment]
Unfortunately, my BW-16D1HT with firmware 3.10 modded by RibShark is also unable to read this sector and reports a C2 error in it

**Comment by MrPepka** [comment]
1. 
[LPM2000.zip](https://github.com/saramibreak/DiscImageCreator/files/13033807/LPM2000.zip)
2. I will try to test it on my BH16NS40

**Comment by MrPepka** [comment]
Logs from BH16NS40
[LPM2000 (LG).zip](https://github.com/saramibreak/DiscImageCreator/files/13034138/LPM2000.LG.zip)

**Comment by saramibreak** [comment]
3.10 and BH16NS40 output similar result.
LBA 300 ... 367 always output the same hash -> intentional error?
It seems that other sectors are real error.

This problem looks like "Eikan wa kimi ni 3" of the FM Towns. http://forum.redump.org/topic/32047/fm-towns-disc-c2-error/

**Comment by MrPepka** [comment]
What if it was possible to set the /sk option so that I could skip more than 2 sectors and that I could use this option to set 2 sector ranges (300-307 and 320-327) and I could dump these sectors in a drive that would somehow read them (at least and swapping disc method)?

**Comment by saramibreak** [comment]
300-307 and 320-327 are readable sectors. I'm not sure that these sectors are really protected, so I don't skip reading. /sk is used for unreadable sector (e.g. laserlock).

**Comment by MrPepka** [comment]
These sectors are probably not protected, but what I mean is that I want to dump the disc in DIC on Plextor, but skipping sectors 300-307 and 320-237. I want to read the sectors that I have indicated on another drive (GSA-H10N? H20N? Any drive that will read these sectors without errors) and then import them to the image created in DIC. Oh, that's right. While we're on the subject. The merge option you once implemented still works?
http://forum.redump.org/post/63837/#p63837

**Comment by saramibreak** [comment]
You dump the 300...307 and 320...327 sectors by any drive using date command.
```
DiscImageCreator.exe data <driveletter> 300to307.bin <drivespeed> 300 307
```
```
DiscImageCreator.exe data <driveletter> 320to327.bin <drivespeed> 320 327
```

And merge these files into "LPM2000".
```
DiscImageCreator.exe merge LPM2000.bin 300to307.bin
```
```
DiscImageCreator.exe merge LPM2000.bin 320to327.bin
```

As a result, 300...307 and 320...327 sectors with c2 error in LPM2000.bin are replaced by these non c2 error sectors.

**Comment by MrPepka** [comment]
Could you look at the logs from BW-16D1HT? It seems that this drive doesn't like it when a disc with audio tracks has C2 errors, we had a similar problem here - https://github.com/saramibreak/DiscImageCreator/issues/236#issuecomment-1791062390
[LPM2000 (ASUS).zip](https://github.com/saramibreak/DiscImageCreator/files/13271617/LPM2000.ASUS.zip)
