### ISSUE TITLE
DIC creates multiple .bin files for an Enhanced CD

### ISSUE THREAD

**Issue by Arthandas** [saramibreak/DiscImageCreator#230]
**Version**
MPF 2.6.3-b6ae390c

**Describe the bug**
I want to dump "Wiedźmin - Muzyka Do Filmu Marka Brodzkiego", I don't know what type of CD it is, I presume it's "enhanced CD" since it has both audio tracks and a music video (MPF doesn't automatically detect the type). The problem is DIC creates 23 bin files instead of a single bin+cue, which I prefer.

**URL**
https://www.discogs.com/release/13030522-Grzegorz-Ciechowski-Wied%C5%BAmin-Muzyka-Do-Filmu-Marka-Brodzkiego

**Log file**
[Wiedźmin - Muzyka Do Filmu Marka Brodzkiego [Arth]_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/12589501/Wiedzmin.-.Muzyka.Do.Filmu.Marka.Brodzkiego.Arth._logs.zip)

**Comment by MrPepka** [comment]
redump.org prefers the multi-bin format for audio CDs (hashes are calculated for each bin file). They can be combined into one bin using CDMage

**Comment by Arthandas** [comment]
I want to keep the number of used tools to a minimum, is there no way to force DIC to create a single bin?

**Comment by MrPepka** [comment]
DIC itself does not have this capability. As I have already mentioned, you can combine multiple bin files into one in CDMage, but DIC itself will not offer this option due to the need to calculate hashes for each bin file.

**Comment by saramibreak** [comment]
> is there no way to force DIC to create a single bin?

_.img_ and __img.cue_ are same as a single bin and cue.

**Comment by Arthandas** [comment]
How do you properly view the contents of a dumped disc like that one?
When I open the contents of the physical disc, all I see is track 23 "Wiedzmin.mpg" which is a music video.
When I mount the .cue in virtual drive, all I see are audio tracks 01-22.
<img width="780" alt="Image" src="https://github.com/saramibreak/DiscImageCreator/assets/41027064/d91207d8-fea2-4b12-8b01-fa52a1fc4779">
<img width="781" alt="Physical Disc" src="https://github.com/saramibreak/DiscImageCreator/assets/41027064/f1d27e2a-5b51-426c-9f17-285e5f1ec5e7">

**Comment by saramibreak** [comment]
> When I mount the .cue in virtual drive, all I see are audio tracks 01-22.

Try to mount .ccd

**Comment by Arthandas** [comment]
> Try to mount .ccd

There is no such thing, DIC produced bins, cue, img and scm.

**Comment by saramibreak** [comment]
> There is no such thing

It is in your uploaded "Wiedzmin.-.Muzyka.Do.Filmu.Marka.Brodzkiego.Arth._logs.zip"
```
Wiedźmin - Muzyka Do Filmu Marka Brodzkiego [Arth].ccd
```

**Comment by Arthandas** [comment]
You're right, I can't mount it though
<img width="828" alt="Untitled" src="https://github.com/saramibreak/DiscImageCreator/assets/41027064/e7ab1bee-aec8-4db3-9db1-a632c500917a">

**Comment by saramibreak** [comment]
Same message. https://forum.alcohol-soft.com/index.php?/topic/34894-problem-with-alcohol-emulation-core-message/
Anyway, it's not DIC problem.

**Comment by Arthandas** [comment]
I've never said it's DIC problem, I just asked how to properly view the disc's contents.
As for the post you linked, I'm not using any emulators nor AutoHotkey.
