### ISSUE TITLE
"LOGICAL BLOCK ADDRESS OUT OF RANGE" when checking exe

### ISSUE THREAD

**Issue by OldMadMan** [saramibreak/DiscImageCreator#231]
**Version**
32 bit, AnsiBuild, 20230909T161424

**Describe the bug**
During the process of checking exe, when DIC checks an exe, it prompts "ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE". But after this, the program can continue to run and detect other exes.

**Screenshots**
![Screenshot 2023-09-15 203842](https://github.com/saramibreak/DiscImageCreator/assets/87818252/be9898ac-a523-4df8-a5c0-c3fde8a9d58a)

**Disc title**
Microsoft Windows 2000 HCT

**Disc ringcode**
N/A

**URL**
N/A

**Log file**
Here are the log files, thank you.
[files](https://mega.nz/file/yVthHK5J#wAKKHm0eMnwL8Igu0fEQK_YFn1T042VZ5EdrFkACQF0)

**Comment by saramibreak** [comment]
"Location of Extent" and "Data Length" are corrupt.
```
		      Length of Directory Record: 46
		Extended Attribute Record Length: 0
		              Location of Extent: 1768515946
		                     Data Length: 0
		         Recording Date and Time: 1998-12-10T10:30:32+00:00
		                      File Flags: 0 (Visible, File, No Associated, No Record Format, No Owner/Group ID, Final Directory Record)
		                  File Unit Size: 0
		             Interleave Gap Size: 0
		          Volume Sequence Number: 1
		       Length of File Identifier: 13
		                 File Identifier: STRESS7.POP;1
FullPath: \HCT\IOSTRESS\I386\STRESS7.POP
```

Perhaps IsoBuster also can't access "STRESS7.POP".

**Comment by OldMadMan** [comment]
Um, so does it mean that on the "master CD", the "file size information" of this exe file is wrong? And does this error affect the file itself?

**Comment by saramibreak** [comment]
> "file size information" of this exe file is wrong?

Yes.

> does this error affect the file itself?

No.
