### ISSUE TITLE
Feature request: Skip copy protection/exe scanning

### ISSUE THREAD

**Issue by mrpijey** [saramibreak/DiscImageCreator#232]
**Is your feature request related to a problem? Please describe.**
Unnecessary scans of exe files when title is known to have no copy protection (mostly applicable to standard application discs)

**Describe the solution you'd like**
A flag to skip exe scanning or scanning for copy protection at all.

**Comment by MrPepka** [comment]
Just do not use /ns and /sf and then DIC will not scan exe files

**Comment by mrpijey** [comment]
Thank you, I was not using /sf, but I was using /ns and it was not clear from the included help that it would scan exe files.
