### ISSUE TITLE
LUN_NOT_READY when dump a data CD with audio tracks

### ISSUE THREAD

**Issue by OldMadMan** [saramibreak/DiscImageCreator#234]
**Version**
32 bit, AnsiBuild, 20230909T161424

**Describe the bug**
When using DIC to dump a Microsoft data CD containing multiple audio tracks, DIC reported continuous errors during the file check. The error content was showed in screenshot, like "SenseData Key-Asc-Ascq: 02-04-01 = NOT_READY - LUN_NOT_READY - BECOMING_READY".

I own three official copies of this disc, but no matter which one I try to dump, DIC reports the same error and is unable to complete the dump process.

What could be the cause of this? Is there any way to fix it? Thank you very much.

**Screenshots**
cd G NTDDK351.bin 48 /d8 /c2 1000 /q /ns /s 2
![999](https://github.com/saramibreak/DiscImageCreator/assets/87818252/c8c2f7a7-7e42-473c-9618-09e4e076ff5f)

**Disc title**
Windows NT Driver Development Kit

**Disc ringcode**
N/A

**URL**
N/A

**Log file**
Here are the logs:
[logs.zip](https://github.com/saramibreak/DiscImageCreator/files/12845106/logs.zip)

Thank you.

**Comment by saramibreak** [comment]
SizeOfRawData and below is broken. Perhaps it's a mastering issue. Without /ns, you can dump it to the end.
```
========== LBA[044098, 0x0ac42]: ML.EXE ==========

	========== IMAGE_SECTION_HEADER (40 bytes) ==========
	                Name: .data
	         VirtualSize: 00011f3c
	      VirtualAddress: 0004c000
	       SizeOfRawData: 20207265
	    PointerToRawData: 2d25203d
	PointerToRelocations: 0a783823
	PointerToLinenumbers: 00000000
	 NumberOfRelocations: 2020
	 NumberOfLinenumbers: 2020
	     Characteristics: 6f437670
```

**Comment by OldMadMan** [comment]
I found some tools like Alcohol120% can dump it without error, maybe those tools even do not check strictly like DIC.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/12858373/DiscImageCreator_test.zip)
added checking the LBA range

**Comment by OldMadMan** [comment]
Does this mean that DIC regards the above-mentioned problems as "ignorable errors that do not affect the content of the captured data" and thus hides the relevant error information?

**Comment by saramibreak** [comment]
> thus hides the relevant error information?

Not hide. It' logged to _mainError.txt

**Comment by OldMadMan** [comment]
Oh, I see info like "Import size is over the all sector size. Skip reading".

**Comment by saramibreak** [comment]
If the dump is finished, I want to commit the src and close the issue.

**Comment by OldMadMan** [comment]
> If the dump is finished, I want to commit the src and close the issue.

Okay, the dump is finished. Thank you :)
