### ISSUE TITLE
Can't dump disc with ringed protection on audio sectors

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#236]
**Version**
I have latest version
**Describe the bug**
I have a disc with ring protection. This wouldn't be surprising if it weren't for the fact that this protection is available both on the data track and on the audio track. DIC is therefore unable to start dumping the disc because it either hangs while checking tracks (PX-712A) or terminates after displaying reading errors (BW-16D1HT and BH16NS40). I was thinking about how to deal with this problem and the only thing that comes to my mind is to skip checking the tracks and some solution in which DIC detects ring protection on audio sectors and automatically zeroed them (or something like that, I assume that audio tracks with this protection are empty)

**Screenshots**
Paste command-line text.

**Disc title**
Emergency 2: The Ultimate Fight For Life

**Disc ringcode**
All the string that is written the inner of the disc (IFPI etc.)

**URL**
https://www.ebay.com/itm/134568169983

**Log file**

[Em2Deluxe (ASUS).zip](https://github.com/saramibreak/DiscImageCreator/files/13120606/Em2Deluxe.ASUS.zip)

**Comment by saramibreak** [comment]
Do you think there is the ring protection in starndard version?
https://www.amazon.de/Emergency-2-Ultimate-Fight-Life/dp/B0000696DU/

**Comment by MrPepka** [comment]
Hmm, it's hard to say (in Redump, the German versions of this game are only those included with newspapers), but it may be. If you buy this game, buy the basic version and the deluxe version because the deluxe version has confirmed ring protection

**Comment by MrPepka** [comment]
Question. Have you received the game yet?

**Comment by saramibreak** [comment]
As a result, I got standard version.

Some fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13237002/DiscImageCreator_test.zip)

**Comment by saramibreak** [comment]
It takes a long time to read the ringed area.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13276620/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
And you spoiled it even more xD
[Em2Deluxe (ASUS1).zip](https://github.com/saramibreak/DiscImageCreator/files/13280339/Em2Deluxe.ASUS1.zip)

**Comment by MrPepka** [comment]
I tried again and DIC started dumping the disc. Apparently the drive has hung up. When it's over, I'll let you know the results

**Comment by MrPepka** [comment]
Well, unfortunately, the fix didn't help
https://mega.nz/file/1rAjQSoa#50rPNhk6KB_UjXOpjIhiKsrVhS5H9IxWeGyNPTxenVM
