### ISSUE TITLE
Feature request: skipping rereading sectors when it's in range of intentional errors

### ISSUE THREAD

**Issue by thegawin** [saramibreak/DiscImageCreator#237]
**Is your feature request related to a problem? Please describe.**
I have one disc with constant reading problem, basically a sector my plextor cannot read even after thousand tries, the error is in range of safedisc, so this shouldn't be problem.

**Describe the solution you'd like**
Skip reading this sector (or sectors).

**Comment by saramibreak** [comment]
What protected disc are you dumping?

**Comment by thegawin** [comment]
The Sims Deluxe Edition

**Comment by MrPepka** [comment]
If you use /sf then C2 errors on SafeDisc sectors will be skipped and DIC will not re-read them. Unless otherwise, please send the logs

**Comment by thegawin** [comment]
I think I understand where problem is. When the initial scan fails to mark sectors of intentional errors due to "this error can't fixed by plextor", in later stage the plextor will be retrying to read safedisc sectors. (Seems like in logs later it rotates on 9 sectors)

Logs: 
[logs_sims.zip](https://github.com/saramibreak/DiscImageCreator/files/13462555/logs_sims.zip)

My idea how to deal with this would be option to mark remaining sectors as intentionally bad after x tries or allowing multiple reads for safedisc check.

**Comment by MrPepka** [comment]
With safedisc sectors, DIC worked correctly, i.e. it avoided C2 errors in these sectors (because they were intentional). The problem is the remaining sectors with unintentional C2 errors. Steps you can try are:
1. Test on another drive
2. Change the dumping speed
3. If the disc is dirty, it is worth cleaning it

**Comment by thegawin** [comment]
After further cleaning of some residue I was able to get disc dumped. @saramibreak Maybe different message of error would make easier to understand. Like for example: "It's not possible to get laser reflection from disc. Check for residue or damage to data layer (disc rot etc). "
