### ISSUE TITLE
Dumping error obviously because of subchannel data

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#240]
**Version**
32 bit, AnsiBuild, 20230909T161424

**Describe the bug**
This is a retry of dumping a problematic disc (Pokemon) from #70. There it was said:

> The last 150 sectors indicate "lead-out", not Track 15. It's irregular.
> ```
> LBA[220537, 0x35d79]: P[ff], Q[41aa0100000000490237f14f]{ Data,      Copy NG,                  LeadOut  , Idx[01], RMSF[00:00:00], AMSF[49:02:37]}, RtoW[0, 0, 0, 0]
> LBA[220538, 0x35d7a]: P[ff], Q[41aa0100000100490238aaf1]{ Data,      Copy NG,                  LeadOut  , Idx[01], RMSF[00:00:01], AMSF[49:02:38]}, RtoW[0, 0, 0, 0]
> LBA[220539, 0x35d7b]: P[ff], Q[41aa01000002004902395402]{ Data,      Copy NG,                  LeadOut  , Idx[01], RMSF[00:00:02], AMSF[49:02:39]}, RtoW[0, 0, 0, 0]
> ```
> For this reason, app can't get the correct data sector length. I have no idea now.

Now I gave it a try with the most current version. I still cannot dump the disc, but I am not sure, if it is still the exact problem. in the _subReadable.txt the sectors from above now don't tell LeadOut anymore:
```
LBA[220537, 0x35d79]: P[ff], Q[41aa0100000000490237f14f]{ Data,      Copy NG,                  Track[aa], Idx[01], RMSF[00:00:00], AMSF[49:02:37]}, RtoW[0, 0, 0, 0]
```

Please just close this issue, if it __is__ still the same problem and there isn't much one can do.

**Log file**
I put everything but the bin and scm files into this: 
[Pokemon.zip](https://github.com/saramibreak/DiscImageCreator/files/13202032/Pokemon.zip)
console.log contains everything that was written to the console (I shortened the sector reads between first and last with [...])

**Comment by saramibreak** [comment]
Track[aa] is LeadOut.

**Comment by Feathered-Serpent** [comment]
Ah, I wasn't sure about the naming concept for these special tracks.
Not sure if it might be a relief, but Redumper also cannot create a useful image with that disc. CloneCD it'll stay then for that one :) thx for looking!
