### ISSUE TITLE
Parsing PS3_DISC.SFB

### ISSUE THREAD

**Issue by tjanas** [saramibreak/DiscImageCreator#242]
**Is your feature request related to a problem? Please describe.**
PS3 compilation discs may have multiple PARAM.SFO files. Each of these contain their own serial number and version corresponding to a game on the disc. Currently, DiscImageCreator is only parsing one of these.

**Describe the solution you'd like**
Parse the [PS3_DISC.SFB](https://psdevwiki.com/ps3/PS3_DISC.SFB) file in the root of a PS3 disc.
In the _disc.log, capture the version, serial, etc values in PS3_DISC.SFB, as well as the those in each of the PARAM.SFO files

**Describe alternatives you've considered**
Manually inspect these files for compilation discs.

**Comment by saramibreak** [comment]
Added.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13256740/DiscImageCreator_test.zip)
