### ISSUE TITLE
The program copies a disc without the /c2 option very slowly when using the BW-16D1HT drive

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#243]
**Describe the bug**
When I rip a disc in the BW-16D1HT drive without the /c2 option, the ripping process is very slow, the drive then switches to 8x speed. I tried changing the ripping speed, but the program ignores this setting. It doesn't matter which disc I try to rip this way, they all behave the same. BW-16D1HT firmware error?

**Comment by saramibreak** [comment]
/c2 is used, subchannel uses raw mode (001b) by DIC. /c2 is not used, subchannel uses pack mode (100b) by DIC.

It seems BW-16D1HT does not support pack mode. Therefore subchannel is fixed per sector and ripping speed goes to slow.

```
========== OpCode[0xbe]: C2flag[0]: SubCode[4]: Check Drive + CD offset ==========
========== LBA[000000, 0000000]: Sub Channel ==========
	  +0 +1 +2 +3 +4 +5 +6 +7 +8 +9 +A +B
	P 00 00 00 00 00 00 00 00 00 00 00 00
	Q 00 00 00 00 00 00 00 00 00 00 00 00
	R 00 00 00 00 00 00 00 00 00 00 00 00
	S 00 00 00 00 00 00 00 00 00 00 00 00
	T 00 00 00 00 00 00 00 00 00 00 00 00
	U 00 00 00 00 00 00 00 00 00 00 00 00
	V 00 00 00 00 00 00 00 00 00 00 00 00
	W 00 00 00 00 00 00 00 00 00 00 00 00
SubQ is all zero... (BufLen: 2448)
```

**Comment by MrPepka** [comment]
Meh. This means that the firmware needs to be modified to make the drive copy the disc faster without /c2. Okay, I'll get tired somehow, thanks for the explanation

**Comment by saramibreak** [comment]
> This means that the firmware needs to be modified to make the drive copy the disc faster without /c2

No. If /c2 is not used, raw mode can be used, not pack mode.

**Comment by MrPepka** [comment]
How to use raw mode when /c2 is not used? Should I use the /be raw? command?

**Comment by saramibreak** [comment]
> Should I use the /be raw?

Yes, but it didn't work as I expected. Fixed it.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13308817/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Thanks, it works as it should

**Comment by MrPepka** [comment]
I reopen it, but it doesn't work as it should
[LPM2000 (ASUS).zip](https://github.com/saramibreak/DiscImageCreator/files/13311974/LPM2000.ASUS.zip)

**Comment by saramibreak** [comment]
> even though I used the /be raw option, DIC heavily uses Pack mode

LPM2000_20231109T224638.txt
```
cd G:\ LPM2000.bin 72 
```
It seems that /be is not used.

**Comment by MrPepka** [comment]
DIC not detecting the /be raw command was an MPF error, so I bypassed this frontend and ran DIC directly in CMD. Well, this /be raw command doesn't work as it should
![2023-11-10_19-26-09 476](https://github.com/saramibreak/DiscImageCreator/assets/38865931/413cd247-ff45-489e-bb8a-8bcd165af92b)
![2023-11-10_19-26-05 198](https://github.com/saramibreak/DiscImageCreator/assets/38865931/ffe36d38-7c6e-4298-bfcd-6649901eda53)

**Comment by saramibreak** [comment]
> /be raw command doesn't work as it should

Fixed it. And with /be, it will set _raw_ with or without /c2.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13325945/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Now I can finally confirm that it works, thanks
