### ISSUE TITLE
Corrupted MSF when I dump disc without /c2 with /be raw mode in BW-16D1HT

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#244]
**Describe the bug**
Thanks to the last fix, the /be command in DIC started working, but when I use it and do not use the /c2 command at the same time, practically all sectors in the dump are damaged, including those where DIC normally does not report any error. Among other things, the MSF, synchronization, etc. are damaged, and the scm file is not created. According to my observations, the problem appears only when the BW-16D1HT drive is used
**Log file**
[LPM2000 (ASUS).zip](https://github.com/saramibreak/DiscImageCreator/files/13326434/LPM2000.ASUS.zip)
<img width="587" alt="Zrzut ekranu 2023-11-11 214443" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/a1eb0d4c-e589-49e2-8278-a9f3d57a336e">

**Comment by saramibreak** [comment]
Sorry, more fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13326950/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Thanks. Well, it's almost good, there's still some improvement to be made
[LPM2000 (ASUS).zip](https://github.com/saramibreak/DiscImageCreator/files/13327990/LPM2000.ASUS.zip)

**Comment by saramibreak** [comment]
Some changed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13328183/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Still bugged
[LPM2000 (ASUS).zip](https://github.com/saramibreak/DiscImageCreator/files/13328258/LPM2000.ASUS.zip)

**Comment by saramibreak** [comment]
Which point is the bug? It seems that LBA 340 ... 347 are intentional or real error.
```
LBA[000340, 0x00154]: Track[01]: Invalid sync. Skip descrambling
========== LBA[000340, 0x00154]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 00 FF FF FF 7F FF FF FF  FF FF FF 00 FF 13 40 62   ..............@b
```

**Comment by MrPepka** [comment]
The synchronization of 8 sectors is broken (see the file ending in .img_eccedc.txt)

**Comment by saramibreak** [comment]
Yes, it's not the app problem.

**Comment by MrPepka** [comment]
So what causes this error? When I dump the disc with the /c2 option, there are no C2 errors on sectors with broken sync, also when I dump this disc on Plextor without /c2, there are no broken sync errors

**Comment by saramibreak** [comment]
I'm not sure but one thing I can say is ASUS can't dump these sectors if it's not the cause of the disc.

**Comment by MrPepka** [comment]
APPROX. So I leave it as it is and close the ticket. Thanks again for your help
