### ISSUE TITLE
INVALID FIELD IN CDB in SOHD-167T in data mode

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#245]
**Describe the bug**
An attempt to copy specific sectors in SOHD-167T in data mode results in the message "INVALID FIELD IN CDB". I can copy the same sectors in data mode in another drive. Do you have any idea what is causing this bug?

**Screenshots**

<img width="616" alt="Zrzut ekranu 2023-11-13 162716" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/e1220366-0a69-4073-aadb-b10bc9c3f0d8">
<img width="612" alt="Zrzut ekranu 2023-11-13 162732" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/7a81a134-5025-4346-97ac-ea359ba3f8d9">
<img width="614" alt="Zrzut ekranu 2023-11-13 162742" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/6dfc9ffb-e35f-469f-b915-a21ef6710547">

**Log file**
[LPM2000 (Lite-On).zip](https://github.com/saramibreak/DiscImageCreator/files/13336326/LPM2000.Lite-On.zip)

**Comment by saramibreak** [comment]
Changed: When data is used, raw is used in subchannel, not pack.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13365916/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Thanks. I need one more fix to make this mode work properly
[LPM2000.zip](https://github.com/saramibreak/DiscImageCreator/files/13376009/LPM2000.zip)

**Comment by saramibreak** [comment]
Try to use audio, not data.

**Comment by MrPepka** [comment]
Doesn't work. Probably because the drive is not compatible with redump
<img width="597" alt="Zrzut ekranu 2023-11-16 142418" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/068d693b-99bd-45bb-a819-d9e364393ccb">

**Comment by saramibreak** [comment]
Some fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13392942/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Still glitched
<img width="615" alt="Zrzut ekranu 2023-11-17 161655" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/c3e644a2-8314-4e7f-bb2f-0dcea4b4de45">
<img width="610" alt="Zrzut ekranu 2023-11-17 161706" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/0cdee3d6-1139-4773-847c-9c3640896f30">

**Comment by saramibreak** [comment]
Changed: audio command does not search the offset.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13400242/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Still bad
<img width="614" alt="Zrzut ekranu 2023-11-18 141611" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/97b9896b-4664-43df-849b-bfb1f257a77c">
<img width="615" alt="Zrzut ekranu 2023-11-18 141622" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/41a12399-b76e-467e-b498-5ea117131f73">

**Comment by saramibreak** [comment]
Sorry for several test.
Added: check if drive supports the subchannel pack mode.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13400456/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Again
<img width="612" alt="Zrzut ekranu 2023-11-18 193112" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/560dc3b1-f17b-400d-926e-294edae3136d">

**Comment by saramibreak** [comment]
Some fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13402142/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
Again
<img width="613" alt="Zrzut ekranu 2023-11-19 143804" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/38129446-4596-4b9a-a654-43b517b311de">

**Comment by saramibreak** [comment]
What command is used? data? audio?

**Comment by MrPepka** [comment]
audio

**Comment by saramibreak** [comment]
Try to change the start sector to 21804.

**Comment by MrPepka** [comment]
Same
<img width="587" alt="Zrzut ekranu 2023-11-19 152132" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/58b9b0ba-286b-4903-add6-233b62bef5f7">

**Comment by saramibreak** [comment]
Added: check if scrambled reading is supported for non PLEXTOR and non LG/ASUS drive
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13403657/DiscImageCreator_test.zip)

**Comment by MrPepka** [comment]
It's finally working as it should. Thanks very much for all your help. I'm closing the ticket
