### ISSUE TITLE
SH-216BB freezes when I dump specific sectors in data mode

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#246]
**Describe the bug**
When I dump specific sectors from any disc in data mode, the SH-216BB drive hangs after some time. Sometimes it hangs, and sometimes it just hangs like that (DIC then displays a message about the semaphore timeout and stops working after some time). I can rip the disc on this drive in another program and the ripping will be successful, only in DIC such anomalies occur
**Log file**
[LPM2000.zip](https://github.com/saramibreak/DiscImageCreator/files/13338645/LPM2000.zip)

**Comment by MrPepka** [comment]
Up. I tried to test DIC with all the fixes from the SOHD-167T ticket and honestly it's worse because the 216BB drive doesn't even start dumping anymore (and I'm trying this time with the audio command) and immediately hangs up. Firmware bug?
<img width="615" alt="Zrzut ekranu 2023-11-19 170842" src="https://github.com/saramibreak/DiscImageCreator/assets/38865931/0aaa4aa1-e3aa-43cb-bd2c-2a5e10538074">

**Comment by saramibreak** [comment]
21654 ... 21657 was dumped?

**Comment by MrPepka** [comment]
No. Once the drive hangs, DIC stops working

**Comment by MrPepka** [comment]
Since I do not have documentation for this drive, and therefore I am not able to repair it sensibly at the firmware or software level (i.e. in DIC), I am closing the ticket
