### ISSUE TITLE
Cannot install with makefile on Linux

### ISSUE THREAD

**Issue by xiota** [saramibreak/DiscImageCreator#248]
**Version**
6d3b62c

**Describe the bug**
After successful make, attempting to install into an empty folder (`$pkgdir`) with the following command fails:
```
make DESTDIR="$pkgdir" PREFIX="/usr" install
```

The problem is the `install` command is missing the `-D` argument to allow it to create new directories.

https://github.com/saramibreak/DiscImageCreator/blob/6d3b62c1e2201091cff2b480203e3d7bde6a4690/DiscImageCreator/makefile#L104-L107

May also be worth adding quotes around the path variables, in case they contain spaces.
```
	install -Dm644 ../Release_ANSI/default.dat "$(DESTDIR)$(PREFIX)/share/$(TARGET)/default.dat"
	install -Dm644 ../Release_ANSI/driveOffset.txt "$(DESTDIR)$(PREFIX)/share/$(TARGET)/driveOffset.txt"
	install -Dm755 "$(TARGET)" "$(DESTDIR)$(PREFIX)/bin/$(TARGET)"
```

**Comment by saramibreak** [comment]
Could you test this makefile?
[makefile.zip](https://github.com/saramibreak/DiscImageCreator/files/13400288/makefile.zip)

**Comment by xiota** [comment]
> Could you test this makefile? [makefile.zip](https://github.com/saramibreak/DiscImageCreator/files/13400288/makefile.zip)

Works.

**Comment by xiota** [comment]
I must have made some mistake when testing before.  1b5f15288255e6cfc2b5848e3082eda5819119dd is not working.  From searching online, the tab character may be the cause.  Replacing with spaces seems to work.  (But somehow, replacing all tabs in the file with spaces produces errors elsewhere.)
```
make: Entering directory '/home/gs/xdg/Projects/aur-maintain-chaotic/discimagecreator-git.aur/src/discimagecreator/DiscImageCreator'
ifeq (Linux,Linux)
/bin/sh: -c: line 1: syntax error near unexpected token `Linux,Linux'
/bin/sh: -c: line 1: `ifeq (Linux,Linux)'
make: *** [makefile:105: install] Error 2
make: Leaving directory '/home/gs/xdg/Projects/aur-maintain-chaotic/discimagecreator-git.aur/src/discimagecreator/DiscImageCreator'
```

**Comment by saramibreak** [comment]
fixed: removed the tab character
[makefile.zip](https://github.com/saramibreak/DiscImageCreator/files/13432487/makefile.zip)

**Comment by xiota** [comment]
The last makefile didn't work.  I'm using a script that clones and builds the repo, and it's confusing to try to stop it midway to replace files.  So I made the following fork/branch with a working (on Linux) make file:

https://github.com/xiota/DiscImageCreator/tree/makefile

**Comment by saramibreak** [comment]
It's merged. (#251)
