### ISSUE TITLE
HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT error with CDs

### ISSUE THREAD

**Issue by Deranfan** [saramibreak/DiscImageCreator#254]
**Version**
20231201 via Media Preservation Frontend version 3.0.2 net 8.0 win x64 on windows 10

**Describe the bug**
I’m getting HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT error with the most recent version of DIC. I tested previous disks I successfully dumped, and the error also appears with them. This issue isn’t present with the 20230909 version. I managed to dump the disk with that version with no errors. This issue only appears with CDs, DVDs work with no problems.

**Drive Info**
BW-16D1HT with RipSharks firmware 3.10

**Screenshots**
```
Check if subchannel pack mode is supported
LBA[000000, 0000000]: [F:ReadCDForCheckingSubPack][L:1235]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
lpCmd: be, 00, 00, 00, 00, 00, 00, 00, 01, f8, 04, 00
dwBufSize: 2448
[WARNING] This drive does not support subchannel pack mode
```

**Disc title**
Casio Utilities CD - fx-9860G

**Disc ringcode**
Mastering Code: CDCSOG497A01A	C12072601
Mould SID Code: IFPI T116

**Log file**
[fx-9860G.zip](https://github.com/saramibreak/DiscImageCreator/files/13539083/fx-9860G.zip)

**Comment by saramibreak** [comment]
Fixed: fail to dump when LG/ASUS drive is used.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13539302/DiscImageCreator_test.zip)

> This issue isn’t present with the 20230909 version.

Yes. I added at 20231201.

**Comment by Deranfan** [comment]
I found a bug with the test version. While trying to dump Virtua Fighter 2 after reaching “Checking SubRtoW (Track)  1/24” I get an “HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT” error and then I got continuously “MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR” errors. This doesn’t happen with the 20230909 version, just like the bug I reported initially on this thread. 

**Drive Info**
BW-16D1HT with RipSharks firmware 3.10

**Screenshots**
```
LBA[000000, 0000000]: [F:ReadCDForCheckingSubPack][L:1236]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
lpCmd: be, 00, 00, 00, 00, 00, 00, 00, 01, f8, 04, 00
dwBufSize: 2448

LBA[144194, 0x23342]: [F:ReadCDForCheckingSubRtoW][L:1283]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
lpCmd: be, 00, 00, 02, 33, 42, 00, 00, 01, f8, 01, 00
dwBufSize: 2448
```

**Disc title**
Virtua Fighter 2, XPLOSIV version

**Disc ringcode**
Mastering Code: (kdg-NL) 01 EI 1305
Mastering SID Code: IFPI L371
Mould SID Code: IFPI 5599 

**Log file**
[SEGA_VF2.zip](https://github.com/saramibreak/DiscImageCreator/files/13583021/SEGA_VF2.zip)
The log files might be incomplete because I closed the cmd window before it finished on its own. The “MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR” errors seemed to be endless.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13583727/DiscImageCreator_test.zip)
changed: pack mode supported drive only checks SubRtoW.
fixed: fail to dump when mixed mode disc is dumped by LG/ASUS drive. (http://forum.redump.org/post/113592/#p113592)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13595655/DiscImageCreator_test.zip)
fixed: error occurs when checks adr by LG/ASUS drive. (http://forum.redump.org/post/113615/#p113615)
