### ISSUE TITLE
Issue dumping BD-Video disc - dumping with MATSHITA BD-MLT UJ260AF

### ISSUE THREAD

**Issue by rockleevk** [saramibreak/DiscImageCreator#256]
**Version**
[20231201](https://github.com/saramibreak/DiscImageCreator/releases/tag/20231201)

**Describe the bug**
DIC crashes after attempting to dump a BD disc.

**Screenshots**
`LBA[000000, 0000000]: [F:ReadDiscStructure][L:1589]
    Opcode: 0xad
    ScsiStatus: 0x02 = CHECK_CONDITION
    SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB`

**Disc title**
[DEARDROPS あそＢＤ](https://vndb.org/r27481)

**Disc ringcode**
`103402	ABBD-0017	PRESSED IN TAIWAN`
`IFPI L606`
`IFPI IC1Z`

**URL**
Tell me the link to get the disc.
[Amazon](https://www.amazon.co.jp/あそべる-BD-GAME-DEARDROPS-あそBD/dp/B00DIUCWG4/)

**Log file**
[ABBD-0017.zip](https://github.com/saramibreak/DiscImageCreator/files/13629496/ABBD-0017.zip)

**Comment by saramibreak** [comment]
fixed: fail to dump blu-ray disc except for PS3
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13639537/DiscImageCreator_test.zip)
