### ISSUE TITLE
The drive hangs when you try to dump a CD and gives the error "HARDWARE_ERROR - OTHER"

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#259]
**Version**
Use latest test version

**Describe the bug**
When I try to dump a CD, the drive often gives the error "HARDWARE_ERROR - OTHER" and then hangs. On earlier versions of DIC, dumping on my drive worked fine

**Screenshots**
Paste command-line text.

**Disc title**
Tell me the correct disc title.

**Disc ringcode**
All the string that is written the inner of the disc (IFPI etc.)

**URL**
Tell me the link to get the disc.
[Amazon](https://www.amazon.com/): 
[eBay](https://www.ebay.com/): 
[discogs](https://www.discogs.com/): 

**Log file*
[Kinder Extra 4.zip](https://github.com/saramibreak/DiscImageCreator/files/13762800/Kinder.Extra.4.zip)
*

**Comment by MrPepka** [comment]
After changing the speed it started working. However, I will leave a ticket if the problem returns (I forgot to mention, but the drive on which I noticed the problem is BH16NS40, firmware 1.03)

**Comment by saramibreak** [comment]
Does this occur only BH16NS40, firmware 1.03?

**Comment by MrPepka** [comment]
It seems that is right. I rarely use this drive, so I don't know from which build it doesn't work (although it happened only with one disc, maybe something went wrong with the cabling?)

**Comment by MrPepka** [comment]
Due to the fact that I do not often use the drive on which I noticed this problem, and the disc on which I noticed it is not in the best condition (despite regeneration), I am closing this ticket
