### ISSUE TITLE
Incorrect Enhanced CD data track

### ISSUE THREAD

**Issue by fuzz6001** [saramibreak/DiscImageCreator#260]
# Version
20231201

# Describe the bug
The data track on the Enhanced CD is not dumped correctly.

# Disc title
Akumajou Dracula MIDI Collection (Japan)
悪魔城ドラキュラ MIDIコレクション
KICA 7809

# Log files
[20230909](https://www.dropbox.com/scl/fi/bhzspyghxrsvytwhhtqje?rlkey=keb0z5xwqvonav4d8skbtjpf3)
[20231201](https://www.dropbox.com/scl/fi/a66ldtj9mr00zngabri0q?rlkey=es24delwrczqtvt03iiw42ja0)

The test version (20231212T031032) outputs the same hash as 20231201.

# 20230909 vs 20231201
![diff_track21](https://github.com/saramibreak/DiscImageCreator/assets/2080945/31b7855d-b777-4d38-8b6e-1301d58cffa2)

**Comment by saramibreak** [comment]
Uploaded test version.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13788041/DiscImageCreator_test.zip)

**Comment by fuzz6001** [comment]
It seems to be fixed.
Thank you as always. Have a Happy New Year!

[out.20231229.zip](https://github.com/saramibreak/DiscImageCreator/files/13790395/out.20231229.zip)
