### ISSUE TITLE
Incorrect UDF volume label

### ISSUE THREAD

**Issue by Deterous** [saramibreak/DiscImageCreator#264]
*_volDesc.txt currently shows the Volume Labels (Identifiers) from ISO9660 and Joliet filesystems.
It would be useful if DIC output the Volume Labels from other filesystems, such as UDF, HFS, High Sierra, Rock Ridge, etc

Example: A disc with both ISO and UDF partitions (e.g. http://redump.org/disc/77006/) shows up in Windows with the UDF volume label. ~~However this volume label is not mentioned anywhere in DIC logs/output.~~ However, the UDF label in the DIC logs is incorrect.

**Comment by saramibreak** [comment]
> It would be useful if DIC output the Volume Labels from other filesystems, such as UDF, HFS, High Sierra, Rock Ridge, etc

I dumped a DVD and confirmed the volume label.
```
========== LBA[000016, 0x00010]: Volume Descriptor ==========
	                       Volume Descriptor Type: 1
	                          Standard Identifier: CD001
	                    Volume Descriptor Version: 1
	                            System Identifier:                                 
	                            Volume Identifier: DVD_VIDEO                       
```

UDF
```
========== LBA[000032, 0x00020]: Primary Volume Descriptor ==========
	Descriptor Tag
		Tag Identifier: 1
		Descriptor Version: 2
		Tag Checksum: 222
		Tag Serial Number: 0
		Descriptor CRC: 2aa0
		Descriptor CRC Length: 496
		Tag Location: 32
	Volume Descriptor Sequence Number: 0
	Primary Volume Descriptor Number: 0
	Volume Identifier: DVD_VIDEO
```

> Example: A disc with both ISO and UDF partitions (e.g. http://redump.org/disc/77006/) shows up in Windows with the UDF volume label. However this volume label is not mentioned anywhere in DIC logs/output.

Could you upload logs?

**Comment by Deterous** [comment]
Ah, I see, UDF volume information is here:
```
========== LBA[000032, 0x00020]: Primary Volume Descriptor ==========
	Descriptor Tag
		Tag Identifier: 1
		Descriptor Version: 2
		Tag Checksum: 209
		Tag Serial Number: 1
		Descriptor CRC: 7b41
		Descriptor CRC Length: 496
		Tag Location: 32
	Volume Descriptor Sequence Number: 0
	Primary Volume Descriptor Number: 0
	Volume Identifier: 
```

Logs are not mine, but this is the example I used to look for the label:
[UDF Example.zip](https://github.com/saramibreak/DiscImageCreator/files/13926315/UDF.Example.zip)

Unfortunately the Label is just "" which is not the label that Windows sees when it mounts the disc.

**Comment by Deterous** [comment]
I have confirmed with ISOBuster that the disc with logs above has ISO9660 label "BRUTAL" and UDF label "brutal".
DIC, meanwhile, just outputs the non-printable character `` (ASCII 0x10, DLE) as the UDF volume identifier

**Comment by saramibreak** [comment]
fixed UDF log
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13951515/DiscImageCreator_test.zip)
