### ISSUE TITLE
Strange disc with SafeDisc

### ISSUE THREAD

**Issue by MrPepka** [saramibreak/DiscImageCreator#265]
**Describe the bug**
One of the dumpers (Lugamo) has a SafeDisc disc and there are 2 files protected by SafeDisc (00000001.TMP and 00000002.TMP). Both files have intentional errors, but when DIC finishes the dump, it tries to read the sectors from 00000002.TMP again, which ends in failure. Is it possible for DIC, in addition to the 00000001.TMP file, to also skip intentional errors from the second file 00000002.TMP?

**Disc title**
Fallen Lords: Condemnation

**Disc ringcode**
Data Side Mastering Code (laser branded/etched): DUPLICO 2000 FALLEN LORDS
Data Side Mastering SID Code: IFPI LT57
Data Side Mould SID Code: ifpi 8604
Barcode: 8 431474 055333

**Log file**
http://forum.redump.org/post/114274/#p114274

**Comment by saramibreak** [comment]
> http://forum.redump.org/post/114274/#p114274

I commented there.

**Comment by MrPepka** [comment]
I saw this one. Taking into account that the dumper had a damaged disc, I have no choice but to close the ticket
