### ISSUE TITLE
Discrepancy between DiscImageCreator and redumper in Cue with DCP

### ISSUE THREAD

**Issue by maxz** [saramibreak/DiscImageCreator#268]
I'm not sure whether I would really classify this as a bug, but it something that should be looked at and decided upon.

**Version**
20240101 on Linux.

**Describe the bug**
There is a discrepancy between the cue generated by DiscImageCreator and the cue generated by redumper. DIC sets the DCP flag on the audio tracks, Redumper does not. All other relevant information matches.

DIC seems to base its cue structure on the subchannel information while redumper bases it on the TOC by default.

@superg over in [this issue](https://github.com/superg/redumper/issues/121) on the redumper tracker states that it is the official redump.org stance to prefer the information in the TOC, so maybe DIC should prefer that as well or maybe it should remain as it is. I wanted to at least bring it up.

**Disc title**
[Computer Bild Spiele 8/2001](http://redump.org/disc/90797/) 

**Disc ringcode**
Outer mastering code: CSPR0020
Outer mastering SID: IFPI LL21	
Additional mould text (data side): 3

**Log files**
DiscImageCreator: [https://archive.org/download/redump.org-logs/TOMBRAIDER2 (DiscImageCreator).zip](https://archive.org/download/redump.org-logs/TOMBRAIDER2%20%28DiscImageCreator%29.zip)
Redumper: [https://archive.org/download/redump.org-logs/TOMBRAIDER2 (Redumper).zip](https://archive.org/download/redump.org-logs/TOMBRAIDER2%20%28Redumper%29.zip)

**Comment by saramibreak** [comment]
Thanks. I met the first time the control flag mismatched disc. I also prefer TOC and fix it by the next version.

**Comment by saramibreak** [comment]
Uploaded test  version.
http://forum.redump.org/post/115412/#p115412

**Comment by maxz** [comment]
The test version produces the correct `TOMBRAIDER2.cue` but additionally produces `TOMBRAIDER2 (Subs desync).cue` (which is equal to the cue file produced by the old version) and all bin files are also named `TOMBRAIDER2 (Subs desync) (Track 01).bin`, which leads to the entries in `TOMBRAIDER2.cue` being wrong (since the `TOMBRAIDER2 (Track 01).bin` and so on don't exist.) If you removed the `(Subs desync)` postfix from the bin files it would probably be correct.

**Log files**
DiscImageCreator: [https://archive.org/download/redump.org-logs/TOMBRAIDER2 (DiscImageCreator) (Test).zip](https://archive.org/download/redump.org-logs/TOMBRAIDER2%20%28DiscImageCreator%29%20%28Test%29.zip)
Redumper: [https://archive.org/download/redump.org-logs/TOMBRAIDER2 (Redumper).zip](https://archive.org/download/redump.org-logs/TOMBRAIDER2%20%28Redumper%29.zip)

**Comment by maxz** [comment]
I just dumped it again an rechecked. You are correct, the normal bins are also there and I somehow managed to overlook them. Everything should be fine then.
