### ISSUE TITLE
Recent versions generate a different hash than before

### ISSUE THREAD

**Issue by fuzz6001** [saramibreak/DiscImageCreator#269]
# Version
20240101

# Describe the bug
## 20230909
This matches the database.
```
<rom name="dump.bin" size="610757952" crc="368ff3f5" md5="bfd7991fc566236ebc04a3f50278a305" sha1="1a4c72c20a1b0b480f47f00c94615d4cc63ea24b" />
```

## 20240101, 20231201 and 20240224 (Test Version)
```
<rom name="dump.bin" size="610757952" crc="442e89ac" md5="873ad5416000ccd6806cf22b4676dc88" sha1="fb35f328b3cfff7e290e5ad96e3bb5ceb20fc6f0" />
```

# Disc title
Need for Speed: High Stakes (J)
http://redump.org/disc/100873/

# Log files
20230909 [nfshs_20230909.zip](https://github.com/saramibreak/DiscImageCreator/files/14433416/nfshs_20230909.zip)
20240101 [nfshs_20240101.zip](https://github.com/saramibreak/DiscImageCreator/files/14433497/nfshs_20240101.zip)

# Comparison
LBA 259674
![nfshs_diff](https://github.com/saramibreak/DiscImageCreator/assets/2080945/1e8a650b-f34e-4863-babe-7c90a0e64345)

**Comment by saramibreak** [comment]
mode is invalid (0xe1). I'll support again using new option to descramble the invalid mode sector.

By the way, LBA 259674 can be read without error by the general dumping tool (isobuster, clonecd etc.)?

**Comment by fuzz6001** [comment]
> By the way, LBA 259674 can be read without error by the general dumping tool (isobuster, clonecd etc.)?

I am not using CloneCD.

# IsoBuster
Whether "all zeroes" or "User Data All zeroes" is selected, a sector of all zeroes (2352 bytes) is created.
![screenshot 1709203970](https://github.com/saramibreak/DiscImageCreator/assets/2080945/6128eb0e-f544-4d23-b0e4-b7bcb8be2b88)

**Comment by fuzz6001** [comment]
For reference, redumper generates the same hash as 20230909.
```
<rom name="dump.bin" size="610757952" crc="368ff3f5" md5="bfd7991fc566236ebc04a3f50278a305" sha1="1a4c72c20a1b0b480f47f00c94615d4cc63ea24b" />
```
Note that the error count is 0.
```
  REDUMP.ORG errors: 0
```

logs: [nfshs_redumper314.zip](https://github.com/saramibreak/DiscImageCreator/files/14455474/nfshs_redumper314.zip)

**Comment by fuzz6001** [comment]
This is a disc that happens to have the same error.

Shin Theme Park: Yuuenchi o Tsukurou (J) (not yet in the db)
logs: [Shin Theme Park.zip](https://github.com/saramibreak/DiscImageCreator/files/14468300/Shin.Theme.Park.zip)
```
LBA[176910, 0x2b30e]: Track[01]: Invalid mode - LBA[176910, 0x2b30e]: Track[01]: Other. Skip descrambling
```

**Comment by saramibreak** [comment]
Uploaded test version.
http://forum.redump.org/post/115412/#p115412

**Comment by fuzz6001** [comment]
It now generates the same hash as dic(20230909)/redumper.
Thanks for the fix.

Need for Speed: High Stakes
[nfshs_20240303.zip](https://github.com/saramibreak/DiscImageCreator/files/14472742/nfshs_20240303.zip)

Shin Theme Park
[shinthemepark_20240303.zip](https://github.com/saramibreak/DiscImageCreator/files/14472743/shinthemepark_20240303.zip)
