### ISSUE TITLE
Error overload: PS1 — Tetris Plus (USA)

### ISSUE THREAD

**Issue by gingerbeardman** [saramibreak/DiscImageCreator#27]
Problem: multiple errors 
- `C2` 
- `SenseData Key-Asc-Ascq: 03-02-8d = MEDIUM_ERROR - VENDOR UNIQUE ERROR`

Logs:
(will post when it's finished, let me know if I should just cancel it early, currently at 284877/286853)

I've used DICUI to rip a dozen or so PS1 games, and this is the first time it was not able to complete a disc successfully. I had my best attempt at 8x speed (default for my drive is 20x, and apparently supports reading CDs up to 48x).

Game: TETRIS PLUS
Version: Greatest Hits
Region: USA
Serial: SLUS-00338 50005

Note: seems to be an "enhanced" CD
01 = data track
02 to 51 = audio tracks
52 = data track

References:
https://www.discogs.com/Unknown-Artist-Tetris-Plus/release/12821208
https://gamefaqs.gamespot.com/ps/915929-tetris-plus/images/1123857

PS:
Also, at many speeds other than 8x, upon error and incomplete rip, my Plextor PX-716UF external USB drive is in a strange state that it will not do any more rips until it is power cycled.

**Comment by gingerbeardman** [comment]
OK, finally it failed. 

Here is output directory (minus the incomplete scm): https://mega.nz/#!l5gklYKA!93KwYYpQ0_Kn6WokN0IWpBToisT3OEchG33CPyJPdtY

And with the incomplete scm: (on request)

Using DICUI 1.12.2

**Comment by saramibreak** [comment]
> Note: seems to be an "enhanced" CD

Logs show this disc is single-session disc.

> Problem: multiple errors

Yes, your disc has multiple c2 errors. Please polish the disc if there are some scratches.

**Comment by gingerbeardman** [comment]
I'll do so!
