### ISSUE TITLE
Cannot match EAC dump, even when using /a

### ISSUE THREAD

**Issue by malvarenga123** [saramibreak/DiscImageCreator#271]
**Version**
20240401

**Describe the bug**
With the latest version of DIC, audio disc tracks always have an offset equal to the drive's.

Here's the bit compare output of foobar (equal for all tracks):
```
Differences found in all track pairs, all became identical after applying offset and truncating first/last samples.
Extra leading/trailing sections contained only null samples in 12 out of 12 non-identical track pairs.

Comparing:
"H:\cds\Dance Now 4\01. La Bouche - Sweet Dreams.flac"
"H:\DiscImageCreator\Release_ANSI\dance now 4 (Track 01).flac"
Compared 14029680 samples.
Differences found: 27967513 values, 0:00.598844 - 5:17.949569, peak: 1.647705 (+4.34 dBTP) at 0:09.920317, 2ch
Channel difference peaks: 1.457794 (+3.27 dBTP) 1.647705 (+4.34 dBTP)
File #1 peaks: 1.000000 (0.00 dBTP) 1.000000 (0.00 dBTP)
File #2 peaks: 1.000000 (0.00 dBTP) 1.000000 (0.00 dBTP)
Detected offset as 30 samples.

Comparing again with corrected offset...
Compared 14029650 samples, with offset of 30.
Discarded 30 trailing null samples from file #1.
Discarded 30 leading null samples from file #2.
No differences in decoded data found within the compared range.
Channel peaks: 1.000000 (0.00 dBTP) 1.000000 (0.00 dBTP)
```
I know redumper works the same way, but you can force a 0 offset that will make all tracks match. This doesn't seem to work with DIC.

**Screenshots**
cd l: dance now 4.bin 8 /q /d8 /c2 /d /a 0
cd l: dance now 4.bin 8 /q /d8 /c2 /d /a -30 
cd l: dance now 4.bin 8 /q /d8 /c2 /d /a 30
None of those commands solve the issue

**Log file**
[dancenow4.zip](https://github.com/saramibreak/DiscImageCreator/files/15049397/dancenow4.zip)

**Comment by saramibreak** [comment]
fixed /a is invalid when pregap sector exists in the 1st track.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/15052176/DiscImageCreator_test.zip)

**Comment by malvarenga123** [comment]
Thanks sarami. It works now with `/a 0`
