### ISSUE TITLE
Regression from 20240101: Dump of region-free, copy protection-free DVD-Video disc never starts

### ISSUE THREAD

**Issue by Lugamo94** [saramibreak/DiscImageCreator#272]
Please be sure to read through the entire [README](https://github.com/saramibreak/DiscImageCreator/blob/master/README.md) before reporting.

**Version**
20240401

**Describe the bug**
Trying to dump a standard DVD-Video gets stuck in the Reading DirectoryRecord stage. When using DIC 20240101, the dumping process starts immediately. Copy-protected DVD-Video discs start just fine in DIC 20240401.

**Screenshots**
DIC 20240101:
![DiscImageCreator_jL16LbRO8K](https://github.com/saramibreak/DiscImageCreator/assets/166972693/f45983c2-2408-48b2-b402-ab44f66e82ee)
DIC 20240401:
![DiscImageCreator_M3KoLB4P7y](https://github.com/saramibreak/DiscImageCreator/assets/166972693/13f4cf5a-ffd9-4ac9-88e9-17d8fcd85830)

**Disc title**
Heroes II

**Disc ringcode**
Data Side Mastering Code (laser branded/etched): TELTRON ■ DVD ■ MOD 5010 POS 15643 ■ INDUSTRIA ARGENTINA
Data Side Mastering SID Code: IFPI LL02
Data Side Mould SID Code: IFPI 6C12

**URL**
The disc is out of print.

**Log file**
[Heroes II (Argentina) - DiscImageCreator 20240401 logs.zip](https://github.com/saramibreak/DiscImageCreator/files/15143120/Heroes.II.Argentina.-.DiscImageCreator.20240401.logs.zip)
[Heroes II (Argentina) - DiscImageCreator 20240101 logs.zip](https://github.com/saramibreak/DiscImageCreator/files/15143102/Heroes.II.Argentina.-.DiscImageCreator.20240101.logs.zip)

**Comment by saramibreak** [comment]
Thanks. Uploaded.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/15149909/DiscImageCreator_test.zip)

**Comment by Lugamo94** [comment]
It works now, thanks.
![DiscImageCreator_LPcpehuYeF](https://github.com/saramibreak/DiscImageCreator/assets/166972693/c830601b-99ee-4315-82a4-339a103f9bf2)
