### ISSUE TITLE
Hashes missmatch between DIC versions

### ISSUE THREAD

**Issue by eingrossfilou** [saramibreak/DiscImageCreator#274]
**Version**

20240401

**Describe the bug**

When dumping [Age of Empires III (Disc 1)](http://redump.org/disc/114025/), DIC-20240401 produces an image that differs from DIC-20230606 and redumper v2024.01.08 build_311.

It looks like a possible regression, DIC-20230606 and redumper hashs are same and match the [redump.org ones](http://redump.org/disc/114025/)

**Disc title**
[Age of Empires III (Disc 1)](http://redump.org/disc/114025/)

**Disc ringcode**
Data Side Mastering Code (laser branded/etched): arvato digital services bertelsmann X14-04278 04
Data Side Mastering SID Code: IFPI L0 22
Data Side Toolstamp or Mastering Code (engraved/stamped): 1
Data Side Mould SID Code: IFPI 5805

**Log file**

[AOEIIICD1.zip](https://github.com/saramibreak/DiscImageCreator/files/15278347/AOEIIICD1.zip)

**Comment by eingrossfilou** [comment]
Here the logs for DIC-20230606

[AOEIIICD1-20230606.zip](https://github.com/saramibreak/DiscImageCreator/files/15278490/AOEIIICD1-20230606.zip)

**Comment by saramibreak** [comment]
Thanks. Uploaded test version.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/15282972/DiscImageCreator_test.zip)

**Comment by eingrossfilou** [comment]
Look like the issue is solved, the test version produces the same hash as redumper and the one register in redump.org
