### ISSUE TITLE
Mismatch in SecuROM sectors between DIC and Redumper.

### ISSUE THREAD

**Issue by maxz** [saramibreak/DiscImageCreator#277]
**Version**
`20240601T190719`

**Describe the bug**
The track hashes match, but DIC and Redumper output different SecuROM sectors.

DiscImageCreator (`ZEUS_subIntention.txt`):
```
MSF: 00:01:74 Q-Data: 412100 00:40:01 00 00:03:74 2ef1
MSF: 01:08:50 Q-Data: 410101 21:06:50 00 05:08:50 0a8f
MSF: 01:21:00 Q-Data: 410101 11:19:00 00 09:21:00 26b1
MSF: 01:31:16 Q-Data: 410101 03:29:16 00 41:31:16 b166
MSF: 01:33:02 Q-Data: 410101 21:31:02 00 05:33:02 1f2b
MSF: 02:19:24 Q-Data: 410101 06:17:24 00 22:19:24 4ea8
MSF: 02:47:28 Q-Data: 410101 02:45:2a 00 02:47:68 d26b
MSF: 02:51:15 Q-Data: 410101 02:49:1d 00 02:51:05 ba37
MSF: 02:56:51 Q-Data: 410101 02:14:51 00 02:54:51 e749
MSF: 03:36:58 Q-Data: 410101 03:14:58 00 03:32:58 057f
MSF: 03:58:14 Q-Data: 410101 03:56:10 00 03:58:34 ea09
```

Redumper (`ZEUS.log`):
```
SecuROM [ZEUS.bin]:
  scheme: unknown
MSF: 41:19:35 Q-Data: 410101 41:17:34 00 41:19:34 9951
MSF: 41:19:36 Q-Data: 410101 41:17:34 00 41:19:34 9951
```

I don't know which one is more correct.

**Command**
`./DiscImageCreator.out cd /dev/sr0 ZEUS.bin 40 /q /c2 100 1 /d8 /ns`

**Disc title**
Herrscher des Olymp: Zeus (BestSeller Series)

**Disc ringcode**
`Sonopress 50455848/S0026154 01`, `IFPI LB 46` (Mastering SID).

**URL**
[eBay](https://www.ebay.de/sch/i.html?&_nkw=%22Herrscher+des+Olymp%22+Zeus+%22Bestseller+Series%22)

**Log files**
[ZEUS (DiscImageCreator).zip](https://archive.org/download/redump.org-logs/ZEUS%20%28DiscImageCreator%29.zip)
[ZEUS (Redumper).zip](https://archive.org/download/redump.org-logs/ZEUS%20%28Redumper%29.zip)

**Comment by saramibreak** [comment]
Would you upload DATA1.CAB of the disc?

**Comment by maxz** [comment]
[DATA1.CAB](https://archive.org/download/redump.org-logs/DATA1.CAB)

Let me know when you finished downloading it so that I can remove the file again.

**Comment by saramibreak** [comment]
Thanks, I finished it.

**Comment by maxz** [comment]
I don't have a Windows install, but if nothing else works then I might be able to dump the disc in a Windows VM, although at that point the host OS might somehow interfere.

```
grep: ./DATA1.CAB: binary file matches
grep: ./DEMOS/Pharao/_sys1.cab: binary file matches
grep: ./DEMOS/Pharao/_user1.cab: binary file matches
grep: ./DEMOS/Pharao/data1.cab: binary file matches
grep: ./_SYS1.CAB: binary file matches
grep: ./_USER1.CAB: binary file matches
```

These are the files with the pattern. So just the CAP files, of which probably only the ones in the root directory are relevant here.

Using [unshield](https://github.com/twogood/unshield) I was able to extract `DATA1.CAB` just by itself.
Would using `unshield` solve your problem?
If not, then what else do you require from me to continue debugging?

<details>
<summary>
`SYS1.CAB` and `_USER1.CAB` seem like generic files to me. But their content differs from the Pharao demo files.</summary>

```
23f0395b61628f5b3698714708a5e876  DATA1.CAB
b29ebf3acc5956976b4bfc2fe9a08efa  _SYS1.CAB
b86c35678dc9462f9408a4e45d09113e  _USER1.CAB
f243222661eb930434d633e897b06d39  DEMOS/Pharao/data1.cab
cf31d5b3a38d037a28f1ada7396de627  DEMOS/Pharao/_sys1.cab
1e7003bea4ce8b9ab18839b834612ff5  DEMOS/Pharao/_user1.cab
```
</details>
So maybe those would help you?

**Comment by saramibreak** [comment]
Thanks. I confirmed ZEUS_subIntention.txt is correct.
