### ISSUE TITLE
Plextor drive in unstable state after ripping, needs to be power cycled

### ISSUE THREAD

**Issue by gingerbeardman** [saramibreak/DiscImageCreator#28]
From #27 

After both successful and unsuccessful ripping, my Plextor PX-716UF external USB drive is often a strange state that it will not do any more rips until it is power cycled. I was thinking maybe there is a "reset" command that can be issued to this drive to help.

I can help debug this with guidance from you.

Thanks!

**Comment by gingerbeardman** [comment]
Using the reset command in between rips seems to work.

**Comment by gingerbeardman** [comment]
Reset sometimes helps but mostly still needs power cycle

**Comment by saramibreak** [comment]
I have no idea about it. Perhaps drive's problem, not software. How about other plextor drive if you have?

**Comment by gingerbeardman** [comment]
I do not have another drive and this one was bought new unused only recently. I'll keep looking into it.

**Comment by mirh** [comment]
Did you try firmware updates?

**Comment by gingerbeardman** [comment]
Yes, I'm using the latest/final firmware.

**Comment by mirh** [comment]
Mhh.. In my experience, there are drives that [go down in flames](https://github.com/PCSX2/pcsx2/issues/648#issuecomment-227250009) after they hit some specifically crafted sequence of bits. 

I wonder what could be the minimal amount of activity/actions that makes yours fail.

**Comment by gingerbeardman** [comment]
Wow, very interesting! That makes sense and feels right in my experience. I'm happy that a simple power cycle will return it to "normal" behaviour, at least for now.

**Comment by gingerbeardman** [comment]
The drive eventually failed. 

I bought another used drive that was also DOA. 

Waiting on my 3rd drive that is guaranteed working.
