### ISSUE TITLE
SS.bin output to wrong folder when dumping Xbox

### ISSUE THREAD

**Issue by Deterous** [saramibreak/DiscImageCreator#282]
**Version**
20240601

**Describe the bug**
SS.bin is not output to the current directory when dumping Original Xbox games. Instead, it gets output to the directory above. See https://github.com/SabreTools/MPF/issues/715

**Command**
`xbox E:\ SEP13011042072.iso 8 /rr 10 `

**Result**
All log files in current directory, except SEP13011042072_SS.bin is placed in parent directory.

**Log file**
[logs.zip](https://github.com/user-attachments/files/16233068/logs.zip)

**Comment by saramibreak** [comment]
Test version.
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/16234698/DiscImageCreator_test.zip)
