### ISSUE TITLE
DIC spits out zero dumped CD without errors, halts at Reading DirectoryRecord.

### ISSUE THREAD

**Issue by mrpijey** [saramibreak/DiscImageCreator#283]
Please be sure to read through the entire [README](https://github.com/saramibreak/DiscImageCreator/blob/master/README.md) before reporting.

**Version**
32 bit, AnsiBuild, 20240627T232126

**Describe the bug**
Dumping a CD-ROM yields in a drive ejection without any errors reported in the console or log files. Log file and incomplete dump included. Same disc dumps fine with other tools, and manual file copy from the disc finishes without errors as well.

DIC halts at Reading DirectoryRecord    9/  27 and then spits out the disc.

Same issue has been detected with multiple discs of smaller sizes, all being from the same disc set however.

**Screenshots**
DiscImageCreator.exe cd D media_dic\Disc01\Disc01.bin 4 /d8 /c2 5000 /q

**Disc title**
Microsoft Partner Program: Networking Infrastructure Solutions Resources

**Disc ringcode**
X10-83913 02 02

**URL**
N/A

**Log file**
[log.txt](https://github.com/user-attachments/files/16286921/log.txt)
[Disc01.zip](https://github.com/user-attachments/files/16286926/Disc01.zip)

**Comment by saramibreak** [comment]
If possible, would you upload LBA 31 ... 47 using tool (e.g. IsoBuster)?

**Comment by mrpijey** [comment]
[Disc Segment_LBA31-47.zip](https://github.com/user-attachments/files/16309159/Disc.Segment_LBA31-47.zip)

**Comment by saramibreak** [comment]
Thanks. Fixed a overflow.
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/16310207/DiscImageCreator_test.zip)

**Comment by mrpijey** [comment]
Thank you, fix is verified and discs dump nicely now.
