### ISSUE TITLE
Differences in leadin and leadout between DiscImageCreator and Redumper

### ISSUE THREAD

**Issue by maxz** [saramibreak/DiscImageCreator#284]
**Version**
`64 bit, AnsiBuild, 20240601T190719`

**Describe the bug**
I don't know whether DiscImageCreator and Redumper intend to have equivalent leadin and -out data, but currently they differ for the disc I tested it with ([Myth III: The Wolf Age](http://redump.org/disc/42299/)).
It would make sense if their data matched, because the Redump.org Wiki recommends to include the hashes of the leadin and -out.

`MYTH3 (Track 0).bin` differs widely between both, but DIC's `MYTH3 (Track 1)(-LBA).bin` seems to be a longer version of Redumper's `MYTH3 (Track 0).bin`. The last 176400 bytes of `MYTH3 (Track 1)(-LBA).bin` are equivalent to Redumper's `MYTH3 (Track 0).bin`.
I guess there might be similar differences in the leadout but I did not find a disc to test that with yet.

Also what is the reason for the seeming disagreement about what track 0 and track A should contain (e. g. why does Redumper's Track 0 contain data which DIC contains in Track 1 -LBA)? Is there no obvious, continuous structure to those leading or trailing sectors compared to the sectors in the regular data area?

**Command**
`./DiscImageCreator.out cd /dev/sr0 MYTH3.bin 40 /q /c2 100 1 /d8 /sf`

**Disc title**
[Myth III: The Wolf Age](http://redump.org/disc/42299/)

**Disc ringcode**
`DISCTRONICS       MYTH 3/ EFGIS 01`, `IFPI L503` (Mastering SID) and `IFPI 8726` (Mould SID).

**URL**
[eBay](https://www.ebay.de/sch/i.html?_nkw=%22Myth+III%22+%22Die+Zeit+des+Wolfs%22+%225026555034654%22&_sacat=1249)

**Log files**
[MYTH3 (DiscImageCreator).zip](https://archive.org/download/redump.org-logs/MYTH3%20%28DiscImageCreator%29.zip)
[MYTH3 (Redumper).zip](https://archive.org/download/redump.org-logs/MYTH3%20%28Redumper%29.zip)

**Comment by saramibreak** [comment]
> MYTH3 (Track 0).bin differs widely between both

Yes. Plextor returns different sector range each time.

> MYTH3 (Track 1)(-LBA).bin seems to be a longer ...

`(Track 1)(-LBA).bin` is pregap sectors of the track 1. DIC's `(Track 0).bin` is lead-in sectors, which is track 0. Pregap sectors of the track 1 do not belongs lead-in area.

You can read the subchannel by the readable text format using `sub` command.

`./DiscImageCreator.out sub MYTH3 (Track 1)(-LBA).sub`
`./DiscImageCreator.out sub MYTH3 (Track 0).sub`

**Comment by maxz** [comment]
> > MYTH3 (Track 0).bin differs widely between both
> 
> Yes. Plextor returns different sector range each time.

So is there any way to obtain reproducible (partial) lead-in data?
What is your stance on which parts of the lead-in and pregap data should be recorded and are important to preserving the CD?
And on how comparability between the DIC and Redumper data can be ensured?

See sections [Track 0/A hashes](http://wiki.redump.org/index.php?title=Dumping_Guide_(redumper_CLI)) of the Redumper CLI guide and section [PLEXTOR Lead-in Notes/Solution](http://wiki.redump.org/index.php?title=Redumper) of the Redumper Moderator Guidelines.
Also take a look at this disc [Oyaji Hunter Mahjong](http://redump.org/disc/39873) which has the data for the lead-in and lead-out included.

> > MYTH3 (Track 1)(-LBA).bin seems to be a longer ...
> 
> `(Track 1)(-LBA).bin` is pregap sectors of the track 1. DIC's `(Track 0).bin` is lead-in sectors, which is track 0. Pregap sectors of the track 1 do not belongs lead-in area.

Ok, that makes sense. So Redumper is handling the pregap wrong in your opinion?

> You can read the subchannel by the readable text format using `sub` command.
> 
> `./DiscImageCreator.out sub MYTH3 (Track 1)(-LBA).sub` `./DiscImageCreator.out sub MYTH3 (Track 0).sub`

This does not produce any useful output for me. Can you give an example of how the output is supposed to look?
I can't imagine that it is just supposed to output the file size.

```
AppVersion
        64 bit, AnsiBuild, 20240601T190719
CurrentDirectory
        /tmp/MYTH3 (DiscImageCreator)
WorkingPath
         Argument: MYTH3 (Track 0).sub
         FullPath: /tmp/MYTH3 (DiscImageCreator)/MYTH3 (Track 0).sub
            Drive: /
        Directory: tmp/MYTH3 (DiscImageCreator)/
         Filename: MYTH3 (Track 0)
        Extension: .sub
StartTime: 2024-07-19T05:53:48+0200
Parsing sub (Size)   191424/  191424
EndTime: 2024-07-19T05:53:48+0200
```
```
AppVersion
        64 bit, AnsiBuild, 20240601T190719
CurrentDirectory
        /tmp/MYTH3 (DiscImageCreator)
WorkingPath
         Argument: MYTH3 (Track 1)(-LBA).sub
         FullPath: /tmp/MYTH3 (DiscImageCreator)/MYTH3 (Track 1)(-LBA).sub
            Drive: /
        Directory: tmp/MYTH3 (DiscImageCreator)/
         Filename: MYTH3 (Track 1)(-LBA)
        Extension: .sub
StartTime: 2024-07-19T05:53:48+0200
Parsing sub (Size)    14400/   14400
EndTime: 2024-07-19T05:53:48+0200
```

**Comment by saramibreak** [comment]
> So is there any way to obtain reproducible (partial) lead-in data?

It's a super rare that non-zero data exists in the lead-in area, so it's not a problem now.

> What is your stance on which parts of the lead-in and pregap data should be recorded and are important to preserving the CD?

Currently I think the lead-in area and pregap sectors should be preserved separately.

> And on how comparability ... lead-out included.

I don't have [Oyaji Hunter Mahjong](http://redump.org/disc/39873) yet, so I can't comment now.

> So Redumper is handling the pregap wrong in your opinion?

The only thing I can say is that pregap sectors of the track 1 belong track 1, not track 0. It's specification of compact disc.

> This does not produce any useful output for me.

Isn't there `MYTH3 (Track 1)(-LBA)_subReadable.txt` ?

**Comment by maxz** [comment]
> > This does not produce any useful output for me.
> 
> Isn't there `MYTH3 (Track 1)(-LBA)_subReadable.txt` ?

There is, thanks. I missed that it was generating a new file.

So I think there is no obvious thing to fix or change right now regarding the pregap and lead-in, but I think you and @superg should communicate regarding this, maybe along with various other people of the inner redump.org circle and come to an agreement about which format we should use to preserve this data so that it is also comparable between the tools.
Currently all the files are different, I don't know which one would be enough to preserve so that my images can be used instead of the discs for all future uses.
