### ISSUE TITLE
[ERROR] Number of sector(s) where mode is invalid: 1

### ISSUE THREAD

**Issue by mrpijey** [saramibreak/DiscImageCreator#285]
Please be sure to read through the entire [README](https://github.com/saramibreak/DiscImageCreator/blob/master/README.md) before reporting.

**Version**
32 bit, AnsiBuild, 20240719T183529

**Describe the bug**
[ERROR] Number of sector(s) where mode is invalid: 1

Getting this from recent CD dumps. Yet this isn't logged in any error logs. Is it a critical error? If not, shouldn't it rather be [NOTICE] or something instead? Where should this error be logged?

**Disc title**
Neverwinter Nights Expansion pack 1 and 2, both discs

[log.txt](https://github.com/user-attachments/files/16326064/log.txt)

**Comment by saramibreak** [comment]
Please upload full logs.

**Comment by mrpijey** [comment]
[Disc04 - Shadows of Undrentide.zip](https://github.com/user-attachments/files/16389439/Disc04.-.Shadows.of.Undrentide.zip)
[Disc05 - Hordes of the Underdark.zip](https://github.com/user-attachments/files/16389441/Disc05.-.Hordes.of.the.Underdark.zip)

**Comment by saramibreak** [comment]
Thanks. Disc04 and 05 have SecuROM. If /ns is used, subchannel is dumped correctly.

> Is it a critical error?

No. The 4th sector of the last is changed to mode 2. It's specification of this protection.
```
LBA[320796, 0x4e51c], MSF[71:19:21], mode 1
LBA[320797, 0x4e51d], MSF[71:19:22], mode 1
LBA[320798, 0x4e51e], MSF[71:19:23], mode 1
LBA[320799, 0x4e51f], MSF[71:19:24], mode 1
LBA[320800, 0x4e520], MSF[71:19:25], mode 2 form 1, SubHeader[1](FileNum[00]), [2](ChannelNum[00]), [3](Submode[00])[NoEOF, Form 1], [4](CodingInfo[00])[]
LBA[320801, 0x4e521], MSF[71:19:26], mode 1
LBA[320802, 0x4e522], MSF[71:19:27], mode 1
LBA[320803, 0x4e523], MSF[71:19:28], mode 1
[ERROR] Number of sector(s) where mode is invalid: 1
	Sector: 320800, 
```

> If not, shouldn't it rather be [NOTICE] or something instead?

I will consider it.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/16439070/DiscImageCreator_test.zip)
changed message like this.
```
LBA[112198, 0x1b646], MSF[24:57:73], mode 1
LBA[112199, 0x1b647], MSF[24:57:74], mode 2 form 1, SubHeader[1](FileNum[00]), [2](ChannelNum[00]), [3](Submode[00])[NoEOF, Form 1], [4](CodingInfo[00])[]
LBA[112200, 0x1b648], MSF[24:58:00], mode 1
LBA[112201, 0x1b649], MSF[24:58:01], mode 1
LBA[112202, 0x1b64a], MSF[24:58:02], mode 1
[INFO] Detected SecuROM sector (mode changed): 112199
[NO ERROR] User data vs. ecc/edc match all
```

**Comment by saramibreak** [comment]
https://github.com/saramibreak/EccEdc/commit/4de6d42c766d4a721540aaa408e9c09362adf9df
