### ISSUE TITLE
Plextor Drive Reset and SpeedRead

### ISSUE THREAD

**Issue by codengine** [saramibreak/DiscImageCreator#286]
Hi,
I just started using DIC with MPF and noticed that when it is done dumping a disc, it will basically reset the drive.
So in my specific case it would also turn SpeedRead on, which is the default I assume.

Would there be a possibility to either have it not reset the SpeedRead flag? My intention is that I want to reduce the wear and tear on my drive and while DIC does indeed read discs using the passed speed option, windows and other tools like ProtectionID will still read the disc at max speed.

**Comment by saramibreak** [comment]
Uploaded test version.
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/16346247/DiscImageCreator_test.zip)
If SpeedRead is off by default, it turns back off when the program exits.

**Comment by codengine** [comment]
Thanks, I will try it later today.

**Comment by codengine** [comment]
Unfortunately it didn't work for me, SpeedRead was ON again when DIC was done (which may be the drives default - honestly I dont know how to change it). But I turned it off before I started the process.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/16363171/DiscImageCreator_test.zip)
If SpeedRead is already ON, DIC do not set to OFF.
If SpeedRead is OFF, DIC set to ON temporarily and set to OFF when the program exits.

**Comment by codengine** [comment]
> [DiscImageCreator_test.zip](https://github.com/user-attachments/files/16363171/DiscImageCreator_test.zip) If SpeedRead is already ON, DIC do not set to OFF. If SpeedRead is OFF, DIC set to ON temporarily and set to OFF when the program exits.

Can confirm, SpeedRead is now off when it was turned off before starting DIC. Awesome!
