### ISSUE TITLE
/sk for DVD is not working

### ISSUE THREAD

**Issue by Lugamo94** [saramibreak/DiscImageCreator#288]
Please be sure to read through the entire [README](https://github.com/saramibreak/DiscImageCreator/blob/master/README.md) before reporting.

**Version**
20240601

**Describe the bug**
I'm trying to dump a ring-protected Spanish DVD re-release of Patrician III, and I think I have an idea which sectors the ring may cover (478738-9 / 508448). The problem is that DIC goes to the next sector instead of skipping the amount of sectors I indicated. Is it meant to only work with ARccOS DVDs? If it is, have you considered implementing something similar for ring-protected DVDs? Either specifying an amount of sectors to be skipped until it tries again like /sk already does for ARccOS discs, or a range (ideally, both options could exist). Trying without `/ps` simply ended the dumping process.

**Screenshots**
> AppVersion
        32 bit, AnsiBuild, 20240601T211847
CurrentDirectory
        H:\MPF.UI_3.2.1_net8.0-windows_win-x86_release
WorkingPath
         Argument: ISO\Patrician III\Patrician III.iso
         FullPath: H:\MPF.UI_3.2.1_net8.0-windows_win-x86_release\ISO\Patrician III\Patrician III.iso
            Drive: H:
        Directory: \MPF.UI_3.2.1_net8.0-windows_win-x86_release\ISO\Patrician III\
         Filename: Patrician III
        Extension: .iso
StartTime: 2024-08-09T14:30:04-0300
Set the drive speed: 0KB/sec
DiskSize of [H:\MPF.UI_3.2.1_net8.0-windows_win-x86_release\ISO\Patrician III]
        Total:   536870907904 bytes
         Used:   471240040448 bytes
        ---------------------------
        Space:    65630867456 bytes
         => There is enough disk space for dumping
Reading DirectoryRecord   19/  19
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 1/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 2/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 3/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 4/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 5/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 6/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 7/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 8/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 9/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 10/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 11/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 12/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 13/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 14/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 15/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 16/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 17/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 18/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 19/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478738 (Pass 20/20)
LBA[478738, 0x74e12]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Padded by 0x00
LBA[478739, 0x74e13]: [F:ReadDVD][L:368]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 04-3e-02 = HARDWARE_ERROR - TIMEOUT ON LOGICAL UNIT
Read retry from 478739 (Pass 1/20)

**Disc title**
Patrician III: El imperio de los mares.

**Disc ringcode**
Data Side Mastering Code (laser branded/etched): Illegible
Mastering SID: IFPI L182
Mould SID: IFPI 3137

**URL**
[Biblio.es](https://biblio.es/libro/juego-pc-dvd-patrician-iii-imperio/1454925569)

**Log file**
[Patrician III 202408091444 Dump Logs.zip](https://github.com/user-attachments/files/16565077/Patrician.III.202408091444.Dump.Logs.zip)

[Patrician III 202408091704 Dump without ps.zip](https://github.com/user-attachments/files/16566342/Patrician.III.202408091704.Dump.without.ps.zip)

**Comment by saramibreak** [comment]
> Is it meant to only work with ARccOS DVDs?

1. If unknown protecion is used, /sf is needed to detect protection.
2. And edit "ReadErrorProtect.txt" to skip the file. LBA 478738 is sector of BOTROOP.TTP

```
		              Location of Extent: 472894
		                     Data Length: 32483717
		         Recording Date and Time: 2006-03-08T13:19:50+01:00
		                      File Flags: 0 (Visible, File, No Associated, No Record Format, No Owner/Group ID, Final Directory Record)
		                  File Unit Size: 0
		             Interleave Gap Size: 0
		          Volume Sequence Number: 1
		       Length of File Identifier: 13
		                 File Identifier: BOTROOP.TTP;1
```
3. Then, use /sk to skip sectors.

**Comment by Lugamo94** [comment]
> > Is it meant to only work with ARccOS DVDs?
> 
>     1. If unknown protecion is used, /sf is needed to detect protection.
> 
>     2. And edit "ReadErrorProtect.txt" to skip the file. LBA 478738 is sector of BOTROOP.TTP
> 
> 
> ```
> 		              Location of Extent: 472894
> 		                     Data Length: 32483717
> 		         Recording Date and Time: 2006-03-08T13:19:50+01:00
> 		                      File Flags: 0 (Visible, File, No Associated, No Record Format, No Owner/Group ID, Final Directory Record)
> 		                  File Unit Size: 0
> 		             Interleave Gap Size: 0
> 		          Volume Sequence Number: 1
> 		       Length of File Identifier: 13
> 		                 File Identifier: BOTROOP.TTP;1
> ```
> 
>     3. Then, use /sk to skip sectors.

Same results. FX Interactive and Dinamic Multimedia's ring protections are entirely physical, for the record.
[Patrician III 202408101002 Dump.zip](https://github.com/user-attachments/files/16569640/Patrician.III.202408101002.Dump.zip)

**Comment by saramibreak** [comment]
> Same results.

/sk needs the value to skip sectors.

**Comment by Lugamo94** [comment]
Thanks, sarami. It took some time, but it eventually finished, and got matching dumps with my CloneCD dump refined with CDArchive.
[Patrician III_logs.zip](https://github.com/user-attachments/files/16571663/Patrician.III_logs.zip)
