### ISSUE TITLE
[Feature request] Option to require that all sectors have been read correctly twice

### ISSUE THREAD

**Issue by thegawin** [saramibreak/DiscImageCreator#293]
There are some modern optical drives (with MT1862N) that support scrambled mode.

The issue is these drives tend to produce bad hashes even on single data track cd with no protection. As drives have probably bad c1/c2, I think this feature would be good workaround.

(Also asus jb8 often can fall into fall positives with C2 errors.)

**Comment by saramibreak** [comment]
> There are some modern optical drives (with MT1862N) that support scrambled mode.

What drive is it?

**Comment by thegawin** [comment]
These are constructions based on MT1862AN/MT1862N chipset (DATA_SUB_C2 + BE_CDDA):
- GH24NSC0 ( firmware LK00) <- I have this one
- GH24NSD1 (LG00) <- used by olofolleola4
- iHAS 124 B (AL0R) <- also from olo

I've noticed they probably don't support FlushDriveCache (this may be true problem) and also OEM versions of this drives like for example asus has this locked in firmware.

**Comment by thegawin** [comment]
Started comparing resulting bin files with hexeditior. Will update if I'm gonna find something interesting.

So far seems like single track data CDs are giving bad hashes due to last sector being wrong. After copying it from plextor/asus jb8 I can get good hash.

**Comment by saramibreak** [comment]
> So far seems like single track data CDs are giving bad hashes due to last sector being wrong.

Because these drives can't read the lead-out sector.

**Comment by thegawin** [comment]
Let discard problem of lead-out for now. Maybe Ribshark would have idea for that. Picked mixed mode CD without leadout:

Good dump:
```
<rom name="drive_test (Track 01).bin" size="272276928" crc="2fa5fb66" md5="3c98bc5d0d042d1535df01bf87c3998f" sha1="cc3d2b3653d5008937341ea659303228f0a1e3e9" />
<rom name="drive_test (Track 02).bin" size="16012416" crc="b35fb803" md5="558f4e57e82cf4c19f318ab152d44ca6" sha1="09ffb636e1e020b8855189a62d781832c07228a2" />
<rom name="drive_test (Track 03).bin" size="27339648" crc="64e0cdd1" md5="49aabe0a2d30dcde209cbf4f84051e97" sha1="2d2abf06d9de4212a04b4f3fc7d6de7f698876a7" />
<rom name="drive_test (Track 04).bin" size="25185216" crc="c156d138" md5="bcc4b0c52d9a47aa7e8197b29a4b9ffe" sha1="cab44f9639c606d1fcbecac171031f05ee0efcb0" />
<rom name="drive_test (Track 05).bin" size="25427472" crc="d7121527" md5="eac10e11656624a66fca94095a2b5cf5" sha1="127a291226c2a1fe96f190dd1c576b705a15d933" />
<rom name="drive_test (Track 06).bin" size="27144432" crc="ffc48534" md5="b12ff725a48fd17b80aebc2c5be5d939" sha1="1e9c67ab78a59a027ecfd7cab0ecd643239e58ee" />
<rom name="drive_test (Track 07).bin" size="24785376" crc="e30e14c1" md5="4ef8741b3255b246b28708cbb40aeb66" sha1="5a62eedf29ef01afbe541d144ea77fc220912fd6" />
<rom name="drive_test (Track 08).bin" size="25963728" crc="8d973cbc" md5="88af204fa685297396797f926de835ab" sha1="7c12e74777ddee5522f3480b53cca2637dd9dd66" />
<rom name="drive_test (Track 09).bin" size="26563488" crc="08eb2b64" md5="ee96a48e14bf91b09fd35d7282ec9ef1" sha1="9c87c24757633be296aecd432ba3c70ad2539d07" />
<rom name="drive_test (Track 10).bin" size="26173056" crc="01ceee3d" md5="845fee9621dd5fe809b5478c80286491" sha1="b13aa4ace19e1cb22e3795958ce1cd5c110bd047" />
<rom name="drive_test (Track 11).bin" size="24298512" crc="ab2f593a" md5="947e1ddfc588fcc7412ffda82ed9c822" sha1="6a2ccdbab031e4b0150bcb37067694747626077a" />
```
First try:
```
<rom name="drive_test (Track 01).bin" size="272276928" crc="2fa5fb66" md5="3c98bc5d0d042d1535df01bf87c3998f" sha1="cc3d2b3653d5008937341ea659303228f0a1e3e9" />
<rom name="drive_test (Track 02).bin" size="16012416" crc="b35fb803" md5="558f4e57e82cf4c19f318ab152d44ca6" sha1="09ffb636e1e020b8855189a62d781832c07228a2" /> <------------------- wrong size
<rom name="drive_test (Track 03).bin" size="27339648" crc="64e0cdd1" md5="49aabe0a2d30dcde209cbf4f84051e97" sha1="2d2abf06d9de4212a04b4f3fc7d6de7f698876a7" />
<rom name="drive_test (Track 04).bin" size="25185216" crc="c156d138" md5="bcc4b0c52d9a47aa7e8197b29a4b9ffe" sha1="cab44f9639c606d1fcbecac171031f05ee0efcb0" />
<rom name="drive_test (Track 05).bin" size="25427472" crc="d7121527" md5="eac10e11656624a66fca94095a2b5cf5" sha1="127a291226c2a1fe96f190dd1c576b705a15d933" />
<rom name="drive_test (Track 06).bin" size="27144432" crc="ffc48534" md5="b12ff725a48fd17b80aebc2c5be5d939" sha1="1e9c67ab78a59a027ecfd7cab0ecd643239e58ee" />
<rom name="drive_test (Track 07).bin" size="24785376" crc="e30e14c1" md5="4ef8741b3255b246b28708cbb40aeb66" sha1="5a62eedf29ef01afbe541d144ea77fc220912fd6" />
<rom name="drive_test (Track 08).bin" size="25963728" crc="8d973cbc" md5="88af204fa685297396797f926de835ab" sha1="7c12e74777ddee5522f3480b53cca2637dd9dd66" />
<rom name="drive_test (Track 09).bin" size="26563488" crc="08eb2b64" md5="ee96a48e14bf91b09fd35d7282ec9ef1" sha1="9c87c24757633be296aecd432ba3c70ad2539d07" />
<rom name="drive_test (Track 10).bin" size="26173056" crc="01ceee3d" md5="845fee9621dd5fe809b5478c80286491" sha1="b13aa4ace19e1cb22e3795958ce1cd5c110bd047" />
<rom name="drive_test (Track 11).bin" size="24298512" crc="ab2f593a" md5="947e1ddfc588fcc7412ffda82ed9c822" sha1="6a2ccdbab031e4b0150bcb37067694747626077a" />
```

second try:
```
<rom name="drive_test (Track 01).bin" size="271921776" crc="8a574124" md5="71e269ff0ae936045a365c44e937e506" sha1="56226c3ed9faa3bb7eca01ba506faf37f979722d" />
<rom name="drive_test (Track 02).bin" size="16713312" crc="1458bb7a" md5="613c77a0e3bb9a7bce44f3f2dd3a5e76" sha1="0882ca05eadfb2785456905be7da2d1e7cf5f387" />
<rom name="drive_test (Track 03).bin" size="27339648" crc="9b7b30d6" md5="0ac4eca982f7e0805b65e0134b9832b1" sha1="a553e252b813b575f6ec264bac71cfd240c17a49" />
<rom name="drive_test (Track 04).bin" size="25185216" crc="521a4796" md5="a490b184c0b616a79710fbb5934ec3f5" sha1="9a2d69215af4c73d8d31a3995779d12c86b02a1c" />
<rom name="drive_test (Track 05).bin" size="25427472" crc="9b1c1833" md5="28c9d09efe751750f17429b3d150c510" sha1="66c0185ebd42d7900db0cfcb9b4bd6f3403146ee" />
<rom name="drive_test (Track 06).bin" size="26798688" crc="e50db95d" md5="5c10af77e0893f52f4cebc2de18234dc" sha1="1850f2b249a31b4126ff49fcb9badaac37e20a39" /> <----- wrong size
<rom name="drive_test (Track 07).bin" size="24785376" crc="e30e14c1" md5="4ef8741b3255b246b28708cbb40aeb66" sha1="5a62eedf29ef01afbe541d144ea77fc220912fd6" />
<rom name="drive_test (Track 08).bin" size="25963728" crc="8d973cbc" md5="88af204fa685297396797f926de835ab" sha1="7c12e74777ddee5522f3480b53cca2637dd9dd66" />
<rom name="drive_test (Track 09).bin" size="26563488" crc="08eb2b64" md5="ee96a48e14bf91b09fd35d7282ec9ef1" sha1="9c87c24757633be296aecd432ba3c70ad2539d07" />
<rom name="drive_test (Track 10).bin" size="26173056" crc="01ceee3d" md5="845fee9621dd5fe809b5478c80286491" sha1="b13aa4ace19e1cb22e3795958ce1cd5c110bd047" />
<rom name="drive_test (Track 11).bin" size="24298512" crc="ab2f593a" md5="947e1ddfc588fcc7412ffda82ed9c822" sha1="6a2ccdbab031e4b0150bcb37067694747626077a" />
```

The reproducibility of bad hashes make me feel this may be something with reading QTOC.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.tar.gz](https://github.com/user-attachments/files/18016823/DiscImageCreator_test.tar.gz)
improved subQ channel fixing

**Comment by thegawin** [comment]
Thanks, I will test and post new topic to clean up a bit.

**Comment by thegawin** [comment]
Thanks, I've done test run on current master: https://drive.google.com/file/d/1kXoyKV3PDaeNAHA6sSjYQ3fIDPwq-XxO/view?usp=drive_link

http://redump.org/disc/108808/

I can see improvements. :)

So to summary I think there's still something preventing DIC to get hashes right (multitrack discs), redumper can get hashes right, but cannot recover in case of subcode desync (and then gets sizes and hashes wrong).

On my side I was able to dump firmware of GH24NSC0 and I've sent it to ribshark. Maybe he will be able unlock lead-out. (also chipset from mediatek)

I will make new thread. Cheers in New Year!

**Comment by tuowangkeji** [comment]
Hello, I'm currently troubled by a problem. Could you please help me solve it? Regarding the Mediatek MT1862AN chip, I want to change the name from ASUS or LG to my own name! For example, they will display the corresponding names on my computer device manager. I want to modify them. May I ask if this requires any code or BIN file?
Key point: Do not affect the function and usage of the drive!

**Comment by tuowangkeji** [comment]
> [DiscImageCreator_test.tar.gz](https://github.com/user-attachments/files/18016823/DiscImageCreator_test.tar.gz) 改进了子通道修复

Hello, I'm currently troubled by a problem. Could you please help me solve it? Regarding the Mediatek MT1862AN chip, I want to change the name from ASUS or LG to my own name! For example, they will display the corresponding names on my computer device manager. I want to modify them. May I ask if this requires any code or BIN file?
Key point: Do not affect the function and usage of the drive!
