### ISSUE TITLE
Problems with ccd files generated from audio CDs

### ISSUE THREAD

**Issue by epa-dha** [saramibreak/DiscImageCreator#294]
When I use the Plextor PX-760A to dump an audio CD, the cue file is correct, but the ccd file is incorrect. Only the last entry is incorrect. When dumped with HLDS WH16NS58DUP (firmware is Asus BW-16D1HT 3.02), both cue and ccd files get the correct result. This can be verified by mounting the cue or ccd file to a virtual drive and using CUERipper to see if it matches CUETools DB or AccurateRip.
[dic760d8.ccd.txt](https://github.com/user-attachments/files/18148056/dic760d8.ccd.txt)
[dichlds.ccd.txt](https://github.com/user-attachments/files/18148058/dichlds.ccd.txt)

**Comment by epa-dha** [comment]
My report is that if you process the exact same audio CD on different drives, an incomplete ccd file may be generated.
Among the files generated by DIC, I decided to upload the files that showed obvious differences.

[dic760d8_disc.txt](https://github.com/user-attachments/files/18150676/dic760d8_disc.txt)
[dic760d8_mainInfo.txt](https://github.com/user-attachments/files/18150681/dic760d8_mainInfo.txt)
[dichlds_disc.txt](https://github.com/user-attachments/files/18150651/dichlds_disc.txt)
[dichlds_mainInfo.txt](https://github.com/user-attachments/files/18150663/dichlds_mainInfo.txt)

**Comment by epa-dha** [comment]
Among the CloneCD files, img and sub files are exactly the same at the binary level. Only the ccd file is a little different, which is the cause of the problem.

**Comment by saramibreak** [comment]
> Only the ccd file is a little different, which is the cause of the problem.

Related issue #294, #42

Try to dump it by CloneCD and compare CloneCD's ccd and DIC's ccd.

**Comment by epa-dha** [comment]
I also tried dumping it with CloneCD. The same thing is happening with CloneCD. The ccd file is incorrect. In addition, the cue file is also incorrect in CloneCD. In DIC, the cue file is correct. 
[ccd760.ccd.txt](https://github.com/user-attachments/files/18159818/ccd760.ccd.txt)
[ccd760.cue.txt](https://github.com/user-attachments/files/18159842/ccd760.cue.txt)

I also tried it with Alcohol 120%. The situation was similar.
[a120760.ccd.txt](https://github.com/user-attachments/files/18159826/a120760.ccd.txt)

By the way, there is a software similar to CloneCD called CD Manipulator. This software can successfully generate ccd and cue files on the PX-760.
[cdm760.ccd.txt](https://github.com/user-attachments/files/18159831/cdm760.ccd.txt)
[cdm760.cue.txt](https://github.com/user-attachments/files/18159836/cdm760.cue.txt)

http://www.storeroom.info/cdm/

**Comment by saramibreak** [comment]
> By the way, there is a software similar to CloneCD called CD Manipulator. This software can successfully generate ccd and cue files on the PX-760.

It's weird. DIC uses [SCSI Pass Through Interface](https://en.wikipedia.org/wiki/SCSI_Pass_Through_Interface) (SPTI, in Windows), while CDM uses [Advanced SCSI Programming Interface](https://en.wikipedia.org/wiki/Advanced_SCSI_Programming_Interface) (ASPI). By the way, CCD uses ElbyCDIO (It's proprietary) and A120% uses [SCSI Pass-Through Direct](https://en.wikipedia.org/wiki/SCSI_Pass-Through_Direct) (It's proprietary).

The following tests should be performed to isolate the problem.
1. If Full Toc is correct in Linux or macOS using PX-760 and DIC, this is Windows SPTI problem. If not so, this may be a PX-760 issue when SPTI is used.
2. If Full Toc is correct using DIC and other PX-760, this may be your PX-760 problem. But CDM can get a correct Full Toc, so it may be unlikely.

**Comment by epa-dha** [comment]
Isn't CDM 2.70 Final compatible with SPTI? Since I'm using  Windows 11, I don't think the ASPI driver is installed.
![cdm-screenshot](https://github.com/user-attachments/assets/a5afcb6c-6e75-4262-9281-d25875a81836)

**Comment by epa-dha** [comment]
I have a dual installation of Windows and Ubuntu, so I switched to Ubuntu, made DIC, and tried running. UGREEN's adapter is also working on real Ubuntu. The result is the same as in Windows. The values in the last three lines of entry 13 are equally incorrect.


For DIC & PX-760

[Entry 13]
Session=1
Point=0x0b
ADR=0x01
Control=0x00
TrackNo=0
AMin=0
ASec=0
AFrame=0
ALBA=-150
Zero=0
PMin=58
PSec=0
PFrame=0
PLBA=260850


For CDM & PX-760, DIC & other drives

[Entry 13]
Session=1
Point=0x0b
ADR=0x01
Control=0x00
TrackNo=0
AMin=0
ASec=0
AFrame=0
ALBA=-150
Zero=0
PMin=58
PSec=8
PFrame=20
PLBA=261470

**Comment by saramibreak** [comment]
> Isn't CDM 2.70 Final compatible with SPTI? Since I'm using Windows 11, I don't think the ASPI driver is installed.

Ah, sorry. CDM supports SPTI.

----
I recalled that this problem was reported in 2017. http://forum.redump.org/post/55534/#p55534

I don't know the cause, but I changed the fulltoc buffer size anyway.
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/18167245/DiscImageCreator_test.zip)

**Comment by epa-dha** [comment]
On my PX-760, it was the same when I ripped a music CD with DAEMON Tools. I don't know if it's a problem with the model or just the individual I have, but it's difficult to use this regularly for ripping music CDs. It's an excellent drive, though.

**Comment by saramibreak** [comment]
> Regarding CDM, in the case of the PX-760, the correct ccd file cannot be obtained unless the "Analyze Sub Code(Get Accurately TOC)" is checked in the option settings. There may be a hint here.

I confirmed it by the source code that fulltoc is overwritten by the sub Q channel when "Analyze Sub Code" is enabled.

----
To resolve this problem, fulltoc must be overwritten. CDM uses sub Q, but I’ll implement the code that fulltoc is overwritten by TOC.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/18194536/DiscImageCreator_test.zip)
added /toc option
```
/toc    Full TOC is overwritten by TOC
```

**Comment by epa-dha** [comment]
My problem has just been solved!! I made a fuss. It looks like there was a problem with UGREEN's adapter that converts IDE to USB. The product was compatible with optical drives, but it seems that the IDE was not perfect. Instead, I connected it with TIMELY's Groovy UD-500SA, and both DIC and other software worked perfectly!! The UD series of this company has sold a total of more than 1.2 million units, and has a proven track record. UGREEN's product is USB 3.0 and this one is USB 2.0, but it should be enough for an optical drive.

Now that the issue has been resolved, I would like to close this thread. Thank you very much.

**Comment by saramibreak** [comment]
> It looks like there was a problem with UGREEN's adapter that converts IDE to USB. The product was compatible with optical drives, but it seems that the IDE was not perfect. Instead, I connected it with TIMELY's Groovy UD-500SA, and both DIC and other software worked perfectly!!

Thanks good info. I am glad to have solved a long-standing problem.

**Comment by periodic1236** [comment]
> UGREEN's product is USB 3.0 and this one is USB 2.0, but it should be enough for an optical drive.

I've tested many adapters from different brands. No USB 3.x adapter has worked, while USB 2.0 seems to be the way to go.
