### ISSUE TITLE
Linux build with makefile won't create a *.dat file

### ISSUE THREAD

**Issue by pseiler** [saramibreak/DiscImageCreator#31]
When I use a self-compiled version of DiscImageCreator I get the following error. I don't know where this comes from. Is this some escaping error? The result is, that the *.dat file won't be created. Everything else seems fine. ISO Creation and all other text file generations work perfect.

Also when I use the linux tarball from your release(s) the dat will be created with the same parameters I used in my self-compiled version.

```
[F:ReadWriteDat][L:397] GetLastError: 2, No such file or directory
```

This is the full output including my command line arguments.

```
philipp@feynman ~ [0] $ DiscImageCreator dvd /dev/sr0 abba/SingStar\ ABBA\ \(Germany\).iso 8
AppVersion
        x64, AnsiBuild, 20190701 171607
CurrentDirectory
        /home/philipp
WorkingPath
         Argument: abba/SingStar ABBA (Germany).iso
         FullPath: /home/philipp/abba/SingStar ABBA (Germany).iso
            Drive: /
        Directory: home/philipp/abba/
         Filename: SingStar ABBA (Germany)
        Extension: .iso
StartTime: 2019/07/07(Sun) 16:31:28
[F:SetDiscSpeed][L:660] GetLastError: 1, Operation not permitted
Please wait for 25000 milliseconds until the device is returned
Reading DirectoryRecord    3/   3
Creating iso(LBA)  1586736/ 1586736
[F:ReadWriteDat][L:397] GetLastError: 2, No such file or directory
EndTime: 2019/07/07(Sun) 16:39:34
```

**Comment by saramibreak** [comment]
It needs default.dat. See linux tarball of my release.

**Comment by pseiler** [comment]
@saramibreak This sounds good. Could the path be variable and search for /usr/local/share/DiscImageCreator and /usr/share/DiscImageCreator?

This is useful to package the program and integrate it into Linux distributions.
Am I correct that the path is set on Line 389 in xml.cpp?

**Comment by saramibreak** [comment]
default.dat needs to be placed in the same directory as DiscImageCreator.out

**Comment by pseiler** [comment]
As I've already written a variable path would be much better, so it can be integrated into Linux distributions with a proper packaging. Have a look at this
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

So the correct path on Unix systems would be /usr/share/DiscImageCreator or /usr/local/share/DiscImageCreator.
This change could only be applied to Unix systems. 
If I would do this, would you accept the pull request?

**Comment by saramibreak** [comment]
I leave this to you.

**Comment by pseiler** [comment]
Sorry for the late answer. Will work on this the next days
