### ISSUE TITLE
Offset feature (/a) and Mixed-mode CD

### ISSUE THREAD

**Issue by Lutepatious** [saramibreak/DiscImageCreator#35]
I need rip Mixed-mode cd with offset feature (/a option and driveOffset.txt).
I also need overread feature with Mixed-mode CD.

These feature needed by some Japanese PC (etc. FM Towns, PC=9801) CD games.

**Comment by saramibreak** [comment]
You should prepare specific drives written in README.md

**Comment by Lutepatious** [comment]
Ohh, I have 2 Plextor PX-760.

	      Signature: a3 03
	       VendorId: PLEXTOR 
	      ProductId: DVDR   PX-760A  
	   SerialNumber: 411400

and
	      Signature: a3 03
	       VendorId: PLEXTOR 
	      ProductId: DVDR   PX-760A  
	   SerialNumber: 411401
