### ISSUE TITLE
Dot handling in path

### ISSUE THREAD

**Issue by superg** [saramibreak/DiscImageCreator#37]
Hey,
You accepted my pull request half a year ago where I rewrote pathSplit() function to support dots in a path so paths like "Interactive CD Sampler Disc Vol. 9 (USA)/Interactive CD Sampler Disc Vol. 9 (USA).bin" are handled correctly.
It stopped working recently when I updated my DICUI which bundles updated DiscImageCreator. I started to look into it and I see that you disabled my fix in commit "- added: support multiple files in C2ErrorProtect.txt (MAX 16 files)" on November 10, 2019.
Was there a reason for this? Did I break something?
Commit: https://github.com/saramibreak/DiscImageCreator/commit/05fda7da824dc378a159dda3ed54fe68515eb994#diff-ed7acfc1a28fe2c204ad2a65c1b11b83

**Comment by saramibreak** [comment]
http://forum.redump.org/post/74041/#p74041

**Comment by superg** [comment]
I think I fixed it, more details in your thread:
http://forum.redump.org/post/76449/#p76449

**Comment by saramibreak** [comment]
Not work.
CurrentDirectory is D:\temp
Argument is "ISO\TEST Vol. 9 (USA)\TEST Vol_ 9 (USA)"

**Comment by saramibreak** [comment]
http://forum.redump.org/post/76513/#p76513

**Comment by superg** [comment]
sarami, I fixed the last issue and updated the pull request.
Every dot before the last path delimiter is treated as part of the path.
