### ISSUE TITLE
Missing info from _disc.txt

### ISSUE THREAD

**Issue by tomthumb876** [saramibreak/DiscImageCreator#39]
Several things are missing from the _disc.txt file in certain cases.

The most important of these (and easiest to fix) is that the "DiscInformation" section is omitted entirely for CD-R(W) ("TOC ATIP" section is given instead). For CD-R(W), the "TOC ATIP" and "DiscInformation" should both be included. This should just be a simple matter of adding one additional call to ReadDiscInformation ( ), I think?

Then, two significant pieces of information for CD-R(W) are not included anywhere: "Disc(Matrix) Manufacturer" and "Recording Characteristics" (dye type). Other programs such as "CDR ATIP Reader" do include these. Though often unreliable, it would be very useful to have the data the drive returns for this and would make the DIC output more complete.

Finally, I would really appreciate if you could add the code to request the PMA Descriptors (format field = 0x03 in "READ TOC/PMA/ATIP" command) when they are present, and list the raw data for these in the _disc.txt output. This is the only remaining data not currently retrieved from the disc by DIC and can be helpful for troubleshooting with some discs.

**Comment by saramibreak** [comment]
http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file
- added: call ReadDiscInformation if disc is CD-R/RW
- added READ TOC/PMA

> two significant pieces of information for CD-R(W) are not included anywhere: "Disc(Matrix) Manufacturer" and "Recording Characteristics" (dye type).

Do you know which sectors store it?

**Comment by tomthumb876** [comment]
Thanks very much for your prompt attention with this.

- DiscInformation now shows up correctly for CD-R(W), thank you.

- PMA info is still not showing up anywhere, does this now mean that zero PMA Descriptors were returned by the drive? ("PMA Data Length" = 0) Or, did the attempt to read the Descriptors fail? PMA Data Length of zero is expected for most discs, but for the avoidance of doubt it would be good to have DIC explicitly report in _disc.txt that the PMA is empty if no Descriptors are returned.

- For details on how "Disc(Matrix) Manufacturer" and "Recording Characteristics" are stored, see this doc: http://web.archive.org/web/20061027043819/www.cdr-forum.de/download/cdr.pdf

After looking at this doc, it's now apparent that these data are encoded in the TOC ATIP "LeadInMsf" and simply need to be interpreted and displayed in human-readable form. (The raw LeadInMsf value should still be displayed as well for reference, of course.)

A typical example of formatted output from CDR ATIP Reader is here: https://club.myce.com/t/what-subtype-and-target-writting-power-exactly-mean/52837

Of course, since the raw data for these disc traits is in fact already logged in the DIC output, you may or may not decide it's worth it to print them in human-readable form. I do think it would be worthwhile to do, especially given how few people would be readily able to look them up in the relevant doc(s). However, I certainly understand if it's not a priority for you.

**Comment by saramibreak** [comment]
Updated test version. (link is same)

**Comment by tomthumb876** [comment]
Excellent, everything looks just about perfect now! Just a question about the "Recording characteristics". I got the following for a test disc:

```
	         LeadInMsf: 97:24:16
	          => Manufacturer: SONY Corporation
              => Recording characteristics: Long Strategy Type (ex. Cyanine type media)
```

From the doc, it appears this should be the "Short Strategy Type" (second digit of frame = 5~9), I think? Have I misinterpreted the doc?

Otherwise, everything now seems perfect.

**Comment by saramibreak** [comment]
Updated. Link is same.

**Comment by tomthumb876** [comment]
Works flawlessly now with all the discs I've been testing. Thanks very much for the diligent work to get it perfect!

Before I close this issue, can I just ask you a quick unrelated question, maybe you'll know the answer since you test so many optical drives: have you found any drive model (supported by DIC) that is capable of reading audio-mode sectors from LBA -150 to -76 (AMSF 00:00:00 ~ 00:00:74)? I've tried many models including PX-W4012 and PX-W5224 and so far none can do it (errors "ILLEGAL_REQUEST - ILLEGAL MODE FOR THIS TRACK", etc). They can successfully read the subchannels for those sectors, but never the main-channel. I have some discs that have audio in those sectors and would love to be able to dump them fully. Sorry for the off-topic question but any advice you have there would be much appreciated, if not then we can close this issue. Thanks again!

**Comment by saramibreak** [comment]
Thank you, too. Your info is very precious to me :)

> between LBA -150 and -76

Try to use /p flag without /c2 flag

>         /p      Dumping the AMSF from 00:00:00 to 00:01:74
>                      For SagaFrontier Original Sound Track (Disc 3) etc.
>                       Support drive: PLEXTOR PX-W5224, PREMIUM, PREMIUM2
>                                      PX-704, 708, 712, 714, 716, 755, 760

**Comment by tomthumb876** [comment]
Eureka! I was already using /p, but didn't think of removing /c2. It works perfectly and I'm now able to get all the data in those sectors. It's unfortunate to have to sacrifice the c2 error correction to get them, but I suppose that can't be helped as probably no drive will allow retrieving those sectors with the error correction on?

Anyway, quite an improvement! Thanks again and I hope you'll release the finalized package with these new corrections soon, as I'm eager to start using it for all of my dumps. :)

**Comment by saramibreak** [comment]
> but didn't think of removing /c2.

I have noticed that recently too. Perhaps this is a specification of plextor drive.
