### ISSUE TITLE
Small oversight in new gap detection logic

### ISSUE THREAD

**Issue by tomthumb876** [saramibreak/DiscImageCreator#40]
Looking at the new gap detection logic, I see that you missed an edge case: what if the 1st Q-sector of a track has MCN/ISRC, yet this track does NOT have an Index00? In other words, a jump directly from Track n Index01 to Track n+1 Index01, with MCN/ISRC in the 1st Q-sector of Track n+1. It looks like your code will fail to catch this and increment the track count.

I guess the solution is to add in set.cpp at line 830 as follows:

```
		else if ((pDiscPerSector->subch.current.byP == 0xff && pDiscPerSector->subch.next.byP == 0x00 &&
			pDiscPerSector->subch.prev.byTrackNum + 1 == pDiscPerSector->subch.next.byTrackNum)) {
			tmpCurrentTrackNum = pDiscPerSector->subch.next.byTrackNum;
		}
```

But please double-check if the above is sufficient to handle this case, as I'm not entirely familiar with your code of course! ;)

**Comment by saramibreak** [comment]
Thanks. Updated the branch. Check plz.

**Comment by tomthumb876** [comment]
Looks good now. Unfortunately it can't easily be tested in action (since I don't know offhand of a disc where this edge case occurs), but the reworked version in the latest commit doesn't have any remaining problems that I can see. I'll update this Issue in the future if I ever discover any further issues with the gap detection, thanks again for the quick fix!
