### ISSUE TITLE
Press any key instead of timeout with swap method

### ISSUE THREAD

**Issue by Pantsi** [saramibreak/DiscImageCreator#44]
Hello,

Having a couple of slot in and laptop readers that cannot auto load the disc back in. 
Can we have a pause and wait for input instead of timeout on these drives maybe by input switch?

Thanks.

**Comment by saramibreak** [comment]
Uploaded test version. http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file
But I can't test it because I don't have a slot mechanism drive.

**Comment by Pantsi** [comment]
Thanks, but i now i have a diffrent problem. 
It giving me an vcruntime crash with all version except versions before release 20191223

Maybe this drive is incompatible?

Logs: https://www.mediafire.com/file/j138wjno94vhkkn/test_%5Btest%5D.7z/file

**Comment by saramibreak** [comment]
Try to update the redistributable package.
https://aka.ms/vs/16/release/VC_redist.x86.exe

**Comment by Pantsi** [comment]
Same problem, but newer version number.

Problem Event Name:	APPCRASH
Application Name:	DiscImageCreator.exe
Application Version:	0.0.0.0
Application Timestamp:	5e61d98a
Fault Module Name:	VCRUNTIME140.dll
Fault Module Version:	14.24.28127.4
Fault Module Timestamp:	5d8e68be
Exception Code:	c0000005
Exception Offset:	00003380
OS Version:	6.1.7601.2.1.0.256.48
Locale ID:	1053
Additional Information 1:	0a9e
Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
Additional Information 3:	0a9e
Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Also tested with a fresh install of win 10 1903 on same computer with the same .net installation you posted. 

Faulting application name: DiscImageCreator.exe, version: 0.0.0.0, time stamp: 0x5e61d98a
Faulting module name: VCRUNTIME140.dll, version: 14.24.28127.4, time stamp: 0x5d8e68be
Exception code: 0xc0000005
Fault offset: 0x00003380
Faulting process ID: 0x1a10
Faulting application start time: 0x01d5fc6b7076a766
Faulting application path: I:\DiscImageCreator\Release_ANSI\DiscImageCreator.exe
Faulting module path: C:\Windows\SYSTEM32\VCRUNTIME140.dll
Report ID: ac649d53-49b1-4b5b-8217-ab3361c7778d
Faulting package full name: 
Faulting package-relative application ID:

Dumping with dvd switch works flawless.
Not tested with versions from release tab.

Win 7 was with swedish language, win 10 was with english if that should be a problem.

Just ask if you want me to test something more :)

**Comment by saramibreak** [comment]
Sorry, swap command didn't work from 20191223.
Updated test version http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file

**Comment by Pantsi** [comment]
Swap works great again, but still 3000 msec timeout with the test version.

**Comment by saramibreak** [comment]
> 3000 msec timeout

I use it intentionally to get the drive's object handle again.
