### ISSUE TITLE
Creator tries to read past end of DVD+R

### ISSUE THREAD

**Issue by SilasLaspada** [saramibreak/DiscImageCreator#45]
When trying to dump a DVD+R that other software dumps fine (Alcohol 120% and ImgBurn), creator crashes after trying to read past the end of the DVD. The progress also has an incorrect end number while dumping. Dumped using two separate drives with the same result both times. Command window output: 
"AppVersion
        x86, AnsiBuild, 20200204 162151
CurrentDirectory
        F:\DiscImageCreator
WorkingPath
         Argument: test.iso
         FullPath: F:\DiscImageCreator\test.iso
            Drive: F:
        Directory: \DiscImageCreator\
         Filename: test
        Extension: .iso
StartTime: 2020/03/08(Sun) 23:53:32
Set the drive speed: 11080KB/sec
LBA[000000, 0000000]: [F:ReadDiscStructure][L:1293]
        Opcode: 0xad
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
FormatCode: 30 failed
LBA[310336, 0x4bc40]: [F:ReadDVD][L:305]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Read retry 1/5
LBA[310336, 0x4bc40]: [F:ReadDVD][L:305]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Read retry 2/5
LBA[310336, 0x4bc40]: [F:ReadDVD][L:305]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Read retry 3/5
LBA[310336, 0x4bc40]: [F:ReadDVD][L:305]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Read retry 4/5
LBA[310336, 0x4bc40]: [F:ReadDVD][L:305]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Read retry 5/5
LBA[310336, 0x4bc40]: [F:ReadDVD][L:305]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
Retry NG"
Log files: [DiscImageCreator.zip](https://github.com/saramibreak/DiscImageCreator/files/4304889/DiscImageCreator.zip)

**Comment by saramibreak** [comment]
Please tell me this "yyyyy" in command-line screen.

`Creating iso(LBA)     xxxx/ yyyyy`

**Comment by SilasLaspada** [comment]
The "yyyyy" is 2294912.

**Comment by saramibreak** [comment]
Updated test version http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file

**Comment by SilasLaspada** [comment]
I can confirm it as fixed! I'll be happy to close this once the fix is in master.
