### ISSUE TITLE
"Drive is not updated to the latest firmware" error

### ISSUE THREAD

**Issue by yudilevi2** [saramibreak/DiscImageCreator#47]
Hi,

When trying to dump a disc with the latest release, DIC shows an error that the drive firmware isn't updated to the latest version even though it does.

DIC Version: 20200403
Drive Model: Plextor PX-755UF
Drive Firmware: 1.08

Thanks

**Comment by saramibreak** [comment]
Show me the _drive.txt plz.
Here is my 755

>
	            VendorId: PLEXTOR 
	           ProductId: DVDR   PX-755A  
	ProductRevisionLevel: 1.08
	      VendorSpecific: 08/18/07  15:10

**Comment by touche112** [comment]
I have the same problem with my LG (HL-DT-ST) BU40N.  Latest firmware is installed on the drive.

`========== StorageAdapterDescriptor ==========
	              Version: 32
	                 Size: 32
	MaximumTransferLength: 65536 (bytes)
	 MaximumPhysicalPages: 17
	        AlignmentMask: 0 (Buffers must be aligned on BYTE boundaries)
	       AdapterUsesPio: False
	     AdapterScansDown: False
	      CommandQueueing: False
	  AcceleratedTransfer: False
	              BusType: BusTypeUsb
	      BusMajorVersion: 2
	      BusMinorVersion: 0
========== InquiryData ==========
	          DeviceType: ReadOnlyDirectAccessDevice (CD/DVD etc)
	 DeviceTypeQualifier: Active
	  DeviceTypeModifier: 0
	      RemovableMedia: Yes
	            Versions: 0
	  ResponseDataFormat: 2
	           HiSupport: Yes
	             NormACA: Yes
	       TerminateTask: No
	                AERC: No
	    AdditionalLength: 91
	       MediumChanger: No
	           MultiPort: No
	   EnclosureServices: No
	           SoftReset: No
	        CommandQueue: No
	      LinkedCommands: No
	  RelativeAddressing: No
	            VendorId: HL-DT-ST
	           ProductId: BD-RE BU40N     
	ProductRevisionLevel: 1.03
	      VendorSpecific: NM00000MO2J81G4344  
========== GetConfiguration ==========
	    DataLength: 188
	CurrentProfile: CD-ROM
	FeatureProfileList
		BD-RW
		BD-R Random Writable
		BD-R Sequential Writable
		BD-ROM
		DVD+R DL
		DVD+R
		DVD+RW
		DVD-R Layer Jump
		DVD-R DL
		DVD-RW Sequential
		DVD-RW
		DVD-RAM
		DVD-R
		DVD-ROM
		CD-RW
		CD-R
		CD-ROM
		RemovableDisk
	FeatureCore
		PhysicalInterface: Serial ATAPI
		  DeviceBusyEvent: Yes
		         INQUIRY2: No
	FeatureMorphing
		Asynchronous: No
		     OCEvent: Yes
	FeatureRemovableMedium
		        Lockable: Yes
		DefaultToPrevent: No
		           Eject: Yes
		LoadingMechanism: Tray type loading mechanism
	FeatureRandomReadable
		        LogicalBlockSize: 2048
		                Blocking: 1
		ErrorRecoveryPagePresent: Yes
	FeatureMultiRead
		   Current: 1
		Persistent: 0
		   Version: 0
	FeatureCdRead
		          CDText: Yes
		     C2ErrorData: Yes
		DigitalAudioPlay: No
	FeaturePowerManagement
		   Current: 1
		Persistent: 1
		   Version: 0
	FeatureTimeout
		    Group3: No
		UnitLength: 0
	FeatureRealTimeStreaming
		        StreamRecording: Yes
		    WriteSpeedInGetPerf: Yes
		       WriteSpeedInMP2A: Yes
		             SetCDSpeed: Yes
		ReadBufferCapacityBlock: Yes
	FeatureLogicalUnitSerialNumber
		SerialNumber: MO2J81G4344 
	FeatureFirmwareDate: 2118-10-24 19:34:  
========== SetSpeed ==========
	    RequestType: CdromSetSpeed
	      ReadSpeed: 8467KB/sec
	     WriteSpeed: 0KB/sec
	RotationControl: CdromDefaultRotation
========== ReadBufferCapacity ==========
	    TotalBufferSize: 2956KByte
	AvailableBufferSize: 2956KByte
========== ModeParmeterHeader10 ==========
	           ModeDataLength: 266
	               MediumType: 1
	  DeviceSpecificParameter: 0
	    BlockDescriptorLength: 0
========== MODE_READ_WRITE_RECOVERY_PAGE ==========
	                 PageCode: 0x01
	              PageSavable: No
	               PageLength: 10
	                   DCRBit: No
	                   PERBit: No
	                   EERBit: No
	                    RCBit: No
	                    TBBit: No
	                     ARRE: No
	                     AWRE: No
	           ReadRetryCount: 32
	          WriteRetryCount: 0
========== MODE_CDROM_WRITE_PARAMETERS_PAGE ==========
	                 PageCode: 0x05
	              PageSavable: No
	               PageLength: 50
	                WriteType: 1
	                TestWrite: No
	            LinkSizeValid: No
	BufferUnderrunFreeEnabled: No
	                TrackMode: 4
	                     Copy: No
	              FixedPacket: No
	             MultiSession: 0
	            DataBlockType: 8
	                 LinkSize: 0
	      HostApplicationCode: 0
	            SessionFormat: 0
	               PacketSize: 32
	         AudioPauseLength: 150
	       MediaCatalogNumber:                 
	                     ISRC:                 
	            SubHeaderData: 0
========== MODE_CACHING_PAGE ==========
	                 PageCode: 0x08
	              PageSavable: No
	               PageLength: 10
	         ReadDisableCache: No
	     MultiplicationFactor: No
	         WriteCacheEnable: Yes
	   WriteRetensionPriority: 0
	    ReadRetensionPriority: 0
	  DisablePrefetchTransfer: 0
	          MinimumPrefetch: 0
	          MaximumPrefetch: 0
	   MaximumPrefetchCeiling: 0
========== CD_DEVICE_PARAMETERS_PAGE ==========
	                 PageCode: 0x0d
	                    PSBit: No
	               PageLength: 6
	InactivityTimerMultiplier: 0
	 TheNumberOfSUnitPerMUnit: 60
	 TheNumberOfFUnitPerSUnit: 75
========== CDAUDIO_CONTROL_PAGE ==========
	                 PageCode: 0x0e
	                    PSBit: No
	               PageLength: 14
	      StopOnTrackCrossing: No
	                Immediate: Yes
	      ChannelSelection[0]: 1
	                Volume[0]: 255
	      ChannelSelection[1]: 2
	                Volume[1]: 255
	      ChannelSelection[2]: 0
	                Volume[2]: 0
	      ChannelSelection[3]: 0
	                Volume[3]: 0
========== CDVD_FEATURE_SET_PAGE ==========
	                 PageCode: 0x18
	                    PSBit: No
	               PageLength: 26
	                  CDAudio: 1
	          EmbeddedChanger: 1
	              PacketSMART: 0
	        PersistantPrevent: 0
	  EventStatusNotification: 1
	            DigitalOutput: 1
	   CDSequentialRecordable: 0
	  DVDSequentialRecordable: 0
	         RandomRecordable: 0
	              KeyExchange: 0
========== POWER_CONDITION_PAGE ==========
	                 PageCode: 0x1a
	                    PSBit: No
	               PageLength: 10
	                  Standby: Yes
	                     Idle: Yes
	                IdleTimer: 100
	             StandbyTimer: 320
========== FAULT_REPORTING ==========
	                 PageCode: 0x1c
	                    PSBit: Yes
	               PageLength: 10
	                  Unknown: 9c0a0004000002580000
========== CDVD_INACTIVITY_TIMEOUT_PAGE ==========
	                 PageCode: 0x1d
	                    PSBit: No
	               PageLength: 10
	                     SWPP: No
	                     DISP: No
	   GroupOneMinimumTimeout: 9
	   GroupTwoMinimumTimeout: 10800
========== Unknown ==========
	                 PageCode: 0x20
	                    PSBit: No
	               PageLength: 10
	                  Unknown: 200a0100006400030000
========== CDVD Capabilities & Mechanism Status Page ==========
	                 PageCode: 0x2a
	                    PSBit: No
	               PageLength: 66
	                  CDRRead: Yes
	                  CDERead: Yes
	                  Method2: Yes
	               DVDROMRead: Yes
	                 DVDRRead: Yes
	               DVDRAMRead: Yes
	                 CDRWrite: Yes
	                 CDEWrite: Yes
	                TestWrite: Yes
	                DVDRWrite: Yes
	              DVDRAMWrite: Yes
	                AudioPlay: Yes
	                Composite: No
	           DigitalPortOne: No
	           DigitalPortTwo: No
	               Mode2Form1: Yes
	               Mode2Form2: Yes
	             MultiSession: Yes
	       BufferUnderrunFree: Yes
	                     CDDA: Yes
	             CDDAAccurate: Yes
	              RWSupported: Yes
	          RWDeinterleaved: No
	               C2Pointers: Yes
	                     ISRC: Yes
	                      UPC: Yes
	       ReadBarCodeCapable: No
	                     Lock: Yes
	                LockState: No
	            PreventJumper: No
	                    Eject: Yes
	     LoadingMechanismType: tray
	           SeparateVolume: Yes
	      SeperateChannelMute: Yes
	      SupportsDiskPresent: No
	          SWSlotSelection: No
	        SideChangeCapable: No
	       RWInLeadInReadable: Yes
	         ReadSpeedMaximum: 4234KB/sec (24x)
	       NumberVolumeLevels: 256
	               BufferSize: 4064
	         ReadSpeedCurrent: 4234KB/sec (24x)
	                      BCK: No
	                      RCK: No
	                     LSBF: No
	                   Length: 1
	        WriteSpeedMaximum: 4234KB/sec (24x)
	        WriteSpeedCurrent: 0KB/sec (0x)
	   CopyManagementRevision: 1
========== Check main + c2 + sub ==========
========== LBA[000000, 0000000]: C2 error ==========
       +0 +1 +2 +3 +4 +5 +6 +7
0000 : 00 00 00 00 00 00 00 00
0008 : 00 00 00 00 00 00 00 00
0010 : 00 00 00 00 00 00 00 00
0018 : 00 00 00 00 00 00 00 00
0020 : 00 00 00 00 00 00 00 00
0028 : 00 00 00 00 00 00 00 00
0030 : 00 00 00 00 00 00 00 00
0038 : 00 00 00 00 00 00 00 00
0040 : 00 00 00 00 00 00 00 00
0048 : 00 00 00 00 00 00 00 00
0050 : 00 00 00 00 00 00 00 00
0058 : 00 00 00 00 00 00 00 00
0060 : 00 00 00 00 00 00 00 00
0068 : 00 00 00 00 00 00 00 00
0070 : 00 00 00 00 00 00 00 00
0078 : 00 00 00 00 00 00 00 00
0080 : 00 00 00 00 00 00 00 00
0088 : 00 00 00 00 00 00 00 00
0090 : 00 00 00 00 00 00 00 00
0098 : 00 00 00 00 00 00 00 00
00A0 : 00 00 00 00 00 00 00 00
00A8 : 00 00 00 00 00 00 00 00
00B0 : 00 00 00 00 00 00 00 00
00B8 : 00 00 00 00 00 00 00 00
00C0 : 00 00 00 00 00 00 00 00
00C8 : 00 00 00 00 00 00 00 00
00D0 : 00 00 00 00 00 00 00 00
00D8 : 00 00 00 00 00 00 00 00
00E0 : 00 00 00 00 00 00 00 00
00E8 : 00 00 00 00 00 00 00 00
00F0 : 00 00 00 00 00 00 00 00
00F8 : 00 00 00 00 00 00 00 00
0100 : 00 00 00 00 00 00 00 00
0108 : 00 00 00 00 00 00 00 00
0110 : 00 00 00 00 00 00 00 00
0118 : 00 00 00 00 00 00 00 00
0120 : 00 00 00 00 00 00 80 C0
========== LBA[000000, 0000000]: Sub Channel(Raw) ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 80 C0 80 80 80 80 80 C0  80 80 80 80 80 80 80 C0
0010 : 80 80 80 80 80 80 80 C0  80 80 80 80 80 80 80 80
0020 : 80 80 80 80 80 80 80 80  80 80 80 80 80 80 80 80
0030 : 80 80 80 80 80 80 80 80  80 80 80 80 80 80 80 80
0040 : 80 80 80 80 80 80 C0 80  80 80 80 80 80 80 80 80
0050 : 80 80 C0 80 C0 80 80 80  80 80 C0 C0 80 80 C0 80
========== Check main + sub + c2 ==========
========== LBA[000000, 0000000]: Sub Channel(Raw) ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
0010 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
0020 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
0030 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
0040 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
0050 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
========== LBA[000000, 0000000]: C2 error ==========
       +0 +1 +2 +3 +4 +5 +6 +7
0000 : 00 00 00 00 00 00 00 00
0008 : 00 00 00 00 00 00 00 00
0010 : 00 00 00 00 00 00 00 00
0018 : 00 00 00 00 00 00 00 00
0020 : 00 00 00 00 00 00 00 00
0028 : 00 00 00 00 00 00 00 00
0030 : 00 00 00 00 00 00 00 00
0038 : 00 00 00 00 00 00 00 00
0040 : 00 00 00 00 00 00 00 00
0048 : 00 00 00 00 00 00 00 00
0050 : 00 00 00 00 00 00 00 00
0058 : 00 00 00 00 00 00 00 00
0060 : 00 00 00 00 00 00 00 00
0068 : 00 00 00 00 00 00 00 00
0070 : 00 00 00 00 00 00 00 00
0078 : 00 00 00 00 00 00 00 00
0080 : 00 00 00 00 00 00 00 00
0088 : 00 00 00 00 00 00 00 00
0090 : 00 00 00 00 00 00 00 00
0098 : 00 00 00 00 00 00 00 00
00A0 : 00 00 00 00 00 00 00 00
00A8 : 00 00 00 00 00 00 00 00
00B0 : 00 00 00 00 00 00 00 00
00B8 : 00 00 00 00 00 00 00 00
00C0 : 00 00 00 00 00 00 80 C0
00C8 : 80 80 80 80 80 C0 80 80
00D0 : 80 80 80 80 80 C0 80 80
00D8 : 80 80 80 80 80 C0 80 80
00E0 : 80 80 80 80 80 80 80 80
00E8 : 80 80 80 80 80 80 80 80
00F0 : 80 80 80 80 80 80 80 80
00F8 : 80 80 80 80 80 80 80 80
0100 : 80 80 80 80 80 80 80 80
0108 : 80 80 80 80 C0 80 80 80
0110 : 80 80 80 80 80 80 80 80
0118 : C0 80 C0 80 80 80 80 80
0120 : C0 C0 80 80 C0 80 00 00
	Byte order of this drive is main + c2 + sub
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 0]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 1]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 2]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 4]
Checking reading lead-in -> OK
`

**Comment by saramibreak** [comment]
BU40N is not defined yet in driveOffset.txt

**Comment by touche112** [comment]
> BU40N is not defined yet in driveOffset.txt

Correct. I entered my own offset when prompted, which is +6.

**Comment by Qwest8K** [comment]
And I also got this problem with ASUS BW-16D1HT (firmware 3.02).

**Comment by saramibreak** [comment]
https://github.com/SabreTools/DICUI/issues/199

**Comment by bleggett** [comment]
Same error with PX-712 - drive has firmware 1.09 but looks like DIC is expecting 1.08

**Comment by yudilevi2** [comment]
@saramibreak here's my `_drive.txt` file -
[_drive.txt](https://github.com/saramibreak/DiscImageCreator/files/4571390/_drive.txt)

**Comment by yudilevi2** [comment]
@saramibreak is this issue resolved in the next version?

**Comment by saramibreak** [comment]
Are you DICUI user? If yes, use 1.16.1 plz.

**Comment by yudilevi2** [comment]
oh cool - thanks.
