### ISSUE TITLE
date/time format

### ISSUE THREAD

**Issue by fuzz6001** [saramibreak/DiscImageCreator#49]
Can DIC adopt "ISO 8601" as the date/time format?

e.g.
```
current:  Recording Date and Time: 1999-01-17 01:00:00 +00:00
ISO 8601: Recording Date and Time: 1999-01-17T01:00:00+00:00
```

**Comment by saramibreak** [comment]
Uploaded test version. http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file

**Comment by fuzz6001** [comment]
Looks like it's working. Thank you.
