### ISSUE TITLE
CAB Extraction crashes DIC entirely

### ISSUE THREAD

**Issue by Whovian9369** [saramibreak/DiscImageCreator#53]
DIC Crashes when trying to extract CAB files of a Windows 95 disc, and it's a very reproducible issue.
I was trying to dump this disc for myself using [DICUI - Version 1.16-317 from AppVeyor](https://ci.appveyor.com/project/mnadareski/dicui/builds/33564893/artifacts) (which itself is using `DIC x86, AnsiBuild, 20200604T002233`) but for whatever reason, DIC tried extracting all the CAB ~~(even without `/sf` being added to the original DIC Command as well)~~ and then ended up crashing before it got to the actual dumping stage.

Example screenshot of error on a Windows 7 machine:
![DIC_Crash_CABExtracting_Win95](https://user-images.githubusercontent.com/5240754/85956120-94504700-b951-11ea-9bae-d6413535fc05.PNG)

**Comment by saramibreak** [comment]
Cab extraction starts when /sf or /ns is uses.
I don't know the cause of the crashing issue yet.

**Comment by Whovian9369** [comment]
> Cab extraction starts when /sf or /ns is used.
Did a test dump (one with CLI and DICUI) and the dumps worked since I didn't use `/sf` or `/ns`, despite earlier testing showing otherwise. Weird, but hey at least it worked there.

Anyway the crash is still a thing, annoyingly. Thanks for your time!

**Comment by Whovian9369** [comment]
So was able to get the latest DIC running *on Linux* (with another disc that crashes DIC with this error on Windows) just fine, since it doesn't seem to do CAB Extraction/Examination on Linux.

Please double check to see if there's a solution with the specific programs you're using on the Windows builds, since something seems to be very stupidly wrong there. If there isn't a solution, please do disable the cab scan by default. (Maybe have it as an opt-in flag so people can still use/test it as they need to, but it isn't run as default?)

**Comment by saramibreak** [comment]
Uploaded test version. http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file
- fixed: crash when /ns is used by some disc

**Comment by Whovian9369** [comment]
Works as expected, thank you!

Working log of same disc as original report, as ran via [cmder](https://cmder.net/) | Using my BW-16D1HT drive for this test: https://mystb.in/raw/TexasMailsHungarian
