### ISSUE TITLE
Dumping process freezing at lead-in reading checking

### ISSUE THREAD

**Issue by Qwest8K** [saramibreak/DiscImageCreator#54]
When I try to dump discs by my drive ASUS BW-16D1HT (firmware 3.02), dumping process almost everytime hangs after appearing of message "Checking reading lead-in -> OK" and I should stop program through task manager.

**Comment by saramibreak** [comment]
I tried the latest test version, but it does not hang.

**Comment by Qwest8K** [comment]
I insert a new CD for PlayStation 2 into the drive, launch the DICUI (which as well as DIC are last test version), select corresponding Sytem/Media Type and start dumping on full default settings. 
Drive hums for several minutes as during operation and then stops. New messages in command line stop appearing after appearing line "Checking reading lead-in -> OK". And no disk images are created.
Programs also stops responding to any commands, but DICUI is possible to close as usual. But command line window can be closed only through task manager.

**Comment by saramibreak** [comment]
Please try to use the DIC without DICUI.

**Comment by Qwest8K** [comment]
I tried without GUI by first command in wiki. If /c2 option enabled, when dumping hangs as usual. Without it, everything works.

**Comment by saramibreak** [comment]
Do you upload all created files?
I also used ASUS BW-16D1HT (firmware 3.02) and dumping is no problem with /c2.

**Comment by Qwest8K** [comment]
Upload to where?

**Comment by saramibreak** [comment]
In this issue.

**Comment by Qwest8K** [comment]
This is all created files:
https://www.dropbox.com/sh/odf1wnkfg3ucnsx/AAB8NW0ZdiYXD8Vjbn1AxK_sa?dl=0

**Comment by saramibreak** [comment]
Added log in _mainInfo.txt
http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file
Upload files using /c2.

**Comment by Qwest8K** [comment]
Done.
[Files using c2.zip](https://github.com/saramibreak/DiscImageCreator/files/5162669/Files.using.c2.zip)

**Comment by saramibreak** [comment]
I bought the same disc (SLPM-62571) and dumped it. The result is no problem.
Btw, how about other discs? If hanging occurs, it may be your drive problem.

**Comment by Qwest8K** [comment]
Other CDs (not DVDs, BDs not tested) also hanging.

**Comment by saramibreak** [comment]
Then, try to change the drive. I recommend plextor (see README.md).
