### ISSUE TITLE
CAB file checking can be simplified

### ISSUE THREAD

**Issue by mnadareski** [saramibreak/DiscImageCreator#55]
When checking for CAB files that can potentially have multiple parts, if a `CABNAME.HDR` exists, that's the only one that needs to be scanned. Otherwise, only `CABNAME1.CAB` needs to be scanned. This can make things go a lot quicker if you have the flag enabled.

**Comment by saramibreak** [comment]
http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file
- changed: 1st cab or hdr is only extracted

**Comment by mnadareski** [comment]
I'll admit I don't fully understand how your code change addresses this. I'll test it out in the latest release and see if it still occurs.
