### ISSUE TITLE
No _CSSKey.txt outputted after dumping on Linux

### ISSUE THREAD

**Issue by gmipf** [saramibreak/DiscImageCreator#56]
After dumping a DVD-Video with CSS protection, DIC isn't creating any _CSSKey.txt, despite referring to it in the file _disc.txt.

**Comment by saramibreak** [comment]
Yes, because Linux version uses [css_auth](http://www.cs.cmu.edu/~dst/DeCSS/) but windows version uses [DVDAuth](https://github.com/saramibreak/DVDAuth). DVDAuth will support Linux in the future.

**Comment by saramibreak** [comment]
[DiscImageCreator_linux_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/5316394/DiscImageCreator_linux_test.tar.gz)
Updated. Test, plz.

**Comment by gmipf** [comment]
It is working now with the same DVD-Video.
