### ISSUE TITLE
DVD with mastering errors fails to dump

### ISSUE THREAD

**Issue by mnadareski** [saramibreak/DiscImageCreator#57]
Myself and at least one other user have run into an issue with a PS2 DVD with mastering errors, corresponding to a dummy file on the disc. To verify that this was an issue with the DVD, multiple programs were used to generate ISOs, all of which hit the same error in the same sectors. For programs that supported it, filling those sectors with `\0` ended up producing a matching hash for the known information on the disc.

This seems to only affect one particular pressing of this disc as well, since other pressings of the disc have the same dummy file (filled with `\0`) and do not hit the same issue. This is definitely a corner case for handling protected discs.

Attached here is the output logs from the DiscImageCreator run. Of note, it fails on the first of the bad sectors and then entirely stops after 5 attempts: 
[KATAMARI.zip](https://github.com/saramibreak/DiscImageCreator/files/5269812/KATAMARI.zip)

The eventual ask from this is either:
- Add a flag to be able to ignore these read errors for DVD specifically
- Or, to log the error but fill with `\0` bytes in the affected sectors

**Comment by saramibreak** [comment]
I ordered it by Amazon.com. It'll arrive on October 9.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/5334114/DiscImageCreator_test.zip)
added
>        /ps     The sector is padded when reading error occurs
>                       val     0: Padded by 0x00
>                       val     1: Padded by 0xAA
