### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by majorpbx** [saramibreak/DiscImageCreator#58]
Issue first noted with build **20200716T214844** as noted below. Dumping a MS Visual Studio disc the program crashes. I've never seen this before and as indicated it persists with the newest release. I have attached what log files remain after the crash and have noted the windows crash information as well.

**Problem signature:**
  Problem Event Name:	APPCRASH
  Application Name:	DiscImageCreator.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5f104cb1
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2990
  Fault Module Timestamp:	5caeb859
  Exception Code:	c0000005
  Exception Offset:	00042357
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Verified still an issue with build **20200921T112141** as found below.

**Problem signature:**
  Problem Event Name:	APPCRASH
  Application Name:	DiscImageCreator.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5f680e3b
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2990
  Fault Module Timestamp:	5caeb859
  Exception Code:	c0000005
  Exception Offset:	00042357
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Logs:
[Dump_Log.zip](https://github.com/saramibreak/DiscImageCreator/files/5315939/Dump_Log.zip)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/5316536/DiscImageCreator_test.zip)
Added buffer size check. Test, plz.

**Comment by majorpbx** [comment]
Testing now, but initially looks promising as it has made it past "Checking EXE" and is now at "Creating .scm (LBA)". Will reply when the entire dump process is complete.

**Comment by majorpbx** [comment]
Dump completed successfully, that was a quick fix and thank you for such a great tool.

**Comment by majorpbx** [comment]
Closing issue as it was resolved with your fix. Thanks again.
