### ISSUE TITLE
LOGICAL BLOCK ADDRESS OUT OF RANGE With IBM PC Disc

### ISSUE THREAD

**Issue by oblivioncth** [saramibreak/DiscImageCreator#59]
Hello,

Having an issue getting my first dump done.

**Game Info:**
Pitfall: The Mayan Adventure (PC, Windows 95)
  Ring Serial - CDD3117 R1J
  Mastering Code - JVC IFPI L239
  Mould Code: IFPI 4111
  Barcode (JVC Glyph Variant): [START] CDD3117 R1JDD [STOP]

**Drive Info:**
LG WH14NS40
  Alt - HL-DT-ST-BD-RE_WH14NS40 
  Firmware - 1.01-N1A12A1-211304042325 (I can crossflash to Asus BW-16D1HT 3.02)

**Other Info:**
Attempted using DICUI
  Tried With - DICUI_1.17.1-net48
  Tried With - DICUI\bin\Debug\DICUI_net472 (1.17.1-428)
  System/Media Type: IBM PC Compatible / CD-ROM

**Error:**
```
LBA[271539, 0x424b3]: [F:ReadCDForCheckingReadInOut][L:703]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, 04, 00, 04, 24, b3, 00, 00, 01, f8, 00, 00
dwBufSize: 2352
```

Generated files, **excluding empty ones**, attached.
[PITFALL Dump Attempt.zip](https://github.com/saramibreak/DiscImageCreator/files/5344888/PITFALL.Dump.Attempt.zip)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/5345022/DiscImageCreator_test.zip)
added WH14NS40 1.01

**Comment by oblivioncth** [comment]
Thanks I was able to dump the disc with that and confirm it is a release that is not present in the database. I am awaiting account approval in the forums to make the submission, but are there any of the generated files you would like me to provide here directly? 

Still got a LOGICAL BLOCK ADDRESS OUT OF RANGE error around the time when copy protection was checked for, but it did not halt execution of the program. Seemed like it may have been when trying to test if the drive can read the lead-out section of the disc as it reported it could not right after.

**Comment by saramibreak** [comment]
> are there any of the generated files you would like me to provide here directly?

No, if you complete dumping the disc.

> Seemed like it may have been when trying to test if the drive can read the lead-out section of the disc as it reported it could not right after.

Yes.

**Comment by oblivioncth** [comment]
Ok thanks, issue is solved.
