### ISSUE TITLE
Can someone confirm the right drive to use

### ISSUE THREAD

**Issue by Amazingsteve** [saramibreak/DiscImageCreator#61]
So after buying 2 drives I can not seem to get it to work.

 This time I will purchase a drive directly from the suggested list, however, I am not sure which one is the most versitle. I am looking to dump CD-Rom's and DVD's. The one I am thinking about purchasing is the ASUS BC-12D2HT.

However, can it anyone confirm it works? Is a different one recommended? 

IN a previous thread Saramibreak used  ASUS BW-16D1HT (firmware 3.02). which is the same as the one above, I assume. I just would like to confirm the details.

**Comment by saramibreak** [comment]
Multi-sector reading of the lead-out of non-plextor drive is WIP/experimental.

http://forum.redump.org/post/85733/#p85733
http://forum.redump.org/post/85758/#p85758
http://forum.redump.org/post/85821/#p85821

I recommend Plextor.

**Comment by Amazingsteve** [comment]
> 
> 
> Multi-sector reading of the lead-out of non-plextor drive is WIP/experimental.
> 
> http://forum.redump.org/post/85733/#p85733
> http://forum.redump.org/post/85758/#p85758
> http://forum.redump.org/post/85821/#p85821
> 
> I recommend Plextor.

For Clarification, you mean any of these models? "DVD model: PX-760, PX-755, PX-716, PX-714, PX-712, PX-708, PX-704" So, as long as I purchase one of these model it should work. I am assuming the 760 is the newest on the list and would probably be the best for my purpose of use.

**Comment by Arrrrrrachno** [comment]
I bought Asus BW-16D1HT, which is on list. It has firmware 3.10. I tried it on a disc (soundtrack) which I could not backup with other drives and it did not work:
```
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 1]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 2]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 4]
LBA[...]: [F:ReadCDForCheckingReadInOut][L:801]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, [...]
dwBufSize: 2352
This drive can't read the lead-out
```
For test purpose edit check.cpp line 120 and changed the hard coded firmware version from 3.02 to my 3.10. This only leads to another error `ILLEGAL_REQUEST - INVALID FIELD IN CDB` (`Opcode: 0xf1`).

In result I would say this drive does not work even though it is on list. The plextor drives are old and cannot be bought anymore. Thus new drives not working, old ones not existing, I would say there simply exists any useful drive.

**Comment by saramibreak** [comment]
> Is PX-760A OK?

Yes.

> In result I would say this drive does not work even though it is on list.

See. http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility#Recommended_Non-Plextor_ODDs

**Comment by Amazingsteve** [comment]
I just bought the 760A and it did not work. You got to be kidding this is
the third drive and I paid 70$ for it. I can not believe this. I am running
into the same errors. I needed this project done before the endo do year. I
guess I will have to throw my discs and drives. What a waste.

**Comment by Amazingsteve** [comment]
Sorry about that. My last responses was sent through email and it did not
format correctly. I also was not ready send it. Autocorrect on my phone is
horrible and sometimes no matter what I type the word changes. Anyways, so
the 760A does not work? I am still getting the same errors as before. 0x08
something like that. I am away from my computer right now and I do not
remember the exact error. So is it the drive?

**Comment by saramibreak** [comment]
> Anyways, so the 760A does not work?

760A really works. Without logs, I can't advise you.

**Comment by Amazingsteve** [comment]
LBA[2075488, 0x1fab60]: [F:ReadDVD][L:311]
Opcode: 0xa8
ScsiStatus: 0x02 = CHECK_CONDITION
SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR

LBA[2075488, 0x1fab60]: [F:ReadDVD][L:311]
Opcode: 0xa8
ScsiStatus: 0x02 = CHECK_CONDITION
SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR

LBA[2075488, 0x1fab60]: [F:ReadDVD][L:311]
Opcode: 0xa8
ScsiStatus: 0x02 = CHECK_CONDITION
SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR

LBA[2075488, 0x1fab60]: [F:ReadDVD][L:311]
Opcode: 0xa8
ScsiStatus: 0x02 = CHECK_CONDITION
SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR

LBA[2075488, 0x1fab60]: [F:ReadDVD][L:311]
Opcode: 0xa8
ScsiStatus: 0x02 = CHECK_CONDITION
SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR

LBA[2075488, 0x1fab60]: [F:ReadDVD][L:311]
Opcode: 0xa8
ScsiStatus: 0x02 = CHECK_CONDITION
SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR

========== DiscStructure ==========
FormatCode: 00, Sendable:  No, Readable: Yes
FormatLength: 2052
========== PhysicalFormatInformation ==========
      BookVersion: 1
         BookType: DVD-ROM
      MinimumRate: 10.08 Mbps
         DiskSize: 120mm
        LayerType: Layer contains embossed data
        TrackPath: Parallel Track Path
   NumberOfLayers: Single Layer
     TrackDensity: 0.74um/track
    LinearDensity: 0.267um/bit
StartingDataSector:  196608 (0x30000)
    EndDataSector: 2277119 (0x22beff)
EndLayerZeroSector:       0 (0)
          BCAFlag: No
    MediaSpecific:
========== LBA[000000, 0000000]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0010 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0030 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0040 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0050 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0060 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0070 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0080 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0090 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0100 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0110 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0120 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0130 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0140 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0150 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0160 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0170 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0180 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0190 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0200 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0210 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0220 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0230 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0240 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0250 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0260 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0270 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0280 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0290 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0300 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0310 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0320 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0330 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0340 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0350 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0360 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0370 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0380 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0390 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0400 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0410 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0420 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0430 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0440 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0450 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0460 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0470 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0480 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0490 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0500 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0510 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0520 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0530 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0540 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0550 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0560 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0570 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0580 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0590 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0600 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0610 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0620 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0630 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0640 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0650 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0660 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0670 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0680 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0690 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0700 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0710 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0720 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0730 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0740 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0750 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0760 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0770 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0780 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0790 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00
========== SectorLength ==========
LayerZeroSector: 2080512 (0x1fbf00)

FormatCode: 01, Sendable:  No, Readable: Yes
FormatLength: 8
========== CopyrightInformation ==========
   CopyrightProtectionType: No
RegionManagementInformation: 1 2 3 4 5 6 7 8

FormatCode: 02, Sendable:  No, Readable: Yes
Skiped because of DVD with CSS only

FormatCode: 03, Sendable:  No, Readable: Yes
Skiped because of no BCA data

FormatCode: 04, Sendable:  No, Readable: Yes
FormatLength: 2052
========== ManufacturingInformation ==========
========== LBA[000000, 0000000]: Main Channel ==========
       +0 +1 +2 +3 +4 +5 +6 +7  +8 +9 +A +B +C +D +E +F
0000 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0010 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0030 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0040 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0050 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0060 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0070 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0080 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0090 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0100 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0110 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0120 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0130 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0140 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0150 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0160 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0170 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0180 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0190 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0200 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0210 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0220 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0230 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0240 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0250 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0260 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0270 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0280 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0290 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0300 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0310 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0320 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0330 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0340 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0350 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0360 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0370 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0380 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0390 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0400 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0410 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0420 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0430 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0440 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0450 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0460 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0470 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0480 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0490 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0500 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0510 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0520 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0530 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0540 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0550 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0560 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0570 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0580 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0590 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0600 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0610 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0620 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0630 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0640 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0650 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0660 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0670 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0680 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0690 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0700 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0710 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0720 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0730 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0740 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0750 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0760 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0770 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0780 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0790 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07A0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07B0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07C0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07D0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07E0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07F0 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

FormatCode: 05, Sendable:  No, Readable: Yes
Skiped. If you see the detailed, use /c option

FormatCode: 06, Sendable:  No, Readable:  No
Skiped because of DVD with CPRM only

FormatCode: 07, Sendable:  No, Readable:  No
Skiped because of DVD with CPRM only

FormatCode: 0c, Sendable:  No, Readable:  No
Skiped because of DVD-R, RW only

FormatCode: 0d, Sendable:  No, Readable:  No
Skiped because of DVD-R, RW only

FormatCode: 0e, Sendable:  No, Readable:  No
Skiped because of DVD-R, RW only

FormatCode: 0f, Sendable:  No, Readable:  No
Skiped because of DVD-R, RW only

FormatCode: 10, Sendable:  No, Readable:  No
Skiped because of DVD-R, RW only

FormatCode: 11, Sendable:  No, Readable:  No
Skiped because of DVD+R, RW only

FormatCode: 30, Sendable:  No, Readable:  No
Skiped because of DVD+R, RW only

FormatCode: c0, Sendable:  No, Readable:  No
Skiped because of DVD-R Rewritable only

FormatCode: ff, Sendable:  No, Readable: Yes
Skiped

**Comment by saramibreak** [comment]
It's a similar issue. https://github.com/saramibreak/DiscImageCreator/issues/57

If your disc is in mint condition, Try to use /ps option.
>        /ps     The sector is padded when reading error occurs
>                       val     0: Padded by 0x00
>                       val     1: Padded by 0xAA

If no, please remove the scratch.

**Comment by Amazingsteve** [comment]
Where do I place that? IN Parameters? IN a file? I have not done that yet
before.

**Comment by saramibreak** [comment]
It seems you don't know how to use a basic command-line app.
Did you read a README.md? Did you read a wiki(https://github.com/saramibreak/DiscImageCreator/wiki)?

**Comment by Amazingsteve** [comment]
I will admit, I have not used it yet. I never needed to use it. In previous
builds the program worked without any issues but, it has been only recently
that I started without older discs. Before it was fairly straightforward
but, now that I am getting these errors, I will admit it is throwing me for
a loop.

**Comment by Amazingsteve** [comment]
Creating iso(LBA)  2094099/ 2099488 Around this area it started padding
numbers on every number, is that normal? That disc is still running as I
speak but, that is a lot of padded numbers. Right now I am up to about
2095101 which has taken about an hour to get to this point.

**Comment by Amazingsteve** [comment]
Read retry from 2094464 to Read retry from 2095823 were padded numbers
using the /ps option. However, with so many of them being filled in will
that hurt the quality of the program or disc? I am trying now but, thus far
I have not found anything wrong but, without fully playing the game I do
not know. What is your take on this?

**Comment by saramibreak** [comment]
> Creating iso(LBA)  2094099/ 2099488 Around this area it started padding
numbers on every number, is that normal?

> LayerZeroSector: 2080512 (0x1fbf00)

2094099 is over the last sector 2080512. It's not normal.
