### ISSUE TITLE
App crash when dumping a DVD

### ISSUE THREAD

**Issue by huoqianyu** [saramibreak/DiscImageCreator#62]
Hello developer,

I found DIC crashed when dumping a Microsoft MSDN DVD with many files and directory. 

I'm using Windows 7 SP1, when crash a window appeared and shows the error file is ucrtbase.dll (version 14393.2990). The CD drive I use is MATSHITA UJ8E1.

Here are all logs created during dump:
[https://anonfiles.com/H4z7mb13p7/log_7z](url)

I searched and found a closed issue (https://github.com/saramibreak/DiscImageCreator/issues/58), in which a user had same problem as mine. You made a special version with buffer size check, I downloaded and test it, however problem still exists.

Would you mind check the log and help me with this problem? Thank you so much!

**Comment by saramibreak** [comment]
Uploaded. Test, please.
https://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file

**Comment by huoqianyu** [comment]
> Uploaded. Test, please.
> https://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file

Thank you so much, it really works! May I ask what cause this problem, the cache size of my DVD Drive or something? 👍

**Comment by saramibreak** [comment]
https://github.com/saramibreak/DiscImageCreator/commit/74bd0ddbba65c1e56302f7ef26dab53ff08ee946
The buffer size to store the filename was expanded.
