### ISSUE TITLE
New disc has checksum errors

### ISSUE THREAD

**Issue by oblivioncth** [saramibreak/DiscImageCreator#65]
**Game Info:**
LEGO Soccer Mania
Ring Serial - 9473489C
Mastering Code - 9473489C + + D792702
Mastering SID Code - IFPI LB41
Mould Code - IFPI I004
System/Media Type: IBM PC Compatible / CD-ROM

**Drive Info:**
LG WH14NS40
Alt - HL-DT-ST-BD-RE_WH14NS40
Firmware - 1.01-N1A12A1-211304042325 (I can crossflash to Asus BW-16D1HT 3.02)

**DIC Info:**

- Tried with test build from #64 

- Command: DIC\DiscImageCreator.exe cd F media_dic\Disc01\Disc01.bin 48 /c2 1000 /q /ns /s 2

Using the test build from issue 64, I tried dumping a different disc for the same purposes mentioned there. Other than the usual LBA out of range errors that are now normal with this drive, I have the following issue
```
Creating .scm (LBA)   1335/246757 LBA[001336, 0x00538] Detected C2 error 312 bit
Creating .scm (LBA)   1351/246757 LBA[001352, 0x00548] Detected C2 error 312 bit
Creating .scm (LBA)   1382/246757 LBA[001383, 0x00567] Detected C2 error 312 bit
Creating .scm (LBA)   1394/246757 LBA[001395, 0x00573] Detected C2 error 312 bit
Creating .scm (LBA)   1405/246757 LBA[001406, 0x0057e] Detected C2 error 312 bit
Creating .scm (LBA)   1424/246757 LBA[001425, 0x00591] Detected C2 error 312 bit
...

Checking sectors: 246757/246757
[ERROR] Number of sector(s) where user data doesn't match the expected ECC/EDC: 597
Total errors: 597
Total warnings: 0
```

This one was sealed/mint. Any ideas?

[Soccer Mania.zip](https://github.com/saramibreak/DiscImageCreator/files/6104042/Soccer.Mania.zip)

**Comment by saramibreak** [comment]
This disc is a safedisc. Try to use /sf, not /ns.

**Comment by oblivioncth** [comment]
Sorry, I should have considered that myself. I was on such a streak of running into discs without copy protection that it had totally skipped my mind.

With /sf (defaulted to 60) I get the following:
```
No unintentional C2 errors
Copying .scm to .img
Descrambling data sector of img: 246757/246757
Exec ""C:\Users\Chris\Desktop\BA DIC\DIC\EccEdc.exe" fix "C:\Users\Chris\Desktop\BA DIC\media_dic\Disc01\Disc01.img"" 911 10910
FILE: C:\Users\Chris\Desktop\BA DIC\media_dic\Disc01\Disc01.img
Checking sectors: 246757/246757
[ERROR] Number of sector(s) where user data doesn't match the expected ECC/EDC: 597
Total errors: 597
Total warnings: 0
597 unmatch sector is replaced at 0x55 except header
Creating cue and ccd (Track)  1/ 1
Creating bin (Track)  1/ 1
Hashing: Disc01.scm
Hashing: Disc01.img
Hashing: Disc01.bin
EndTime: 2021-03-10T06:41:51-0500
```
I apologize for being a bit of a noob at this but I'm slightly confused by the report at the end here. Can the 597 ECC errors safely be ignored because of
`No unintentional C2 errors`
and
`597 unmatch sector is replaced at 0x55 except header`
which suggest that all found errors were part of the copy protection and they have all been successfully accounted for?

Or was the disc still not handled correctly because its labeled as "[ERROR]" instead of a warning or the like?

[Soccer Mania.zip](https://github.com/saramibreak/DiscImageCreator/files/6115566/Soccer.Mania.zip)

**Comment by saramibreak** [comment]
> which suggest that all found errors were part of the copy protection and they have all been successfully accounted for?

Yes. Redump.org handles them as errors. See also http://redump.org/discs/quicksearch/safedisc/protection/only

**Comment by oblivioncth** [comment]
Ok, makes perfect sense.

Thanks for the assistance. Next time I will also look over the Redump documentation as well in case it clarifies any confusion before creating an issue.

The disc has now successfully been dumped.
