### ISSUE TITLE
Negative offset

### ISSUE THREAD

**Issue by eubrunosilva** [saramibreak/DiscImageCreator#67]
Hi
how can I set a negative offset?
/a -xxxx or /a "-xxxx" doesnt work

Thanks

**Comment by saramibreak** [comment]
`DiscImageCreator.exe cd f foo.bin 0 /a -32`

_disc.txt

> ========== Offset (Drive offset referes to http://www.accuraterip.com) ==========
	       Combined Offset(Byte)   -104, (Samples)   -26
	-         Drive Offset(Byte)     24, (Samples)     6
	----------------------------------------------------
	 User Specified Offset(Byte)   -128, (Samples)   -32
	Overread sector: -1
	SubChannel Offset: 0
