### ISSUE TITLE
Multi threaded hashing?

### ISSUE THREAD

**Issue by gmipf** [saramibreak/DiscImageCreator#68]
Could you maybe add multi threaded hashing of dumped discs? The hashing takes very long time on bluray discs.

**Comment by maxz** [comment]
Most hash functions can't be parallelised. They required the information of the previous block for the next block.

What you are asking for is therefore impossible.

It would be possible to implement for CRC32 but not for MD5 or SHA1.
Thus nothing would be won.

**Comment by saramibreak** [comment]
Hash image while dumping (#108)
