### ISSUE TITLE
Bug: Cannot dump some PS3 discs (Segmentation fault)

### ISSUE THREAD

**Issue by gmipf** [saramibreak/DiscImageCreator#69]
Here is the output: 

```
$ sudo ./DiscImageCreator_linux.out bd /dev/sr0 dumps/ps3_tcrs_bces01070/dump.bin 12
AppVersion
        x64, AnsiBuild, 20210601T124730
CurrentDirectory
        /media/Daten/DiscImageCreator_linux
WorkingPath
         Argument: dumps/ps3_tcrs_bces01070/dump.bin
         FullPath: /media/Daten/DiscImageCreator_linux/dumps/ps3_tcrs_bces01070/dump.bin
            Drive: /
        Directory: media/Daten/DiscImageCreator_linux/dumps/ps3_tcrs_bces01070/
         Filename: dump
        Extension: .bin
StartTime: 2021-06-02T20:56:37+0200
Set the drive speed: 53952KB/sec
LBA[000000, 0000000]: [F:ReadDiscStructure][L:1335]
        Opcode: 0xad
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
FormatCode: 03 failed
cdb: ad, 20, 00, 00, 00, 00, 00, 03, 00, 04, 00, 00
Reading DirectoryRecord   59/  59
Segmentation fault
```

I already had this once before with another PS3 disc. Already dumped many PS3 discs but it's weird that there are some discs with this failure. With ImgBurn and on PS3 hardware/Multiman the dumping is working. Do you want to give me a debug build so I can give you a log? I have to give that disc back in 3 days. 

[ps3_tcrs_bces01070.zip](https://github.com/saramibreak/DiscImageCreator/files/6586875/ps3_tcrs_bces01070.zip)

**Comment by saramibreak** [comment]
> I already had this once before with another PS3 disc.

Please tell me these all titles you have. I'll get the cheapest title to test.

**Comment by gmipf** [comment]
Only two PS3 titles so far I found with this error:

Time Crisis: Razing Storm (BCES-01070)
PlayTV application disc (BCES-00096)

**Comment by gmipf** [comment]
So I could gather some more info about the problem. I also tried the same disc on Windows 8.1, same drive and disc BCES-01070. On windows DiscImageCreator.exe is crashing after "Reading DirectoryRecord   59/  59".

I will also send you a pn at redump forum, so please don't yet buy anything.

**Comment by gmipf** [comment]
I have sent a new pn.

**Comment by saramibreak** [comment]
- fixed: escaped the encrypted PARAM.SFO
[DiscImageCreator_linux_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/6602676/DiscImageCreator_linux_test.tar.gz)

**Comment by gmipf** [comment]
It is working now, I could dump the original BCES-01070 disc.
