### ISSUE TITLE
Stop on DirectoryRecord reading

### ISSUE THREAD

**Issue by Novicami** [saramibreak/DiscImageCreator#7]
DIC 20170728 remains locked on the DirectoryRecord reading (173/2947) : 
http://dl.free.fr/rwyVKJR5b
TiA ;-)

**Comment by saramibreak** [comment]
The Directory Record of LBA 40915 is corrupt. Is this no-error disc?

**Comment by Novicami** [comment]
The disc is really in good physical condition. I made a copy with ISOBuster v4.0 and the ISO file has no corrupted sectors (checked with ECC/EDC data). This may be a mastering mistake?! You would have an idea to bypass the blocking of DIC?

**Comment by saramibreak** [comment]
Uploaded test version.
http://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z

**Comment by Novicami** [comment]
Thank you, it works but there is a risk on the quality of the copy?

**Comment by saramibreak** [comment]
Perhaps no. Just in case, please check all disc you have.

**Comment by Novicami** [comment]
For AT4, it's ok. I will continue with DIC 20170728, this will allow me to identify other discs problem.
incorporating a warning in DIC would be interesting...
