### ISSUE TITLE
Question: Three image files on CD backup?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#71]
Hi everyone,

I was wondering, why there are three image files created upon backup of a CD.

the BIN and IMG image are byte identical. So why linking two different ones in the related files?

the SCM file has the same size as the BIN and IMG, but another checksum. What's the difference inside?

If I would want to save a backup on my NAS of my discs, do I need to keep all image files?

**Comment by saramibreak** [comment]
BIN is files that divides IMG per the track. Divided BINs are redump.org format. If you do not contribute to it, those do not need.
SCM is a scrambled file of the IMG. If you want to save only the playable image, you just have to save img+ccd+sub+cue.

**Comment by Feathered-Serpent** [comment]
Thank you for your information. Case closed!
