### ISSUE TITLE
How to copy Tagès protection?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#72]
From what I have read, the disc would need to be read reverse.

But when I try that with cd or dvd on my Plextor drive the executable tells me, that /r is an invalid parameter.

**Comment by saramibreak** [comment]
> the executable tells me, that /r is an invalid parameter.

See wiki https://github.com/saramibreak/DiscImageCreator/wiki and search "/r" using Ctrl+F.
Or work DiscImageCreator.exe by double-click, then show the usage.

> How to copy Tagès protection?

DiscImageCreator.exe only supports creating a reversed file, not create a playable image file.

**Comment by Feathered-Serpent** [comment]
"DiscImageCreator.exe only supports creating a reversed file, not create a playable image file." clears the question for me.

As /r stands beneath "Option (for CD read mode)" I thought it would count for cd command as well, not only for data command.
