### ISSUE TITLE
TestedDrive info question (especially GD compatibility)

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#73]
I have a PX-W5224A drive. At the GD rom column it's stated:
Part(79:59:74)(*5)

and the note says
*5
 It can dump HD Area no swap but if swap, can't read the HD Area.

So it should be able to dump the HD part of a Dreamcast game? When I tried, it wasn't able to locate the sector.

**Comment by saramibreak** [comment]
If you dump GD-ROM, use TS-H353A, TS-H352C of TSSTcorp.

**Comment by Feathered-Serpent** [comment]
So the drives with "Part(79:59:74)" at the GD column don't do anything then I assume?

**Comment by saramibreak** [comment]
HD area length exists until 112:02:00. PX-W5224A can't read 80:00:00 ... 112:01:74.

**Comment by Feathered-Serpent** [comment]
Ahhh, thanks for the clarification!
