### ISSUE TITLE
Error on dumping PS3 discs

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#75]
Using an ASUS BW-16D1HT (Firmware 1.02) I get the following error at the beginning, though the backup continues then and I get an ISO file. So far this happened on two games, will try on some more games.

LBA[000000, 0000000]: [F:ReadDiscStructure][L:1342]
        Opcode: 0xad
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-24-00 = ILLEGAL_REQUEST - INVALID FIELD IN CDB
FormatCode: 03 failed
cdb: ad, 20, 00, 00, 00, 00, 00, 03, 00, 04, 00, 00

Is this something bad for the image itself? I do not get the segmentation error I've seen in https://github.com/saramibreak/DiscImageCreator/issues/69

**Comment by saramibreak** [comment]
> Is this something bad for the image itself?
No.

**Comment by Feathered-Serpent** [comment]
Great, mystery solved.
