### ISSUE TITLE
Strange Copy protection: Sysiphus 

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#76]
Hi there

I've reached dumping a CD for Dark Age of Chamelot. On that disc is a file called SUM.EXE which is placed on an LBA which... no tool can read or access.

MPF runs basically infinite when it tried to analyze that file.
DIC stops at the LBA and after a while this happens:
```
AppVersion
        x86, AnsiBuild, 20210616T120632
/c2 val2 was omitted. set [0]
/sf val was omitted. set [60]
CurrentDirectory
        C:\apps\backup\MPF
WorkingPath
         Argument: G:\ISO\Dark Age of Camelot\Nouveau.bin
         FullPath: G:\ISO\Dark Age of Camelot\Nouveau.bin
            Drive: G:
        Directory: \ISO\Dark Age of Camelot\
         Filename: Nouveau
        Extension: .bin
StartTime: 2021-06-20T13:28:09+0200
Set the drive speed: 12700KB/sec
This drive supports [OpCode: 0xd8, SubCode: 0]
This drive supports [OpCode: 0xd8, SubCode: 1]
This drive supports [OpCode: 0xd8, SubCode: 2]
This drive supports [OpCode: 0xd8, SubCode: 8]
Checking reading lead-out -> OK
Checking SubQ adr (Track)  1/ 1
Checking SubRtoW (Track)  1/ 1
Checking Pregap sync, msf, mode (LBA)  -2851
Scanning sector (LBA) 189563/194832[F:ReadCDForScanningProtectViaSector][L:2346] GetLastError: 121, Das Zeitlimit f³r die Semaphore wurde erreicht.

lpCmd: d8, 00, 00, 02, e4, 7c, 00, 00, 00, 01, 08, 00
dwBufSize: 2742
EndTime: 2021-06-20T13:36:02+0200
```
(English message would be: The semaphore timeout period has expired.)

A surface scan with Isobuster doesn't come to an end as well (at least it's currently running for 15mins and doesn't continue at 97.30 percent. the drive sometimes spins up and down still, and I can still hear it moving the something inside then and when)

ProtectionID was able to tell me this when scanning the disc anf finding the SUM.EXE:
`Sysiphus CD/DVD Copy Protection v1.5 detected`

Ever heard of that? I tried reading it with the PX-W4012 and the PX-755A. On the surface of the disc there is a visible ring to be seen on the data side.

**Comment by saramibreak** [comment]
> On the surface of the disc there is a visible ring to be seen on the data side.

It's RingProtect or proring.
/ss doesn't use for RingProtect or proring.

**Comment by Feathered-Serpent** [comment]
I have the assumption, that this disc killed my USB adapter (Windows tells "Unknown USB device" suddenly) as well as my ASUS BluRay drive (which doesn't recognize anything anymore, no CD, no DVD, no BluRay) when I tried finding out, which of the sectors are there and which are not, aka let a surface scan try to reach over the "damaged" parts.

I better throw that game away.

**Comment by Feathered-Serpent** [comment]
Found another game with that copy protection:
Wizardry 8, but only on disc 3. I didn't tried long to back up that, as even without /ss the drive started hanging itself again when it came to the later sectors.

Really seems like a copy protection to kill a backup process.
