### ISSUE TITLE
Question about DVD dumping

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#77]
I know that, if the disc is CSS encrypted, there will be a text file with the css key for the VOB files.

But the backup wouldn't be decrypted, right?

I tested dumping a few DVDs here and there. On some I had it that there were "unrecoverable errors" during dumping. But when e.g. ripping all video files with MakeMKV there was not a single error. Could it be some kind of protection? I cannot tell yet, if it's the same thing like in https://github.com/saramibreak/DiscImageCreator/issues/34

Using /c on a DVD makes the dumping incredibly slow. What's so different? the DiscInfo log file becomes huuuuuge.

**Comment by saramibreak** [comment]
> But the backup wouldn't be decrypted, right?

You can dump the encrypted iso file. Because it is illegal to create a decrypted file.

> Could it be some kind of protection?

I'm not sure. Please use A-Rayscanner or ProtectionID to detect protection.

**Comment by Feathered-Serpent** [comment]
I scanned the disc with various tools:
ProtectionID Protection Report (txt format):
17:09:56 | *DISC* D:\ [THE_PINK_PANTHER] | Detected CSS / CPMM Protection! (0x00000001) | Region Lock Detected -> RegionBitMask: 00000002
[.] Region(s) allowed : 2 

A-Ray Scanner:
[17:10:59] DvdCrypt CSS/CPPM detected -> D:\THE_PINK_PANTHER  [F40CEA60]

DVDFab Passkey:
Invalid PGCs, CELLs, VOBUs protection is removed.
Invalid PTTs, PGCIs, TMAPs protection not found.
8 fake vts (8, 10, 13, 17, 18, 19, 20, 21) protections are removed.
Potential bad sector (vts:1 title begin:0 end:178) is removed.
Potential bad sector (vts:2 menu begin:0 end:357) is removed.
Potential bad sector (vts:2 title begin:195 end:194653) is removed.
Potential bad sector (vts:2 title begin:1863115 end:2281496) is removed.
Potential bad sector (vts:3 menu begin:0 end:178) is removed.
Potential bad sector (vts:11 title begin:0 end:178) is removed.
Potential bad sector (vts:14 title begin:82769 end:84200) is removed.
Potential bad sector (vts:15 title begin:0 end:178) is removed.
8 potential bad sector protections are removed.
Structure protection (ARccOS, RipGuard, etc.) is removed.

So it seems like there are bad sectors as a kind of protection.

**Comment by saramibreak** [comment]
Is there a visible ring on your disc?

**Comment by Feathered-Serpent** [comment]
No, see for yourself:
https://imgur.com/a/W63QvlO

One image from the label side, two of the data side.

**Comment by saramibreak** [comment]
Some Sony pictures DVDs have ARccOS https://en.wikipedia.org/wiki/ARccOS_protection
I can't support it yet because I don't have its protected disc.

**Comment by Feathered-Serpent** [comment]
One can't tell DIC to just continue even after bad sectors, can we? After an unrecoverable error, the dumping quits.

**Comment by Feathered-Serpent** [comment]
Hmm strangely, DIC skips bad sectors on another disc (though this is a new drive of the same type I had before, the old one stopped reading anything):
NumberOfProgramChain: 31212
Detected irregular title number
Detected protection [MVSNRGFP]. LBA 0 to 0
Detected Anchor Volume Descriptor Pointer: LBA 3284767
Outputted to _xxxKey.txt

Error sectors range: LBA 385480 to 385511 = 32 -> Filled with 0x00
Error sectors range: LBA 470112 to 470142 = 31 -> Filled with 0x00
Error sectors range: LBA 471504 to 471534 = 31 -> Filled with 0x00

Disc dumping is still running currently. What is this mentioned about the LBA 0?

**Comment by saramibreak** [comment]
> Detected protection [MVSNRGFP]. 

It's RipGuard. 

> LBA 0 to 0

This is useless for this protection. I'll update so as not to show it.

**Comment by Feathered-Serpent** [comment]
As a little side info, I found a typo. In the *_disc files for DVDs, there I've seen "Skiped" more often. I assume it should be "Skipped"?

**Comment by saramibreak** [comment]
>  I assume it should be "Skipped"?

Yes, I'll fix it.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/6918056/DiscImageCreator_test.zip)
- added: detecting ARccOS

I tested Stranger than Fiction (0 43396 15407 0) and Pursuit of Happyness, the (0 43396 15085 0)

**Comment by Feathered-Serpent** [comment]
How long did the dumping need for these? I tried dumping the Pink Panther DVD again.
StartTime: 2021-08-02T17:49:33+0200

that's now nearly an hour ago, and it's only at LBA 649492, because it finds errors and errors and errors, then reads back some sectors, then finds other errors.  The disc has 4169920 LBAs

**Comment by Feathered-Serpent** [comment]
I am not sure, that this is right.... for one, the process took now 3 hours and 10mins.

Then the _disc file does NOT list all erroneous sectors, but the _mainerror does. I attached all but the image files.

[THE_PINK_PANTHER.zip](https://github.com/saramibreak/DiscImageCreator/files/6919050/THE_PINK_PANTHER.zip)

**Comment by saramibreak** [comment]
> the process took now 3 hours and 10mins.

Yes, it took the same time for my disc.

> Then the _disc file does NOT list all erroneous sectors, but the _mainerror does.

2589129 is sometimes readable and at other times not.

[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/6920795/DiscImageCreator_test.zip)
- added: /nss option in dvd

If you use "/nss 3", reading error sector is reread at 3 times.

**Comment by Feathered-Serpent** [comment]
If checking the ISO file afterwards with Isobuster and let it check the readability of files, there's a whole bunch of files with the errors, though they're all at the "end" of the file list:
https://i.imgur.com/sZsWF5n.png

VTS_02 still contains over 4GB alone, where the main movie is. so those other VTS files are bogus files I assume, only there to make it difficult to rip (which btw. is possible without any problems, because the main movie is in files which are all ok)

**Comment by Feathered-Serpent** [comment]
Will close this from my side, as it is more useful to have the disc already decrypted on the disk done with another tool. Dumping Video DVDs isn't the purpose of DIC I would think.

I hope the addition for the ARccOS was still useful for others.
