### ISSUE TITLE
Crash on Amiga CD 

### ISSUE THREAD

**Issue by Novicami** [saramibreak/DiscImageCreator#8]
Sorry, I'm confronted again with a DIC 20170728 crash...
The logs before the crash:
```
Allocating packed memory for C2 errors: 8192
This drive supports [OpCode: 0xd8, SubCode: 0]
This drive supports [OpCode: 0xd8, SubCode: 1]
This drive supports [OpCode: 0xd8, SubCode: 2]
This drive supports [OpCode: 0xd8, SubCode: 3]
This drive supports [OpCode: 0xd8, SubCode: 8]
Checking reading lead-out -> OK
Checking SubQ adr (Track) 10/10
Checking SubRtoW (Track) 10/10
Reading DirectoryRecord   20/  20
Set OpCode: 0xd8, SubCode: 8(Raw)
Checking SubQ ctl (Track) 10/10
Created img (LBA)  24959/194074
```

I hope this file will help you:
http://dl.free.fr/vOeQyqEEr

PS: No problem with ISOBuster

**Comment by saramibreak** [comment]
I burned it to CD-RW and dumped with dic, but no crash.

**Comment by Novicami** [comment]
Ok ... the files generated before the crash can be useful?

**Comment by saramibreak** [comment]
Isobuster doesn't create the subchannel. So, a cause of crash may be the subchannel, but I don't know because I don't have the original disc..

**Comment by Novicami** [comment]
I redone a dump with CCD v5.3.4.0 and Redump profil:
http://wiki.redump.org/index.php?title=Setting_Up#CloneCD
and as a bonus, I used SubDump

CCD http://dl.free.fr/m8i4ujnvm
SubDump http://dl.free.fr/mkUCbNcPP

**Comment by saramibreak** [comment]
Uploaded test version.
----
This disc has the weird subQ channel per 100 sector. DIC accessed in the array out of range using the unexpected value. This is fixed.

**Comment by Novicami** [comment]
I did a test for Z2 and it's OK now but...in between, I discovered another CD that had the same problem and the latest version is also problematic : 
`OS
	Windows 7 Professional Service Pack 1 64bit
AppVersion
	x86, AnsiBuild, Aug 14 2017 09:13:43
/c2 val1 is omitted. set [1024]
/c2 val2 is omitted. set [4096]
/c2 val3 is omitted. set [4]
CurrentDirectory
	C:\Program Portable\DiscImageCreator
WorkingPath
	 Argument: LastDump\Disc
	 FullPath: C:\Program Portable\DiscImageCreator\LastDump\Disc
	    Drive: C:
	Directory: \Program Portable\DiscImageCreator\LastDump\
	 Filename: Disc
	Extension: 
Start time: 2017-08-14(Mon) 20:46:27
Set the drive speed: 705KB/sec

Allocating packed memory for C2 errors: 8192
This drive supports [OpCode: 0xd8, SubCode: 0]
This drive supports [OpCode: 0xd8, SubCode: 1]
This drive supports [OpCode: 0xd8, SubCode: 2]
This drive supports [OpCode: 0xd8, SubCode: 3]
This drive supports [OpCode: 0xd8, SubCode: 8]
Checking reading lead-out -> OK
Checking SubQ adr (Track)  9/ 9
Checking SubRtoW (Track)  9/ 9
Reading DirectoryRecord    2/   2

Set OpCode: 0xd8, SubCode: 8(Raw)
Checking SubQ ctl (Track)  9/ 9
Created img (LBA) 240002/239999
[L:2195] Internal error. Failed to analyze the subchannel. Track[03]/[09]
Freeing allocated memory for C2 errors: 8192
End time: 2017-08-14(Mon) 21:00:21`
temporary files : 
http://dl.free.fr/sgZnPCu5T

**Comment by saramibreak** [comment]
```
LBA[095989, 0x176f5]: P[ff], Q[01020105166900212164e66f]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[02], Idx[01], RMSF[05:16:69], AMSF[21:21:64]}, RtoW[0, 0, 0, 0]
LBA[095990, 0x176f6]: P[ff], Q[06cf3cf0cff0fff000655c1b]{Audio, 2ch, Copy NG, Pre-emphasis No, Adr[06], Track[cf], Idx[3c], RMSF[f0:cf:f0], AMSF[f0:00:65]}, RtoW[0, 0, 0, 0]
LBA[095991, 0x176f7]: P[00], Q[01030100000100212166d83d]{Audio, 2ch, Copy NG, Pre-emphasis No, Track[03], Idx[01], RMSF[00:00:01], AMSF[21:21:66]}, RtoW[0, 0, 0, 0]
```
095990 is the first LBA of the track 03, but the weird subQ is inserted, so dic can't get the first LBA of the track 03.
Generally,  adr is 01 or 02(MCN) or 03(ISRC), but it seems that 06 exists as a meaningful value in CDTV disc.
Plz wait until update.

**Comment by saramibreak** [comment]
Uploaded test version. Plz test.

**Comment by Novicami** [comment]
I repeated the test with LOT and Z2. It's OK now. This is probably another topic but the result of the dump is different from that referenced on Redump[dot]org. I do not know if this is actually a problem, but the cutting of the tracks is different!?

**Comment by saramibreak** [comment]
```
the result of the dump is different from that referenced on Redump[dot]org.
```
"LOT" or "Z2" or both? BTW, please report it to F1ReB4LL about SubDump.

**Comment by Novicami** [comment]
> "LOT" or "Z2" or both?

Both. I compared those two in particular, but they are not isolated cases.
> BTW, please report it to F1ReB4LL about SubDump.

Redump forum is not accepting new registrations...it will not be easy ^^
This is also why I go through GitHub for DIC
