### ISSUE TITLE
This drive doesn't define in offsets.txt

### ISSUE THREAD

**Issue by 60fpshacksrock** [saramibreak/DiscImageCreator#85]
I get this issue when trying to dump my retail copy of Sonic CD. It seems to work fine with DVD video though.

 Is this a multi-track (or raw 2352) issue? I have noticed this software is the recommended way of backing up discs and I would like to replace imgburn as it seems to like to rip incorrect dumps, particularly of PSX/PS1 games. I have ripped it using both imgburn and UltraISO and neither give me a redump MD5. I have compared multiple dumps using a hex editor and there seems to always be differences in the audio area.

On another note it is nice to be able to rip DVD movies without having to start up AnyDVD to remove the CP. I would guess this is maybe somewhat similar to libdvdcss.

**Comment by saramibreak** [comment]
Your drive is not defined driveOffset.txt. See README.md if you want to use this app.

**Comment by 60fpshacksrock** [comment]
Is there a tool to retrieve the drive offset? Also I am using MPF.

Also, something must have went wrong with the DVD ripping as only part of the movie is playable.

**Comment by saramibreak** [comment]
This app only supports the recommended drive. Your drive is not supported in relation to ripping the CD.

**Comment by 60fpshacksrock** [comment]
Only DVD's then? Okay.

Thank you for letting me know. By the way the drive is this: HL-DT-ST DVDRAM GP55EX70 PF00 (USB)
