### ISSUE TITLE
DIC checks for free space even with commands that don't write to disk

### ISSUE THREAD

**Issue by malvarenga123** [saramibreak/DiscImageCreator#86]
**Describe the bug**
When using drive commands with DIC, it complains about free space on the hard disk.
It seems the first thing it checks it's free space before executing anything else.

The space reported is also wrong. When using the "cd" command the space is right:
reset
```
Disk Total Size: 9263093410927224 bytes
Disk Used  Size: 18446725639712451000 bytes
```
cd
```
Disk Total Size: 666798911488 bytes
Disk Used  Size: 592461225984 bytes
```

**Screenshots**
DiscImageCreator reset n
DiscImageCreator close n
DiscImageCreator stop n
etc

**Log file**

```
AppVersion
        x86, AnsiBuild, 20210911T132806
Disk Total Size: 9263093410927224 bytes
Disk Used  Size: 18446725639712451000 bytes
------------------------------------
Disk Space Size: 9281527408027840 bytes
 => There is not enough the disk space for dumping
```

**Comment by saramibreak** [comment]
Fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7152636/DiscImageCreator_test.zip)

**Comment by malvarenga123** [comment]
Thanks sarami, it works now with commands that don't write to disk, but still complains about free space using the data command.

**Comment by saramibreak** [comment]
added checking data, audio, sacd, fd, disk.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7166304/DiscImageCreator_test.zip)

**Comment by malvarenga123** [comment]
It's working now sarami, thanks!
