### ISSUE TITLE
Need help for Tages

### ISSUE THREAD

**Issue by gmipf** [saramibreak/DiscImageCreator#88]
I have a Tages CD-Rom, there is this command:

```
/r      Read CD from the reverse
                    For Alpha-Disc, Tages (very slow)
```

But if I try it says: 

```
AppVersion
        x64, AnsiBuild, 20211001T120113
Unknown option: [/r]
If you see the usage, execute .exe without argument
```

Can I dump the CD disc without /r?

**Comment by saramibreak** [comment]
Added: /t option in data command
`DiscImageCreator data <Drive> <Filepath> <DriveSpeed> <StartLBA> <EndLBA> /t <val>`

`val` is 20 by default.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/13692888/DiscImageCreator_test.zip)
[DiscImageCreator_test.tar.gz](https://github.com/saramibreak/DiscImageCreator/files/13692889/DiscImageCreator_test.tar.gz)

3 bin is generated.
`_Forward.bin`, `_Backward.bin`, `_BackToForward.bin`

**Comment by saramibreak** [comment]
https://github.com/saramibreak/DiscImageCreator/commit/c227b54f8a38d607cb7cf1d18533567da06b8387
