### ISSUE TITLE
Utilities disc won't dump because of EXE count

### ISSUE THREAD

**Issue by mnadareski** [saramibreak/DiscImageCreator#9]
I am trying to preserve a utilities disc that I had, and on it, there are hundreds of executables. IT doesn't even get to the point of ripping the disc, instead hard crashing before it even gets to that point. Attached are the output files it creates with the absolute newest version of DiscImageCreator.

[dumpinfo.zip](https://github.com/saramibreak/DiscImageCreator/files/1219431/dumpinfo.zip)

**Comment by saramibreak** [comment]
Changed max size. (1024 -> 4096)

**Comment by mnadareski** [comment]
Confirmed that the increased size worked on the utility disc. Thanks!
