### ISSUE TITLE
When to use C2ErrorProtect and ReadErrorProtect?

### ISSUE THREAD

**Issue by Feathered-Serpent** [saramibreak/DiscImageCreator#93]
**Version**
x86, AnsiBuild, 20211001T112852

**Describe the bug**
I have a disc with a huge file cd.idx which seems to include all other file data on the disc as well. Within the LBA of this file, there are 40000 ones where the program says "[ERROR] Number of sector(s) where user data doesn't match the expected ECC/EDC: 40000".

Should such a file placed in the C2ErrorProtect or the ReadErrorProtect list? ProtectionID wasn't able to find any copy protection.

**Screenshots**
![image](https://user-images.githubusercontent.com/72162369/140062534-8863c239-d30e-4074-92e5-fe7c19cdde5f.png)

**Comment by saramibreak** [comment]
http://forum.redump.org/post/96363/#p96363

It's a specification.

**Comment by Feathered-Serpent** [comment]
So technically the dump is still fine then? I mean the c2Error file states "No unintentional C2 errors" though for mpf in the submission file it states "Error Count: 40000"

Looking at the dump from the PX-W4012A the _disc file says
```
Detected a protected file [CD.IDX]. LBA 88 to 327768
Detected a protected file [CD.IDX]. LBA 88 to 327768
Set OpCode: 0xd8, SubCode: 8(Raw)
========== TOC with pregap ==========
	Track  1, Ctl 4, Mode 1, Index0   -150, Index1      0
	Track  2, Ctl 0, Mode 0, Index0 344528, Index1 344678
	Track  3, Ctl 4, Mode 1, Index0 345278, Index1 345503
	Track  1 Data Sector:      0 - 344527 (0000000 - 0x541cf)
	Track  3 Data Sector: 345278 - 346676 (0x544be - 0x54a34)```

**Comment by saramibreak** [comment]
It's correct cd.idx has some protected sectors but I’m not sure your dumped file is fine. If you are redump.org user, please contact Jackal.
