### ISSUE TITLE
[F:ReadExeFromFile][L:1456] GetLastError: 3

### ISSUE THREAD

**Issue by tjanas** [saramibreak/DiscImageCreator#96]
**Version**
20211001

**Describe the bug**
DiscImageCreator crashes during search protection.
```
Problem signature:
  Problem Event Name:	BEX
  Application Name:	DiscImageCreator.exe
  Application Version:	0.0.0.0
  Application Timestamp:	61567277
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2990
  Fault Module Timestamp:	5caeb859
  Exception Offset:	000872c4
  Exception Code:	c0000417
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	72b1
  Additional Information 2:	72b1ccdeb76503269fe3725d92a1cc0d
  Additional Information 3:	437c
  Additional Information 4:	437c427eb471184be5ec1e5bdb63ecc7
```

**Screenshots**
```
D:\tmp\MPF_net48_wip\net48\Programs\Creator\DiscImageCreator.exe cd F ISO\[PC] Canon CanoScan 4400F Setup CD-ROM [QH7-3156]\Canon CanoScan 4400F Setup CD-ROM [QH7-3156].bin 24 /c2 500 /q /ns /sf 
```
![image](https://user-images.githubusercontent.com/20304619/141146685-d9459b26-e0a2-4d48-96c6-ea143bfbbc8c.png)

**Disc title**
Canon CanoScan 4400F Setup CD-ROM - USCD2.0 - QH7-3156

**Disc ringcode**
91050000900C CanoScan 4400F USCD

**Log file**
[Canon CanoScan 4400F Setup CD-ROM [QH7-3156]_logs.zip](https://github.com/saramibreak/DiscImageCreator/files/7514144/Canon.CanoScan.4400F.Setup.CD-ROM.QH7-3156._logs.zip)

**Comment by saramibreak** [comment]
Test please.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7517891/DiscImageCreator_test.zip)

**Comment by tjanas** [comment]
> Test please. [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/7517891/DiscImageCreator_test.zip)

Thanks! This test build has fixed the issue.
