### ISSUE TITLE
[Request] Add option to configure number of read retries for bad sectors for DVD dumping

### ISSUE THREAD

**Issue by SilasLaspada** [saramibreak/DiscImageCreator#97]
**Is your feature request related to a problem? Please describe.**
If a DVD has stubborn errors, a user may want to retry reading a bad sector a large number of times, especially if a disc is difficult to replace.

**Describe the solution you'd like**
For there to be an option similar to the /c2 option for DVD dumping that allows a user to control the number of times DIC tries to reread a bad sector. I know that DVD's don't use C2, so a different name for the commanline option would have to be chosen.

**Describe alternatives you've considered**
Currently, attempting to clean the disc or buy a new copy is the only viable solution when using DIC, neither of which are always viable solutions.

**Comment by saramibreak** [comment]
>  I know that DVD's don't use C2

DVD (and BD) is read by using READ(12). This command gets the only main channel (2048 bytes), so the software can't find if it's good or not.

DVD also has EDC but raw dumping (2064 bytes) is needed to get it. Raw dumping is supported by a few drives.

**Comment by scsi-wuzzy** [comment]
I also would like to see this. I have had several discs (both DVD and BD, probably with manufacturing defects) that were only readable with multiple read retries. I was able to dump these discs using programs that do read retries. E.g., I set the number of software retries in ImgBurn to 20 and was able to create an ISO of each of the discs.

In contrast, DiscImageCreator was not able to read the discs, because it would abort after the first read error instead of retrying.

**Comment by saramibreak** [comment]
>In contrast, DiscImageCreator was not able to read the discs, because it aborts after the first read error reported by the drive. If it tried to read the same sector a few more times after each read error, it would have been able to read these discs like ImgBurn.

What kind of errors?

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8049158/DiscImageCreator_test.zip)
-added: /rr when DVD dumping
```
        /rr     Retry reading when error occurs
                        val     Max retry value (default: 10)
```
I've not tested.

**Comment by saramibreak** [comment]
Can you test it? If not tested, I'll discard this change and close the issue.

**Comment by SilasLaspada** [comment]
Hello! I will test soon, completely left my mind, sorry!

**Comment by SilasLaspada** [comment]
Got to test it today, seems to work as intended so far, but would it be possible to add an indicator of the current retry pass? It currently just says "Read retry from X", where I think it would be handy to say something along the lines of "Read retry from X (Pass Y/Z)".

**Comment by saramibreak** [comment]
Uploaded.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8113345/DiscImageCreator_test.zip)

**Comment by SilasLaspada** [comment]
Perfect, it seems to work well for me!

**Comment by scsi-wuzzy** [comment]
Would it be possible to enable this option for BD reading too? My most recent disc with this issue is a BD, but it looks like /rr isn't defined for BD reading.

**Comment by saramibreak** [comment]
Added.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8117297/DiscImageCreator_test.zip)

**Comment by scsi-wuzzy** [comment]
> Added. [DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/8117297/DiscImageCreator_test.zip)

It appears to work! I was able to dump the disc I previously showed the log of.
